- label: "JIRA"
  message: "$issuePrefix"
  color: "#0052CC"
  url: "https://jira.company.com/browse/$issuePrefix"
  when: "$issuePrefix"
  
  - label: "Preview"
  message: "PR $prNumber"
  color: "blue"
  url: "https://pr-$prNumber.company.com"
