language: java
jdk:
- openjdk11
branches:
  only:
  - main
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
before_install:
- openssl aes-256-cbc -K $encrypted_f1c9d72eb7c5_key -iv $encrypted_f1c9d72eb7c5_iv
  -in ./src/main/resources/application-secret.yml.enc -out ./src/main/resources/application-secret.yml -d
- chmod +x gradlew
script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/   # 배포 스크립트 디렉토리에 담기
  - cp appspec.yml before-deploy/    # 배포에 필요한 appspec.yml
  - cp dockerfile before-deploy/     # dockerfile 넘기기
  - cp build/libs/*.jar before-deploy/  # jar 파일 넘기기
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동후 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/CoCoBoB_Nginx.zip # deploy로 zip파일 이동


deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값

    bucket: cocobob-storage # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: cocobob-deploy-be # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      repo: PinkDumbbell/CocoBob-BE #Github 주소
      branch: main

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: cocobob-storage # S3 버킷

    key: CoCoBoB_Nginx.zip # 위에서 만든 zip 파일 이름 !! (꼭 맞춰서 적어야함)
    bundle_type: zip
    application: cocobob-be # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션

    deployment_group: cocobob-be-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: PinkDumbbell/CocoBob-BE
      branch: main

notifications:
  email:
    recipients:
      - jmkabc31@ajou.ac.kr
      - dre12am14@gmail.com
