language: java
jdk:
- openjdk11
branches:
  only:
  - main
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
before_install:
- openssl aes-256-cbc -K $encrypted_f1c9d72eb7c5_key -iv $encrypted_f1c9d72eb7c5_iv
  -in ./src/main/resources/application-secret.yml.enc -out ./src/main/resources/application-secret.yml -d
- chmod +x gradlew
script: "./gradlew clean build"
notifications:
  email:
    recipients:
    - jmkabc31@ajou.ac.kr
    - dre12am14@gmail.com
before_deploy:
  - zip -r cocobob-be-build * #현재 위치의 모든 파일을 newsum 이름으로 압축
  - mkdir -p cocobob-deploy-be #ocobob-deploy 디렉토리를 Travis CI가 실행중인 위치에 생성
  - mv cocobob-be-build.zip cocobob-deploy-be/cocobob-be-build.zip #deploy 폴더로 이동
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: cocobob-storage # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: cocobob-deploy-be # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      repo: PinkDumbbell/CocoBob-BE #Github 주소
      branch: main
