language: java
jdk:
  - openjdk11

branches:
  only:
    - CB-94-be-aws-ec-2-백엔드-서버-환경-구축-및-배포-자동화

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
before_install:
  - chmod +x gradlew

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - jmkabc31@ajou.ac.kr  #빌드 결과를 받아 볼 이메일 주소