version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deploy
    overwrite: yes

hooks:
  BeforeInstall:
    - location: /home/ec2-user/CocoBob-BE-CI,CD-test/script
      timeout: 300
      runas: root