version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deploy
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 300
      runas: root