version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/app/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: stop.sh
      timeout: 100
      runas: root

  ApplicationStart:
    - location: start.sh
      timeout: 100
      runas: root

  ValidateService:
    - location: health.sh
      timeout: 100
      runas: root