steps:
  - entrypoint: 'bash'
    args: ['echo', '1']

  - id: Grant execute permission for gradlew
    entrypoint: 'bash'
    args: ["-c", "chmod", "+x", "gradlew"]

  - entrypoint: 'bash'
    args: [ 'echo', '2' ]

  - id: Generate Application Environment Variables File(decryption)
    entrypoint: "bash"
    args: [
      "-c",
      "gpg --quiet --batch --yes --decrypt --passphrase=\"$$GNUPG2_PASSPHRASE\" --output src/main/resources/AuthKey_33CM4RFUVC.p8 src/main/resources/AuthKey_33CM4RFUVC.p8.gpg",
      "gpg --quiet --batch --yes --decrypt --passphrase=\"$$GNUPG2_PASSPHRASE\" --output src/main/resources/application-secret.yml src/main/resources/application-secret.yml.gpg"
    ]
    secretEnv: ["GNUPG2_PASSPHRASE"]

  - entrypoint: 'bash'
    args: [ 'echo', '3' ]

  - name: 'java:11'
    entrypoint: "bash"
    args: ["-c", "./gradlew build -x test"]

  - entrypoint: 'bash'
    args: [ 'echo', '4' ]

  - name: 'java:11'
    entrypoint: "bash"
    args: ["-c", "./gradlew test"]

  - entrypoint: 'bash'
    args: [ 'echo', '5' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/petalog-be-dev:$COMMIT_SHA', '.']

  - entrypoint: 'bash'
    args: [ 'echo', '6' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia.gcr.io/$PROJECT_ID/petalog-be-dev:$COMMIT_SHA']

  - entrypoint: 'bash'
    args: [ 'echo', '7' ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'petalog-be-dev'
      - '--image'
      - 'asia.gcr.io/$PROJECT_ID/petalog-be-dev:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3'

availableSecrets:
  secretManager:
    - versionName: projects/9031771856/secrets/GNUPG2_PASSPHRASE/versions/latest
      env: 'GNUPG2_PASSPHRASE'



