UPDATE `cocobob_dev`.`product` SET `name` = '조이 파테 습식사료 화이트피쉬 369g', `brand` = 'ZOE' WHERE (`product_id` = '803');
UPDATE `cocobob_dev`.`product` SET `name` = '오리 185g', `brand` = 'SHAKEAT' WHERE (`product_id` = '6');
UPDATE `cocobob_dev`.`product` SET `name` = '버라이어티팩 4개입', `brand` = 'SHAKEAT' WHERE (`product_id` = '800');
UPDATE `cocobob_dev`.`product` SET `name` = '말고기 185g', `brand` = 'SHAKEAT' WHERE (`product_id` = '5');
UPDATE `cocobob_dev`.`product` SET `name` = '닭간 185g', `brand` = 'SHAKEAT' WHERE (`product_id` = '4');
UPDATE `cocobob_dev`.`product` SET `name` = 'LID 그레인프리 칠면조 9.98kg', `brand` = 'go! ' WHERE (`product_id` = '767');
UPDATE `cocobob_dev`.`product` SET `name` = 'LID 그레인프리 칠면조 2.72kg', `brand` = 'go! ' WHERE (`product_id` = '766');
UPDATE `cocobob_dev`.`product` SET `name` = 'LID 그레인프리 연어 9.98kg', `brand` = 'go! ' WHERE (`product_id` = '765');
UPDATE `cocobob_dev`.`product` SET `name` = 'LID 그레인프리 연어 5.44kg', `brand` = 'go! ' WHERE (`product_id` = '764');
UPDATE `cocobob_dev`.`product` SET `name` = 'LID 그레인프리 연어 2.72kg', `brand` = 'go! ' WHERE (`product_id` = '763');
UPDATE `cocobob_dev`.`product` SET `name` = '사이언스 다이어트 퍼피 스몰포 치킨 7kg', `brand` = '힐스' WHERE (`product_id` = '737');
UPDATE `cocobob_dev`.`product` SET `name` = '사이언스 다이어트 퍼피 스몰포 치킨 1.5kg', `brand` = '힐스' WHERE (`product_id` = '736');
UPDATE `cocobob_dev`.`product` SET `name` = '사이언스 다이어트 퍼피 라지브리드 치킨 15kg', `brand` = '힐스' WHERE (`product_id` = '21');
UPDATE `cocobob_dev`.`product` SET `name` = '사이언스 다이어트 퍼피 라지브리드 치킨 15kg', `brand` = '힐스' WHERE (`product_id` = '735');
UPDATE `cocobob_dev`.`product` SET `name` = '사이언스 다이어트 어덜트 오랄케어 1.8kg', `brand` = '힐스' WHERE (`product_id` = '734');
UPDATE `cocobob_dev`.`product` SET `name` = '사이언스 다이어트 어덜트 스몰포 치킨 1.5kg', `brand` = '힐스' WHERE (`product_id` = '733');
UPDATE `cocobob_dev`.`product` SET `name` = '사이언스 다이어트 어덜트 스몰포 라이트 7kg', `brand` = '힐스' WHERE (`product_id` = '732');
UPDATE `cocobob_dev`.`product` SET `name` = '사이언스 다이어트 어덜트 스몰포 라이트 1.5kg', `brand` = '힐스' WHERE (`product_id` = '731');
UPDATE `cocobob_dev`.`product` SET `name` = '사이언스 다이어트 어덜트 스몰바이트 치킨 6.8kg', `brand` = '힐스' WHERE (`product_id` = '730');
UPDATE `cocobob_dev`.`product` SET `name` = '사이언스 다이어트 어덜트 스몰바이트 치킨 2kg', `brand` = '힐스' WHERE (`product_id` = '729');
UPDATE `cocobob_dev`.`product` SET `name` = '사이언스 다이어트 어덜트 스몰바이트 치킨 12kg', `brand` = '힐스' WHERE (`product_id` = '728');
UPDATE `cocobob_dev`.`product` SET `name` = '사이언스 다이어트 어덜트 스몰바이트 라이트 12kg', `brand` = '힐스' WHERE (`product_id` = '727');
UPDATE `cocobob_dev`.`product` SET `name` = '사이언스 다이어트 어덜트 센서티브 스토막앤스킨 13.6kg', `brand` = '힐스' WHERE (`product_id` = '726');
UPDATE `cocobob_dev`.`product` SET `name` = '사이언스 다이어트 어덜트 센서티브 스토막 앤 스킨 스몰앤미니 치킨 6.8kg', `brand` = '힐스' WHERE (`product_id` = '725');
UPDATE `cocobob_dev`.`product` SET `name` = '사이언스 다이어트 어덜트 라지브리드 치킨 6.8kg', `brand` = '힐스' WHERE (`product_id` = '724');
UPDATE `cocobob_dev`.`product` SET `name` = '사이언스 다이어트 어덜트 라지브리드 치킨 15kg', `brand` = '힐스' WHERE (`product_id` = '723');
UPDATE `cocobob_dev`.`product` SET `name` = '사이언스 다이어트 어덜트 6 + 라지브리드 치킨 15kg', `brand` = '힐스' WHERE (`product_id` = '722');
UPDATE `cocobob_dev`.`product` SET `name` = '사이언스 다이어트 어덜트 11 + 스몰포 2kg', `brand` = '힐스' WHERE (`product_id` = '721');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 동애등에 2.4kg', `brand` = '후코홀릭 ' WHERE (`product_id` = '720');
UPDATE `cocobob_dev`.`product` SET `name` = '오퍼스 팜 1kg', `brand` = '후새 독' WHERE (`product_id` = '719');
UPDATE `cocobob_dev`.`product` SET `name` = '오퍼스 팜 12kg', `brand` = '후새 독' WHERE (`product_id` = '718');
UPDATE `cocobob_dev`.`product` SET `name` = '오퍼스 오션 12kg', `brand` = '후새 독' WHERE (`product_id` = '15');
UPDATE `cocobob_dev`.`product` SET `name` = '오퍼스 오션 1.8kg', `brand` = '후새 독' WHERE (`product_id` = '717');
UPDATE `cocobob_dev`.`product` SET `name` = '오션케어 미니 1.8kg', `brand` = '후새 독' WHERE (`product_id` = '716');
UPDATE `cocobob_dev`.`product` SET `name` = '홀썸볼 쇠고기,닭고기,당근,보리,콩,비타민,미네랄 85g 10개 묶음', `brand` = '시저' WHERE (`product_id` = '13');
UPDATE `cocobob_dev`.`product` SET `name` = '홀썸볼 쇠고기,닭고기,당근,고구마,비타민,미네랄 85g 10개 묶음', `brand` = '시저' WHERE (`product_id` = '12');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 피에몬테 1kg', `brand` = '해피독' WHERE (`product_id` = '715');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 아일랜드 1kg', `brand` = '해피독' WHERE (`product_id` = '714');
UPDATE `cocobob_dev`.`product` SET `name` = '황태와 오리고기 3kg', `brand` = '한끼뚝딱' WHERE (`product_id` = '713');
UPDATE `cocobob_dev`.`product` SET `name` = '황태와 오리고기 1kg', `brand` = '한끼뚝딱' WHERE (`product_id` = '712');
UPDATE `cocobob_dev`.`product` SET `name` = '황태와 연어 3kg', `brand` = '한끼뚝딱' WHERE (`product_id` = '711');
UPDATE `cocobob_dev`.`product` SET `name` = '황태와 연어 1kg', `brand` = '한끼뚝딱' WHERE (`product_id` = '710');
UPDATE `cocobob_dev`.`product` SET `name` = '황태와 양고기 3kg', `brand` = '한끼뚝딱' WHERE (`product_id` = '709');
UPDATE `cocobob_dev`.`product` SET `name` = '황태와 양고기 1kg', `brand` = '한끼뚝딱' WHERE (`product_id` = '708');
UPDATE `cocobob_dev`.`product` SET `name` = '황태와 소고기 3kg', `brand` = '한끼뚝딱' WHERE (`product_id` = '707');
UPDATE `cocobob_dev`.`product` SET `name` = '황태와 소고기 1kg', `brand` = '한끼뚝딱' WHERE (`product_id` = '706');
UPDATE `cocobob_dev`.`product` SET `name` = '밥이보약 활기찬 노후 3.4kg', `brand` = '하림펫푸드' WHERE (`product_id` = '705');
UPDATE `cocobob_dev`.`product` SET `name` = '밥이보약 튼튼한 관절 라지바이트 8.5kg', `brand` = '하림펫푸드' WHERE (`product_id` = '704');
UPDATE `cocobob_dev`.`product` SET `name` = '밥이보약 튼튼한 관절 3.4kg', `brand` = '하림펫푸드' WHERE (`product_id` = '703');
UPDATE `cocobob_dev`.`product` SET `name` = '밥이보약 토탈웰빙 3.4kg', `brand` = '하림펫푸드' WHERE (`product_id` = '702');
UPDATE `cocobob_dev`.`product` SET `name` = '밥이보약 탄탄한 성장 3.4kg', `brand` = '하림펫푸드' WHERE (`product_id` = '701');
UPDATE `cocobob_dev`.`product` SET `name` = '밥이보약 알맞은 체중 3.4kg', `brand` = '하림펫푸드' WHERE (`product_id` = '700');
UPDATE `cocobob_dev`.`product` SET `name` = '밥이보약 빛나는 피모 3.4kg', `brand` = '하림펫푸드' WHERE (`product_id` = '699');
UPDATE `cocobob_dev`.`product` SET `name` = '밥이보약 건강한 장 3.4kg', `brand` = '하림펫푸드' WHERE (`product_id` = '698');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 밀 오리고기 60g 6개', `brand` = '하림펫푸드' WHERE (`product_id` = '697');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 밀 연어 60g 6개', `brand` = '하림펫푸드' WHERE (`product_id` = '696');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 밀 연어 200g 3개', `brand` = '하림펫푸드' WHERE (`product_id` = '695');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 밀 양고기 60g 6개', `brand` = '하림펫푸드' WHERE (`product_id` = '694');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 밀 소고기 60g 6개', `brand` = '하림펫푸드' WHERE (`product_id` = '693');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 밀 소고기 200g 3개', `brand` = '하림펫푸드' WHERE (`product_id` = '692');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 밀 돼지고기 60g 6개', `brand` = '하림펫푸드' WHERE (`product_id` = '691');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 밀 닭고기 60g 6개', `brand` = '하림펫푸드' WHERE (`product_id` = '3');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 밀 닭고기 60g 2개 + 소고기 60g 2개 + 연어 60g 2개', `brand` = '하림펫푸드' WHERE (`product_id` = '690');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 밀 닭고기 200g + 소고기 200g + 연어 200g', `brand` = '하림펫푸드' WHERE (`product_id` = '689');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 밀 그레인프리 오리고기 60g 6개', `brand` = '하림펫푸드' WHERE (`product_id` = '688');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 밀 그레인프리 연어 60g 6개', `brand` = '하림펫푸드' WHERE (`product_id` = '687');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 밀 그레인프리 양고기 60g 6개', `brand` = '하림펫푸드' WHERE (`product_id` = '686');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 밀 그레인프리 소고기 60g 6개', `brand` = '하림펫푸드' WHERE (`product_id` = '685');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 밀 그레인프리 돼지고기 60g 6개', `brand` = '하림펫푸드' WHERE (`product_id` = '684');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 동결건조 오븐베이크드 연어 어덜트 1.6kg', `brand` = '하림펫푸드' WHERE (`product_id` = '683');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 동결건조 오븐베이크드 닭고기 어덜트 1.6kg', `brand` = '하림펫푸드' WHERE (`product_id` = '682');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 동결건조 오븐베이크드 닭고기 시니어 1.6kg', `brand` = '하림펫푸드' WHERE (`product_id` = '681');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 그레인프리 크런치 연어 어덜트 1.6kg', `brand` = '하림펫푸드' WHERE (`product_id` = '680');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 그레인프리 크런치 양고기 어덜트 1.6kg', `brand` = '하림펫푸드' WHERE (`product_id` = '679');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 그레인프리 크런치 소고기 어덜트 1.6kg', `brand` = '하림펫푸드' WHERE (`product_id` = '678');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 그레인프리 크런치 소고기 시니어 1.6kg', `brand` = '하림펫푸드' WHERE (`product_id` = '677');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 그레인프리 크런치 닭고기 퍼피 1.6kg', `brand` = '하림펫푸드' WHERE (`product_id` = '676');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 그레인프리 크런치 닭고기 어덜트 1.6kg', `brand` = '하림펫푸드' WHERE (`product_id` = '675');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 그레인프리 크런치 닭고기 시니어 1.6kg', `brand` = '하림펫푸드' WHERE (`product_id` = '674');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 그레인프리 오븐베이크드 연어 어덜트 1.6kg', `brand` = '하림펫푸드' WHERE (`product_id` = '673');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 그레인프리 오븐베이크드 양고기 어덜트 1.6kg', `brand` = '하림펫푸드' WHERE (`product_id` = '672');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 그레인프리 오븐베이크드 소고기 어덜트 1.6kg', `brand` = '하림펫푸드' WHERE (`product_id` = '671');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 그레인프리 오븐베이크드 소고기 시니어 1.6kg', `brand` = '하림펫푸드' WHERE (`product_id` = '670');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 그레인프리 오븐베이크드 닭고기 퍼피 1.6kg', `brand` = '하림펫푸드' WHERE (`product_id` = '669');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 그레인프리 오븐베이크드 닭고기 어덜트 1.6kg', `brand` = '하림펫푸드' WHERE (`product_id` = '668');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 그레인프리 오븐베이크드 닭고기 시니어 1.6kg', `brand` = '하림펫푸드' WHERE (`product_id` = '667');
UPDATE `cocobob_dev`.`product` SET `name` = '수제사료 연어 1kg', `brand` = '하루애' WHERE (`product_id` = '666');
UPDATE `cocobob_dev`.`product` SET `name` = '수제사료 양고기 1kg', `brand` = '하루애' WHERE (`product_id` = '665');
UPDATE `cocobob_dev`.`product` SET `name` = '화이트 피쉬 퍼피 1kg', `brand` = '피쉬포독' WHERE (`product_id` = '664');
UPDATE `cocobob_dev`.`product` SET `name` = '화이트 피쉬 어덜트 6.3kg', `brand` = '피쉬포독' WHERE (`product_id` = '663');
UPDATE `cocobob_dev`.`product` SET `name` = '연어 토이 브리드 900g', `brand` = '피쉬포독' WHERE (`product_id` = '662');
UPDATE `cocobob_dev`.`product` SET `name` = '연어 어덜트 6.3kg', `brand` = '피쉬포독' WHERE (`product_id` = '661');
UPDATE `cocobob_dev`.`product` SET `name` = '프리미엄 진도 10kg', `brand` = 'ANF' WHERE (`product_id` = '660');
UPDATE `cocobob_dev`.`product` SET `name` = '프리미엄 램28 7.2kg', `brand` = 'ANF' WHERE (`product_id` = '756');
UPDATE `cocobob_dev`.`product` SET `name` = '프리미엄 램28 15kg', `brand` = 'ANF' WHERE (`product_id` = '755');
UPDATE `cocobob_dev`.`product` SET `name` = '퍼포먼스 17kg', `brand` = '프로베스트' WHERE (`product_id` = '659');
UPDATE `cocobob_dev`.`product` SET `name` = '양고기와 쌀 5kg', `brand` = '프로베스트' WHERE (`product_id` = '658');
UPDATE `cocobob_dev`.`product` SET `name` = '프레쉬 테트라 포크 스튜 354g', `brand` = 'now' WHERE (`product_id` = '799');
UPDATE `cocobob_dev`.`product` SET `name` = '프레쉬 테트라 터키 스튜 354g', `brand` = 'now' WHERE (`product_id` = '798');
UPDATE `cocobob_dev`.`product` SET `name` = '칠면조&고구마 11.34kg', `brand` = '퓨어비타' WHERE (`product_id` = '657');
UPDATE `cocobob_dev`.`product` SET `name` = '치킨&현미 6.8kg', `brand` = '퓨어비타' WHERE (`product_id` = '656');
UPDATE `cocobob_dev`.`product` SET `name` = '치킨&현미 2.26kg', `brand` = '퓨어비타' WHERE (`product_id` = '655');
UPDATE `cocobob_dev`.`product` SET `name` = '연어&완두콩 6.8kg', `brand` = '퓨어비타' WHERE (`product_id` = '654');
UPDATE `cocobob_dev`.`product` SET `name` = '연어&완두콩 2.26kg', `brand` = '퓨어비타' WHERE (`product_id` = '653');
UPDATE `cocobob_dev`.`product` SET `name` = '연어&완두콩 11.34kg', `brand` = '퓨어비타' WHERE (`product_id` = '652');
UPDATE `cocobob_dev`.`product` SET `name` = '오리와 감자 5kg', `brand` = '퓨어네이쳐' WHERE (`product_id` = '651');
UPDATE `cocobob_dev`.`product` SET `name` = '오리와 감자 1.2kg', `brand` = '퓨어네이쳐' WHERE (`product_id` = '650');
UPDATE `cocobob_dev`.`product` SET `name` = '연어와 감자 5kg', `brand` = '퓨어네이쳐' WHERE (`product_id` = '649');
UPDATE `cocobob_dev`.`product` SET `name` = '연어와 감자 1.2kg', `brand` = '퓨어네이쳐' WHERE (`product_id` = '648');
UPDATE `cocobob_dev`.`product` SET `name` = '양과 고구마 5kg', `brand` = '퓨어네이쳐' WHERE (`product_id` = '647');
UPDATE `cocobob_dev`.`product` SET `name` = '양과 고구마 1.2kg', `brand` = '퓨어네이쳐' WHERE (`product_id` = '646');
UPDATE `cocobob_dev`.`product` SET `name` = '프로플랜 퍼피 큰알갱이 대형견용 15.4kg', `brand` = '퓨리나' WHERE (`product_id` = '645');
UPDATE `cocobob_dev`.`product` SET `name` = '프로플랜 어덜트 큰알갱이 대형견용 15.4kg', `brand` = '퓨리나' WHERE (`product_id` = '644');
UPDATE `cocobob_dev`.`product` SET `name` = '건강한하루 피부개선 소프트 1kg', `brand` = '펫츠프라임' WHERE (`product_id` = '643');
UPDATE `cocobob_dev`.`product` SET `name` = '건강한하루 피부개선 1kg', `brand` = '펫츠프라임' WHERE (`product_id` = '642');
UPDATE `cocobob_dev`.`product` SET `name` = '건강한하루 닭고기&황태 소프트 1kg', `brand` = '펫츠프라임' WHERE (`product_id` = '641');
UPDATE `cocobob_dev`.`product` SET `name` = '보양대첩 하모니- 연어와 브로콜리 50g', `brand` = '펫가드' WHERE (`product_id` = '640');
UPDATE `cocobob_dev`.`product` SET `name` = '보양대첩 하모니 인섹트 밀월 1.8kg', `brand` = '펫가드' WHERE (`product_id` = '639');
UPDATE `cocobob_dev`.`product` SET `name` = '보양대첩 쿨링캔 8개입', `brand` = '펫가드' WHERE (`product_id` = '638');
UPDATE `cocobob_dev`.`product` SET `name` = '보양대첩 쿨링- 칠면조와 명태살 80g', `brand` = '펫가드' WHERE (`product_id` = '637');
UPDATE `cocobob_dev`.`product` SET `name` = '보양대첩 쿨링- 오리와 단호박 50g', `brand` = '펫가드' WHERE (`product_id` = '636');
UPDATE `cocobob_dev`.`product` SET `name` = '보양대첩 쿨링 오리와 황태 1.8kg', `brand` = '펫가드' WHERE (`product_id` = '635');
UPDATE `cocobob_dev`.`product` SET `name` = '보양대첩 워밍- 소고기와 초록입홍합 50g', `brand` = '펫가드' WHERE (`product_id` = '634');
UPDATE `cocobob_dev`.`product` SET `name` = '보양대첩 워밍- 소고기와 연어 80g', `brand` = '펫가드' WHERE (`product_id` = '633');
UPDATE `cocobob_dev`.`product` SET `name` = '보양대첩 워밍- 닭가슴살과 고구마 50g', `brand` = '펫가드' WHERE (`product_id` = '632');
UPDATE `cocobob_dev`.`product` SET `name` = '보양대첩 워밍 연어와 강황 1.8kg', `brand` = '펫가드' WHERE (`product_id` = '631');
UPDATE `cocobob_dev`.`product` SET `name` = '퍼피 치킨&치킨간 4.54kg', `brand` = 'ANF ' WHERE (`product_id` = '17');
UPDATE `cocobob_dev`.`product` SET `name` = '퍼피 치킨&치킨간 4.54kg', `brand` = 'HALO ' WHERE (`product_id` = '24');
UPDATE `cocobob_dev`.`product` SET `name` = '독 그레인프리 칠면조 캔 345g', `brand` = '퍼스트메이트' WHERE (`product_id` = '630');
UPDATE `cocobob_dev`.`product` SET `name` = '독 그레인프리 치킨&블루베리 스몰바이트 900g', `brand` = '퍼스트메이트' WHERE (`product_id` = '629');
UPDATE `cocobob_dev`.`product` SET `name` = '독 그레인프리 치킨 캔 345g', `brand` = '퍼스트메이트' WHERE (`product_id` = '628');
UPDATE `cocobob_dev`.`product` SET `name` = '독 그레인프리 오션피쉬 스몰바이트 900g', `brand` = '퍼스트메이트' WHERE (`product_id` = '627');
UPDATE `cocobob_dev`.`product` SET `name` = '독 그레인프리 연어 캔 345g', `brand` = '퍼스트메이트' WHERE (`product_id` = '626');
UPDATE `cocobob_dev`.`product` SET `name` = '하이포알러젠 타조와 파스닙 캔 400g', `brand` = '테라카니스' WHERE (`product_id` = '625');
UPDATE `cocobob_dev`.`product` SET `name` = '하이포알러젠 캥거루와 파스닙 캔 400g', `brand` = '테라카니스' WHERE (`product_id` = '624');
UPDATE `cocobob_dev`.`product` SET `name` = '퓨어미트 칠면조 캔 400g', `brand` = '테라카니스' WHERE (`product_id` = '623');
UPDATE `cocobob_dev`.`product` SET `name` = '퍼피 치킨과 호박 캔 200g', `brand` = '테라카니스' WHERE (`product_id` = '622');
UPDATE `cocobob_dev`.`product` SET `name` = '클래식 토끼와 애호박 캔 200g', `brand` = '테라카니스' WHERE (`product_id` = '621');
UPDATE `cocobob_dev`.`product` SET `name` = '클래식 칠면조와 현미 캔 200g', `brand` = '테라카니스' WHERE (`product_id` = '620');
UPDATE `cocobob_dev`.`product` SET `name` = '클래식 칠면조와 브로콜리 캔 200g', `brand` = '테라카니스' WHERE (`product_id` = '619');
UPDATE `cocobob_dev`.`product` SET `name` = '클래식 치킨과 아마란스 캔 200g', `brand` = '테라카니스' WHERE (`product_id` = '618');
UPDATE `cocobob_dev`.`product` SET `name` = '카니레오 치킨 2.5kg', `brand` = '테라카니스' WHERE (`product_id` = '617');
UPDATE `cocobob_dev`.`product` SET `name` = '카니레오 1kg', `brand` = '테라카니스' WHERE (`product_id` = '616');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 칠면조와 샐러리 캔 100g', `brand` = '테라카니스' WHERE (`product_id` = '615');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 치킨과 파스닙 캔 100g', `brand` = '테라카니스' WHERE (`product_id` = '614');
UPDATE `cocobob_dev`.`product` SET `name` = '레드 디톡스 캔 400g', `brand` = '테라카니스' WHERE (`product_id` = '613');
UPDATE `cocobob_dev`.`product` SET `name` = '라이트 칠면조와 샐러리 캔 400g', `brand` = '테라카니스' WHERE (`product_id` = '612');
UPDATE `cocobob_dev`.`product` SET `name` = '라이트 치킨과 애호박 캔 400g', `brand` = '테라카니스' WHERE (`product_id` = '611');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 토끼와 애호박 캔 200g', `brand` = '테라카니스' WHERE (`product_id` = '610');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 칠면조와 샐러리 캔 200g', `brand` = '테라카니스' WHERE (`product_id` = '609');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 치킨과 파스닙 캔 200g', `brand` = '테라카니스' WHERE (`product_id` = '608');
UPDATE `cocobob_dev`.`product` SET `name` = '오리 그레인프리 100g', `brand` = '크라운롤리 ' WHERE (`product_id` = '607');
UPDATE `cocobob_dev`.`product` SET `name` = '연어&오리 그레인프리 100g', `brand` = '크라운롤리 ' WHERE (`product_id` = '606');
UPDATE `cocobob_dev`.`product` SET `name` = '소고기&오리 그레인프리 100g', `brand` = '크라운롤리 ' WHERE (`product_id` = '605');
UPDATE `cocobob_dev`.`product` SET `name` = '닭고기 그레인프리 100g', `brand` = '크라운롤리 ' WHERE (`product_id` = '604');
UPDATE `cocobob_dev`.`product` SET `name` = '독 비프 앤 치킨 3kg', `brand` = '콩고' WHERE (`product_id` = '603');
UPDATE `cocobob_dev`.`product` SET `name` = '독 비프 앤 치킨 1.5kg', `brand` = '콩고' WHERE (`product_id` = '602');
UPDATE `cocobob_dev`.`product` SET `name` = '그랑크뤼 칠면조 5kg', `brand` = '캐니소스' WHERE (`product_id` = '601');
UPDATE `cocobob_dev`.`product` SET `name` = '그랑크뤼 칠면조 2kg', `brand` = '캐니소스' WHERE (`product_id` = '600');
UPDATE `cocobob_dev`.`product` SET `name` = '그랑크뤼 칠면조 10kg', `brand` = '캐니소스' WHERE (`product_id` = '599');
UPDATE `cocobob_dev`.`product` SET `name` = '그랑크뤼 서프앤터프 5kg', `brand` = '캐니소스' WHERE (`product_id` = '598');
UPDATE `cocobob_dev`.`product` SET `name` = '그랑크뤼 서프앤터프 2kg', `brand` = '캐니소스' WHERE (`product_id` = '597');
UPDATE `cocobob_dev`.`product` SET `name` = '그랑크뤼 서프앤터프 10kg', `brand` = '캐니소스' WHERE (`product_id` = '596');
UPDATE `cocobob_dev`.`product` SET `name` = '그랑크뤼 닭고기앤오리 5kg', `brand` = '캐니소스' WHERE (`product_id` = '595');
UPDATE `cocobob_dev`.`product` SET `name` = '그랑크뤼 닭고기앤오리 2kg', `brand` = '캐니소스' WHERE (`product_id` = '594');
UPDATE `cocobob_dev`.`product` SET `name` = '그랑크뤼 닭고기앤오리 10kg', `brand` = '캐니소스' WHERE (`product_id` = '593');
UPDATE `cocobob_dev`.`product` SET `name` = '데일리 디쉬 칠면조&연어 스튜 354g', `brand` = '카루' WHERE (`product_id` = '592');
UPDATE `cocobob_dev`.`product` SET `name` = '트루프레시 라지바이트 피시 4kg', `brand` = '카니러브' WHERE (`product_id` = '591');
UPDATE `cocobob_dev`.`product` SET `name` = '트루프레시 라지바이트 피시 11.4kg', `brand` = '카니러브' WHERE (`product_id` = '590');
UPDATE `cocobob_dev`.`product` SET `name` = '트루프레시 라지바이트 피시 1.4kg', `brand` = '카니러브' WHERE (`product_id` = '589');
UPDATE `cocobob_dev`.`product` SET `name` = '트루프레시 라지바이트 칠면조 4kg', `brand` = '카니러브' WHERE (`product_id` = '588');
UPDATE `cocobob_dev`.`product` SET `name` = '트루프레시 라지바이트 칠면조 11.4kg', `brand` = '카니러브' WHERE (`product_id` = '587');
UPDATE `cocobob_dev`.`product` SET `name` = '트루프레시 라지바이트 칠면조 1.4kg', `brand` = '카니러브' WHERE (`product_id` = '586');
UPDATE `cocobob_dev`.`product` SET `name` = '데일리솔루션 지아이&프로바이오틱스 2kg', `brand` = '청담닥터스랩' WHERE (`product_id` = '585');
UPDATE `cocobob_dev`.`product` SET `name` = '데일리솔루션 조인트&웨이트 2kg', `brand` = '청담닥터스랩' WHERE (`product_id` = '584');
UPDATE `cocobob_dev`.`product` SET `name` = '데일리솔루션 아이&브레인 2kg', `brand` = '청담닥터스랩' WHERE (`product_id` = '583');
UPDATE `cocobob_dev`.`product` SET `name` = '데일리솔루션 스킨&코트 2kg', `brand` = '청담닥터스랩' WHERE (`product_id` = '582');
UPDATE `cocobob_dev`.`product` SET `name` = '데일리솔루션 멀티&덴탈 2kg', `brand` = '청담닥터스랩' WHERE (`product_id` = '581');
UPDATE `cocobob_dev`.`product` SET `name` = '독 프로비넌스 하우라키 플레인즈 900g', `brand` = '지위픽' WHERE (`product_id` = '580');
UPDATE `cocobob_dev`.`product` SET `name` = '독 프로비넌스 하우라키 플레인즈 140g', `brand` = '지위픽' WHERE (`product_id` = '579');
UPDATE `cocobob_dev`.`product` SET `name` = '독 프로비넌스 이스트 케이프 900g', `brand` = '지위픽' WHERE (`product_id` = '578');
UPDATE `cocobob_dev`.`product` SET `name` = '독 프로비넌스 이스트 케이프 140g', `brand` = '지위픽' WHERE (`product_id` = '577');
UPDATE `cocobob_dev`.`product` SET `name` = '독 프로비넌스 오타고 밸리 900g', `brand` = '지위픽' WHERE (`product_id` = '576');
UPDATE `cocobob_dev`.`product` SET `name` = '독 프로비넌스 오타고 밸리 140g', `brand` = '지위픽' WHERE (`product_id` = '575');
UPDATE `cocobob_dev`.`product` SET `name` = '독 트라이프&양고기 캔 390g', `brand` = '지위픽' WHERE (`product_id` = '574');
UPDATE `cocobob_dev`.`product` SET `name` = '독 트라이프&양고기 캔 170g', `brand` = '지위픽' WHERE (`product_id` = '573');
UPDATE `cocobob_dev`.`product` SET `name` = '독 에어드라이 트라이프&양고기 454g', `brand` = '지위픽' WHERE (`product_id` = '572');
UPDATE `cocobob_dev`.`product` SET `name` = '독 에어드라이 트라이프&양고기 2.5kg', `brand` = '지위픽' WHERE (`product_id` = '571');
UPDATE `cocobob_dev`.`product` SET `name` = '독 에어드라이 트라이프&양고기 1kg', `brand` = '지위픽' WHERE (`product_id` = '570');
UPDATE `cocobob_dev`.`product` SET `name` = '독 에어드라이 양고기 4kg', `brand` = '지위픽' WHERE (`product_id` = '569');
UPDATE `cocobob_dev`.`product` SET `name` = '독 에어드라이 양고기 454g', `brand` = '지위픽' WHERE (`product_id` = '568');
UPDATE `cocobob_dev`.`product` SET `name` = '독 에어드라이 양고기 2.5kg', `brand` = '지위픽' WHERE (`product_id` = '567');
UPDATE `cocobob_dev`.`product` SET `name` = '독 에어드라이 양고기 1kg', `brand` = '지위픽' WHERE (`product_id` = '566');
UPDATE `cocobob_dev`.`product` SET `name` = '독 에어드라이 소고기 4kg', `brand` = '지위픽' WHERE (`product_id` = '565');
UPDATE `cocobob_dev`.`product` SET `name` = '독 에어드라이 소고기 454g', `brand` = '지위픽' WHERE (`product_id` = '564');
UPDATE `cocobob_dev`.`product` SET `name` = '독 에어드라이 소고기 2.5kg', `brand` = '지위픽' WHERE (`product_id` = '563');
UPDATE `cocobob_dev`.`product` SET `name` = '독 에어드라이 소고기 1kg', `brand` = '지위픽' WHERE (`product_id` = '562');
UPDATE `cocobob_dev`.`product` SET `name` = '독 에어드라이 사슴고기 454g', `brand` = '지위픽' WHERE (`product_id` = '561');
UPDATE `cocobob_dev`.`product` SET `name` = '독 에어드라이 사슴고기 2.5kg', `brand` = '지위픽' WHERE (`product_id` = '560');
UPDATE `cocobob_dev`.`product` SET `name` = '독 에어드라이 사슴고기 1kg', `brand` = '지위픽' WHERE (`product_id` = '559');
UPDATE `cocobob_dev`.`product` SET `name` = '독 에어드라이 닭고기 4kg', `brand` = '지위픽' WHERE (`product_id` = '558');
UPDATE `cocobob_dev`.`product` SET `name` = '독 에어드라이 닭고기 454g', `brand` = '지위픽' WHERE (`product_id` = '557');
UPDATE `cocobob_dev`.`product` SET `name` = '독 에어드라이 닭고기 2.5kg', `brand` = '지위픽' WHERE (`product_id` = '556');
UPDATE `cocobob_dev`.`product` SET `name` = '독 에어드라이 닭고기 1kg', `brand` = '지위픽' WHERE (`product_id` = '555');
UPDATE `cocobob_dev`.`product` SET `name` = '독 에어드라이 고등어&양고기 454g', `brand` = '지위픽' WHERE (`product_id` = '554');
UPDATE `cocobob_dev`.`product` SET `name` = '독 에어드라이 고등어&양고기 2.5kg', `brand` = '지위픽' WHERE (`product_id` = '553');
UPDATE `cocobob_dev`.`product` SET `name` = '독 에어드라이 고등어&양고기 1kg', `brand` = '지위픽' WHERE (`product_id` = '552');
UPDATE `cocobob_dev`.`product` SET `name` = '독 양고기 캔 170g', `brand` = '지위픽' WHERE (`product_id` = '551');
UPDATE `cocobob_dev`.`product` SET `name` = '독 소고기 캔 390g', `brand` = '지위픽' WHERE (`product_id` = '550');
UPDATE `cocobob_dev`.`product` SET `name` = '독 소고기 캔 170g', `brand` = '지위픽' WHERE (`product_id` = '549');
UPDATE `cocobob_dev`.`product` SET `name` = '독 사슴고기 캔 390g', `brand` = '지위픽' WHERE (`product_id` = '548');
UPDATE `cocobob_dev`.`product` SET `name` = '독 사슴고기 캔 170g', `brand` = '지위픽' WHERE (`product_id` = '547');
UPDATE `cocobob_dev`.`product` SET `name` = '독 고등어&양고기 캔 390g', `brand` = '지위픽' WHERE (`product_id` = '546');
UPDATE `cocobob_dev`.`product` SET `name` = '독 고등어&양고기 캔 170g', `brand` = '지위픽' WHERE (`product_id` = '545');
UPDATE `cocobob_dev`.`product` SET `name` = '화이트피쉬 6.12kg', `brand` = '지그니쳐' WHERE (`product_id` = '544');
UPDATE `cocobob_dev`.`product` SET `name` = '칠면조 1kg', `brand` = '지그니쳐' WHERE (`product_id` = '543');
UPDATE `cocobob_dev`.`product` SET `name` = '오리 5.66kg', `brand` = '지그니쳐' WHERE (`product_id` = '542');
UPDATE `cocobob_dev`.`product` SET `name` = '오리 1kg', `brand` = '지그니쳐' WHERE (`product_id` = '541');
UPDATE `cocobob_dev`.`product` SET `name` = '송어&연어 5.66kg', `brand` = '지그니쳐' WHERE (`product_id` = '540');
UPDATE `cocobob_dev`.`product` SET `name` = '송어&연어 1kg', `brand` = '지그니쳐' WHERE (`product_id` = '19');
UPDATE `cocobob_dev`.`product` SET `name` = '송어&연어 1kg', `brand` = '지그니쳐' WHERE (`product_id` = '539');
UPDATE `cocobob_dev`.`product` SET `name` = '조이 파테 습식사료 칠면조 369g', `brand` = 'ZOE' WHERE (`product_id` = '802');
UPDATE `cocobob_dev`.`product` SET `name` = '조이 파테 습식사료 치킨 369g', `brand` = 'ZOE' WHERE (`product_id` = '801');
UPDATE `cocobob_dev`.`product` SET `name` = '양고기&현미 스몰브리드 1.2kg', `brand` = '제니스' WHERE (`product_id` = '538');
UPDATE `cocobob_dev`.`product` SET `name` = '양고기&쌀 큰알갱이 1.2kg', `brand` = '제니스' WHERE (`product_id` = '537');
UPDATE `cocobob_dev`.`product` SET `name` = '양고기&쌀 작은알갱이 1.2kg', `brand` = '제니스' WHERE (`product_id` = '536');
UPDATE `cocobob_dev`.`product` SET `name` = '시니어 1.2kg', `brand` = '제니스' WHERE (`product_id` = '535');
UPDATE `cocobob_dev`.`product` SET `name` = '하이포알러지 소프트 1kg', `brand` = '인섹트도그' WHERE (`product_id` = '534');
UPDATE `cocobob_dev`.`product` SET `name` = '하이포알러지 빅 2kg', `brand` = '인섹트도그' WHERE (`product_id` = '533');
UPDATE `cocobob_dev`.`product` SET `name` = '하이포알러지 빅 10kg', `brand` = '인섹트도그' WHERE (`product_id` = '532');
UPDATE `cocobob_dev`.`product` SET `name` = '하이포알러지 미니 2kg', `brand` = '인섹트도그' WHERE (`product_id` = '531');
UPDATE `cocobob_dev`.`product` SET `name` = '홀리스틱 그레인프리 퍼포먼스 치킨 7kg', `brand` = '이즈칸' WHERE (`product_id` = '530');
UPDATE `cocobob_dev`.`product` SET `name` = '홀리스틱 그레인프리 퍼포먼스 치킨 15kg', `brand` = '이즈칸' WHERE (`product_id` = '529');
UPDATE `cocobob_dev`.`product` SET `name` = '파이브케어 6kg', `brand` = '이즈칸' WHERE (`product_id` = '528');
UPDATE `cocobob_dev`.`product` SET `name` = '파이브케어 2.1kg', `brand` = '이즈칸' WHERE (`product_id` = '527');
UPDATE `cocobob_dev`.`product` SET `name` = '주니어 라지브리드 15kg', `brand` = '이즈칸' WHERE (`product_id` = '526');
UPDATE `cocobob_dev`.`product` SET `name` = '주니어 7kg', `brand` = '이즈칸' WHERE (`product_id` = '525');
UPDATE `cocobob_dev`.`product` SET `name` = '어덜트 독 7.5kg', `brand` = '이즈칸' WHERE (`product_id` = '524');
UPDATE `cocobob_dev`.`product` SET `name` = '독 올라이프33 7.5kg', `brand` = '이즈칸' WHERE (`product_id` = '523');
UPDATE `cocobob_dev`.`product` SET `name` = '독 알러지프리 6kg', `brand` = '이즈칸' WHERE (`product_id` = '522');
UPDATE `cocobob_dev`.`product` SET `name` = '독 알러지프리 2.1kg', `brand` = '이즈칸' WHERE (`product_id` = '521');
UPDATE `cocobob_dev`.`product` SET `name` = '독 소프트살몬 6kg', `brand` = '이즈칸' WHERE (`product_id` = '520');
UPDATE `cocobob_dev`.`product` SET `name` = '독 램30 7.5kg', `brand` = '이즈칸' WHERE (`product_id` = '519');
UPDATE `cocobob_dev`.`product` SET `name` = '독 그레인프리 오리와 채소 6kg', `brand` = '이즈칸' WHERE (`product_id` = '518');
UPDATE `cocobob_dev`.`product` SET `name` = '독 그레인프리 연어와 감자 6kg', `brand` = '이즈칸' WHERE (`product_id` = '517');
UPDATE `cocobob_dev`.`product` SET `name` = '루츠 어덜트 독 칠면조 410g', `brand` = '이즈그림' WHERE (`product_id` = '516');
UPDATE `cocobob_dev`.`product` SET `name` = '루츠 어덜트 독 연어&송어&닭고기 410g', `brand` = '이즈그림' WHERE (`product_id` = '515');
UPDATE `cocobob_dev`.`product` SET `name` = '루츠 어덜트 독 멧돼지 410g', `brand` = '이즈그림' WHERE (`product_id` = '514');
UPDATE `cocobob_dev`.`product` SET `name` = '루츠 어덜트 독 말고기 410g', `brand` = '이즈그림' WHERE (`product_id` = '513');
UPDATE `cocobob_dev`.`product` SET `name` = '독-말고기&쵸크베리&샴피뇽 400g', `brand` = '이즈그림' WHERE (`product_id` = '512');
UPDATE `cocobob_dev`.`product` SET `name` = '독-거위&고구마&로즈힙 400g', `brand` = '이즈그림' WHERE (`product_id` = '511');
UPDATE `cocobob_dev`.`product` SET `name` = '뉴트리탑 퍼스트클래스 퍼피 1.2kg', `brand` = '윌로펫 ' WHERE (`product_id` = '510');
UPDATE `cocobob_dev`.`product` SET `name` = '뉴트리탑 퍼스트클래스 어덜트 1.2kg', `brand` = '윌로펫 ' WHERE (`product_id` = '509');
UPDATE `cocobob_dev`.`product` SET `name` = '뉴트리탑 퍼스트클래스 면역 1.2kg', `brand` = '윌로펫 ' WHERE (`product_id` = '508');
UPDATE `cocobob_dev`.`product` SET `name` = '오리 5.4kg', `brand` = '위시본' WHERE (`product_id` = '507');
UPDATE `cocobob_dev`.`product` SET `name` = '연어 10.89kg', `brand` = '위시본' WHERE (`product_id` = '506');
UPDATE `cocobob_dev`.`product` SET `name` = '퍼피 6kg', `brand` = '웰츠' WHERE (`product_id` = '505');
UPDATE `cocobob_dev`.`product` SET `name` = '퍼피 2.1kg', `brand` = '웰츠' WHERE (`product_id` = '504');
UPDATE `cocobob_dev`.`product` SET `name` = '시니어 독 6kg', `brand` = '웰츠' WHERE (`product_id` = '503');
UPDATE `cocobob_dev`.`product` SET `name` = '시니어 독 2.1kg', `brand` = '웰츠' WHERE (`product_id` = '502');
UPDATE `cocobob_dev`.`product` SET `name` = '독 저지방 다이어트 2.1kg', `brand` = '웰츠' WHERE (`product_id` = '501');
UPDATE `cocobob_dev`.`product` SET `name` = '독 오리 6kg', `brand` = '웰츠' WHERE (`product_id` = '30');
UPDATE `cocobob_dev`.`product` SET `name` = '독 오리 6kg', `brand` = '웰츠' WHERE (`product_id` = '500');
UPDATE `cocobob_dev`.`product` SET `name` = '독 오리 2.1kg', `brand` = '웰츠' WHERE (`product_id` = '499');
UPDATE `cocobob_dev`.`product` SET `name` = '독 연어 6kg', `brand` = '웰츠' WHERE (`product_id` = '498');
UPDATE `cocobob_dev`.`product` SET `name` = '독 연어 2.1kg', `brand` = '웰츠' WHERE (`product_id` = '497');
UPDATE `cocobob_dev`.`product` SET `name` = '독 아이케어 6kg', `brand` = '웰츠' WHERE (`product_id` = '496');
UPDATE `cocobob_dev`.`product` SET `name` = '독 아이케어 2.1kg', `brand` = '웰츠' WHERE (`product_id` = '495');
UPDATE `cocobob_dev`.`product` SET `name` = '독 관절케어 2.1kg', `brand` = '웰츠' WHERE (`product_id` = '494');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 동애등에 3.6kg', `brand` = '웰썸' WHERE (`product_id` = '493');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 동애등에 1.2kg', `brand` = '웰썸' WHERE (`product_id` = '492');
UPDATE `cocobob_dev`.`product` SET `name` = '코어 오션 1.8kg', `brand` = '웰니스' WHERE (`product_id` = '491');
UPDATE `cocobob_dev`.`product` SET `name` = '코어 스몰브리드 헬시웨이트 1.8kg', `brand` = '웰니스' WHERE (`product_id` = '490');
UPDATE `cocobob_dev`.`product` SET `name` = '코어 그레인프리 스몰브리드 1.8kg', `brand` = '웰니스' WHERE (`product_id` = '489');
UPDATE `cocobob_dev`.`product` SET `name` = '컴플리트 헬스 헬시 웨이트 스몰브리드 1.8kg', `brand` = '웰니스' WHERE (`product_id` = '488');
UPDATE `cocobob_dev`.`product` SET `name` = '컴플리트 헬스 그레인프리 스몰브리드 1.8kg', `brand` = '웰니스' WHERE (`product_id` = '487');
UPDATE `cocobob_dev`.`product` SET `name` = '심플 그레인프리 연어 2.04kg', `brand` = '웰니스' WHERE (`product_id` = '486');
UPDATE `cocobob_dev`.`product` SET `name` = '파이토 랩 시니어 1.2kg', `brand` = '원데이케어' WHERE (`product_id` = '485');
UPDATE `cocobob_dev`.`product` SET `name` = '파이토 랩 센서티브 1.2kg', `brand` = '원데이케어' WHERE (`product_id` = '484');
UPDATE `cocobob_dev`.`product` SET `name` = '파이토 랩 모빌리티 1.2kg', `brand` = '원데이케어' WHERE (`product_id` = '483');
UPDATE `cocobob_dev`.`product` SET `name` = '원데이케어 샘플키트', `brand` = '강아지 대통령' WHERE (`product_id` = '10');
UPDATE `cocobob_dev`.`product` SET `name` = '투뿔리아 수제사료 연어 800g', `brand` = '우리주' WHERE (`product_id` = '482');
UPDATE `cocobob_dev`.`product` SET `name` = '투뿔리아 수제사료 소고기 800g', `brand` = '우리주' WHERE (`product_id` = '481');
UPDATE `cocobob_dev`.`product` SET `name` = '투뿔리아 수제사료 동애등에 800g', `brand` = '우리주' WHERE (`product_id` = '480');
UPDATE `cocobob_dev`.`product` SET `name` = '올리브 어덜트 1kg', `brand` = '10억사료' WHERE (`product_id` = '35');
UPDATE `cocobob_dev`.`product` SET `name` = '올리브 센서티브 1kg', `brand` = '10억사료' WHERE (`product_id` = '34');
UPDATE `cocobob_dev`.`product` SET `name` = '올리브 센서티브 10kg', `brand` = '10억사료' WHERE (`product_id` = '33');
UPDATE `cocobob_dev`.`product` SET `name` = '올리브 맘&베이비 1kg', `brand` = '10억사료' WHERE (`product_id` = '32');
UPDATE `cocobob_dev`.`product` SET `name` = '홀리스틱 램29 2.7kg', `brand` = '올가밀' WHERE (`product_id` = '479');
UPDATE `cocobob_dev`.`product` SET `name` = '홀리스틱 램29 14kg', `brand` = '올가밀' WHERE (`product_id` = '478');
UPDATE `cocobob_dev`.`product` SET `name` = '독 화이트피쉬 2.04kg', `brand` = '오픈팜' WHERE (`product_id` = '477');
UPDATE `cocobob_dev`.`product` SET `name` = '독 포크 2.04kg', `brand` = '오픈팜' WHERE (`product_id` = '476');
UPDATE `cocobob_dev`.`product` SET `name` = '독 터키&치킨 2.04kg', `brand` = '오픈팜' WHERE (`product_id` = '475');
UPDATE `cocobob_dev`.`product` SET `name` = '독 살몬 2.04kg', `brand` = '오픈팜' WHERE (`product_id` = '474');
UPDATE `cocobob_dev`.`product` SET `name` = '참치,소고기&소고기간 파우치 69g', `brand` = '오쥬 바이 로우즈' WHERE (`product_id` = '473');
UPDATE `cocobob_dev`.`product` SET `name` = '연어,소고기&참치 파우치 69g', `brand` = '오쥬 바이 로우즈' WHERE (`product_id` = '472');
UPDATE `cocobob_dev`.`product` SET `name` = '닭가슴살&호박 파우치 69g', `brand` = '오쥬 바이 로우즈' WHERE (`product_id` = '471');
UPDATE `cocobob_dev`.`product` SET `name` = '닭가슴살&오리 파우치 69g', `brand` = '오쥬 바이 로우즈' WHERE (`product_id` = '470');
UPDATE `cocobob_dev`.`product` SET `name` = '닭가슴살&닭간 파우치 69g', `brand` = '오쥬 바이 로우즈' WHERE (`product_id` = '469');
UPDATE `cocobob_dev`.`product` SET `name` = '피트앤트림 독 11.4kg', `brand` = '오리젠' WHERE (`product_id` = '468');
UPDATE `cocobob_dev`.`product` SET `name` = '퍼피 라지브리드 6kg', `brand` = '오리젠' WHERE (`product_id` = '467');
UPDATE `cocobob_dev`.`product` SET `name` = '퍼피 라지브리드 11.4kg', `brand` = '오리젠' WHERE (`product_id` = '466');
UPDATE `cocobob_dev`.`product` SET `name` = '퍼피 340g', `brand` = '오리젠' WHERE (`product_id` = '465');
UPDATE `cocobob_dev`.`product` SET `name` = '퍼피 2kg', `brand` = '오리젠' WHERE (`product_id` = '464');
UPDATE `cocobob_dev`.`product` SET `name` = '퍼피 11.4kg', `brand` = '오리젠' WHERE (`product_id` = '463');
UPDATE `cocobob_dev`.`product` SET `name` = '오리지널 독 6kg', `brand` = '오리젠' WHERE (`product_id` = '462');
UPDATE `cocobob_dev`.`product` SET `name` = '오리지널 독 340g', `brand` = '오리젠' WHERE (`product_id` = '461');
UPDATE `cocobob_dev`.`product` SET `name` = '오리지널 독 2kg', `brand` = '오리젠' WHERE (`product_id` = '460');
UPDATE `cocobob_dev`.`product` SET `name` = '오리지널 독 11.4kg', `brand` = '오리젠' WHERE (`product_id` = '459');
UPDATE `cocobob_dev`.`product` SET `name` = '시니어 독 340g', `brand` = '오리젠' WHERE (`product_id` = '458');
UPDATE `cocobob_dev`.`product` SET `name` = '시니어 독 11.4kg', `brand` = '오리젠' WHERE (`product_id` = '457');
UPDATE `cocobob_dev`.`product` SET `name` = '스몰브리드 4.5kg', `brand` = '오리젠' WHERE (`product_id` = '456');
UPDATE `cocobob_dev`.`product` SET `name` = '스몰브리드 1.8kg', `brand` = '오리젠' WHERE (`product_id` = '455');
UPDATE `cocobob_dev`.`product` SET `name` = '6 피쉬 독 340g', `brand` = '오리젠' WHERE (`product_id` = '454');
UPDATE `cocobob_dev`.`product` SET `name` = '6 피쉬 독 2kg', `brand` = '오리젠' WHERE (`product_id` = '453');
UPDATE `cocobob_dev`.`product` SET `name` = '퍼피 맥시 3kg', `brand` = '어드밴스' WHERE (`product_id` = '452');
UPDATE `cocobob_dev`.`product` SET `name` = '퍼피 맥시 12kg', `brand` = '어드밴스' WHERE (`product_id` = '451');
UPDATE `cocobob_dev`.`product` SET `name` = '래브라도&골든 리트리버 12kg', `brand` = '어드밴스' WHERE (`product_id` = '450');
UPDATE `cocobob_dev`.`product` SET `name` = '독 퍼피 센시티브 3kg', `brand` = '어드밴스' WHERE (`product_id` = '449');
UPDATE `cocobob_dev`.`product` SET `name` = '독 퍼피 미디엄 3kg', `brand` = '어드밴스' WHERE (`product_id` = '448');
UPDATE `cocobob_dev`.`product` SET `name` = '독 퍼피 미디엄 12kg', `brand` = '어드밴스' WHERE (`product_id` = '447');
UPDATE `cocobob_dev`.`product` SET `name` = '독 퍼피 미니 800g', `brand` = '어드밴스' WHERE (`product_id` = '446');
UPDATE `cocobob_dev`.`product` SET `name` = '독 퍼피 미니 7.5kg', `brand` = '어드밴스' WHERE (`product_id` = '445');
UPDATE `cocobob_dev`.`product` SET `name` = '독 퍼피 미니 3kg', `brand` = '어드밴스' WHERE (`product_id` = '444');
UPDATE `cocobob_dev`.`product` SET `name` = '독 저먼 셰퍼드 어덜트 12kg', `brand` = '어드밴스' WHERE (`product_id` = '443');
UPDATE `cocobob_dev`.`product` SET `name` = '독 어덜트 미디엄 3kg', `brand` = '어드밴스' WHERE (`product_id` = '442');
UPDATE `cocobob_dev`.`product` SET `name` = '독 어덜트 미디엄 14kg', `brand` = '어드밴스' WHERE (`product_id` = '441');
UPDATE `cocobob_dev`.`product` SET `name` = '독 어덜트 미니 800g', `brand` = '어드밴스' WHERE (`product_id` = '440');
UPDATE `cocobob_dev`.`product` SET `name` = '독 어덜트 미니 7.5kg', `brand` = '어드밴스' WHERE (`product_id` = '439');
UPDATE `cocobob_dev`.`product` SET `name` = '독 어덜트 미니 3kg', `brand` = '어드밴스' WHERE (`product_id` = '438');
UPDATE `cocobob_dev`.`product` SET `name` = '독 어덜트 맥시 14kg', `brand` = '어드밴스' WHERE (`product_id` = '437');
UPDATE `cocobob_dev`.`product` SET `name` = '독 시니어 미디엄 3kg', `brand` = '어드밴스' WHERE (`product_id` = '436');
UPDATE `cocobob_dev`.`product` SET `name` = '독 시니어 미디엄 12kg', `brand` = '어드밴스' WHERE (`product_id` = '435');
UPDATE `cocobob_dev`.`product` SET `name` = '독 시니어 미니 7.5kg', `brand` = '어드밴스' WHERE (`product_id` = '434');
UPDATE `cocobob_dev`.`product` SET `name` = '독 시니어 미니 3kg', `brand` = '어드밴스' WHERE (`product_id` = '433');
UPDATE `cocobob_dev`.`product` SET `name` = '독 센시티브 미니 800g', `brand` = '어드밴스' WHERE (`product_id` = '432');
UPDATE `cocobob_dev`.`product` SET `name` = '독 센시티브 미니 7.5kg', `brand` = '어드밴스' WHERE (`product_id` = '431');
UPDATE `cocobob_dev`.`product` SET `name` = '독 센시티브 미니 3kg', `brand` = '어드밴스' WHERE (`product_id` = '430');
UPDATE `cocobob_dev`.`product` SET `name` = '독 센시티브 3kg', `brand` = '어드밴스' WHERE (`product_id` = '429');
UPDATE `cocobob_dev`.`product` SET `name` = '독 센시티브 12kg', `brand` = '어드밴스' WHERE (`product_id` = '428');
UPDATE `cocobob_dev`.`product` SET `name` = '독 라이트 미디엄 3kg', `brand` = '어드밴스' WHERE (`product_id` = '427');
UPDATE `cocobob_dev`.`product` SET `name` = '독 라이트 미디엄 12kg', `brand` = '어드밴스' WHERE (`product_id` = '426');
UPDATE `cocobob_dev`.`product` SET `name` = '독 라이트 미니 7.5kg', `brand` = '어드밴스' WHERE (`product_id` = '425');
UPDATE `cocobob_dev`.`product` SET `name` = '독 라이트 미니 3kg', `brand` = '어드밴스' WHERE (`product_id` = '424');
UPDATE `cocobob_dev`.`product` SET `name` = '어덜트 저알러지식 가드오브비건 9.53kg', `brand` = 'HALO ' WHERE (`product_id` = '776');
UPDATE `cocobob_dev`.`product` SET `name` = '어덜트 저알러지식 가드오브비건 1.81kg', `brand` = 'HALO ' WHERE (`product_id` = '775');
UPDATE `cocobob_dev`.`product` SET `name` = '어덜트 스튜 칠면조&연어 156g X 10개입', `brand` = 'HALO ' WHERE (`product_id` = '774');
UPDATE `cocobob_dev`.`product` SET `name` = '어덜트 스튜 칠면조&연어 156g', `brand` = 'HALO ' WHERE (`product_id` = '773');
UPDATE `cocobob_dev`.`product` SET `name` = '홀리스틱 양고기&연어 독 1kg', `brand` = '앱솔루트' WHERE (`product_id` = '423');
UPDATE `cocobob_dev`.`product` SET `name` = '홀리스틱 양고기&연어 독 100g', `brand` = '앱솔루트' WHERE (`product_id` = '422');
UPDATE `cocobob_dev`.`product` SET `name` = '홀리스틱 양고기&고등어 독 100g', `brand` = '앱솔루트' WHERE (`product_id` = '421');
UPDATE `cocobob_dev`.`product` SET `name` = '홀리스틱 소고기&사슴고기 독 1kg', `brand` = '앱솔루트' WHERE (`product_id` = '420');
UPDATE `cocobob_dev`.`product` SET `name` = '홀리스틱 소고기&사슴고기 독 100g', `brand` = '앱솔루트' WHERE (`product_id` = '419');
UPDATE `cocobob_dev`.`product` SET `name` = '홀리스틱 닭고기&호키 독 1kg', `brand` = '앱솔루트' WHERE (`product_id` = '418');
UPDATE `cocobob_dev`.`product` SET `name` = '홀리스틱 닭고기&호키 독 100g', `brand` = '앱솔루트' WHERE (`product_id` = '417');
UPDATE `cocobob_dev`.`product` SET `name` = '퍼피 연어 5kg', `brand` = '아투' WHERE (`product_id` = '416');
UPDATE `cocobob_dev`.`product` SET `name` = '퍼피 연어 1.5kg', `brand` = '아투' WHERE (`product_id` = '415');
UPDATE `cocobob_dev`.`product` SET `name` = '독 칠면조 5kg', `brand` = '아투' WHERE (`product_id` = '414');
UPDATE `cocobob_dev`.`product` SET `name` = '독 칠면조 10kg', `brand` = '아투' WHERE (`product_id` = '413');
UPDATE `cocobob_dev`.`product` SET `name` = '독 칠면조 1.5kg', `brand` = '아투' WHERE (`product_id` = '412');
UPDATE `cocobob_dev`.`product` SET `name` = '독 치킨 5kg', `brand` = '아투' WHERE (`product_id` = '411');
UPDATE `cocobob_dev`.`product` SET `name` = '독 치킨 10kg', `brand` = '아투' WHERE (`product_id` = '410');
UPDATE `cocobob_dev`.`product` SET `name` = '독 치킨 1.5kg', `brand` = '아투' WHERE (`product_id` = '409');
UPDATE `cocobob_dev`.`product` SET `name` = '독 오리 10kg', `brand` = '아투' WHERE (`product_id` = '408');
UPDATE `cocobob_dev`.`product` SET `name` = '독 연어 5kg', `brand` = '아투' WHERE (`product_id` = '407');
UPDATE `cocobob_dev`.`product` SET `name` = '독 연어 10kg', `brand` = '아투' WHERE (`product_id` = '406');
UPDATE `cocobob_dev`.`product` SET `name` = '독 연어 1.5kg', `brand` = '아투' WHERE (`product_id` = '405');
UPDATE `cocobob_dev`.`product` SET `name` = '독 쉘피쉬 5kg', `brand` = '아투' WHERE (`product_id` = '404');
UPDATE `cocobob_dev`.`product` SET `name` = '독 쉘피쉬 10kg', `brand` = '아투' WHERE (`product_id` = '403');
UPDATE `cocobob_dev`.`product` SET `name` = '독 쉘피쉬 1.5kg', `brand` = '아투' WHERE (`product_id` = '402');
UPDATE `cocobob_dev`.`product` SET `name` = '헤리티지 퍼피 앤 주니어 독 6kg', `brand` = '아카나' WHERE (`product_id` = '401');
UPDATE `cocobob_dev`.`product` SET `name` = '헤리티지 퍼피 앤 주니어 독 2kg', `brand` = '아카나' WHERE (`product_id` = '399');
UPDATE `cocobob_dev`.`product` SET `name` = '헤리티지 퍼피 앤 주니어 독 2kg', `brand` = '아카나' WHERE (`product_id` = '400');
UPDATE `cocobob_dev`.`product` SET `name` = '헤리티지 퍼피 앤 주니어 독 11.4kg', `brand` = '아카나' WHERE (`product_id` = '398');
UPDATE `cocobob_dev`.`product` SET `name` = '헤리티지 어덜트 라지브리드 독  11.4kg', `brand` = '아카나' WHERE (`product_id` = '397');
UPDATE `cocobob_dev`.`product` SET `name` = '헤리티지 시니어 독 6kg', `brand` = '아카나' WHERE (`product_id` = '396');
UPDATE `cocobob_dev`.`product` SET `name` = '헤리티지 시니어 독 2kg', `brand` = '아카나' WHERE (`product_id` = '395');
UPDATE `cocobob_dev`.`product` SET `name` = '헤리티지 시니어 독 11.4kg', `brand` = '아카나' WHERE (`product_id` = '394');
UPDATE `cocobob_dev`.`product` SET `name` = '헤리티지 라이트 앤 피트 독 11.4kg', `brand` = '아카나' WHERE (`product_id` = '393');
UPDATE `cocobob_dev`.`product` SET `name` = '프리런 덕 6kg', `brand` = '아카나' WHERE (`product_id` = '392');
UPDATE `cocobob_dev`.`product` SET `name` = '프리런 덕 2kg x 2개 + 캠핑의자 + 사료소분통 + 프레이리 폴트리 독 340g 증정', `brand` = '아카나' WHERE (`product_id` = '31');
UPDATE `cocobob_dev`.`product` SET `name` = '프리런 덕 2kg', `brand` = '아카나' WHERE (`product_id` = '391');
UPDATE `cocobob_dev`.`product` SET `name` = '프리런 덕 11.4kg', `brand` = '아카나' WHERE (`product_id` = '390');
UPDATE `cocobob_dev`.`product` SET `name` = '퍼피 스몰브리드 2kg', `brand` = '아카나' WHERE (`product_id` = '389');
UPDATE `cocobob_dev`.`product` SET `name` = '클래식 프레이리 폴트리 독 6kg', `brand` = '아카나' WHERE (`product_id` = '388');
UPDATE `cocobob_dev`.`product` SET `name` = '클래식 프레이리 폴트리 독 340g', `brand` = '아카나' WHERE (`product_id` = '29');
UPDATE `cocobob_dev`.`product` SET `name` = '클래식 프레이리 폴트리 독 340g', `brand` = '아카나' WHERE (`product_id` = '387');
UPDATE `cocobob_dev`.`product` SET `name` = '클래식 프레이리 폴트리 독 2kg', `brand` = '아카나' WHERE (`product_id` = '386');
UPDATE `cocobob_dev`.`product` SET `name` = '클래식 와일드 코스트 독 6kg', `brand` = '아카나' WHERE (`product_id` = '385');
UPDATE `cocobob_dev`.`product` SET `name` = '클래식 와일드 코스트 독 340g', `brand` = '아카나' WHERE (`product_id` = '384');
UPDATE `cocobob_dev`.`product` SET `name` = '클래식 와일드 코스트 독 2kg', `brand` = '아카나' WHERE (`product_id` = '383');
UPDATE `cocobob_dev`.`product` SET `name` = '와일드 프레이리 독 6kg', `brand` = '아카나' WHERE (`product_id` = '382');
UPDATE `cocobob_dev`.`product` SET `name` = '어덜트 스몰브리드 6kg', `brand` = '아카나' WHERE (`product_id` = '381');
UPDATE `cocobob_dev`.`product` SET `name` = '어덜트 스몰브리드 2kg', `brand` = '아카나' WHERE (`product_id` = '380');
UPDATE `cocobob_dev`.`product` SET `name` = '어덜트 독 6kg', `brand` = '아카나' WHERE (`product_id` = '379');
UPDATE `cocobob_dev`.`product` SET `name` = '어덜트 독 2kg', `brand` = '아카나' WHERE (`product_id` = '378');
UPDATE `cocobob_dev`.`product` SET `name` = '어덜트 독 11.4kg', `brand` = '아카나' WHERE (`product_id` = '377');
UPDATE `cocobob_dev`.`product` SET `name` = '리저널 패시피카 독 6kg', `brand` = '아카나' WHERE (`product_id` = '376');
UPDATE `cocobob_dev`.`product` SET `name` = '리저널 패시피카 독 340g', `brand` = '아카나' WHERE (`product_id` = '375');
UPDATE `cocobob_dev`.`product` SET `name` = '리저널 패시피카 독 2kg', `brand` = '아카나' WHERE (`product_id` = '374');
UPDATE `cocobob_dev`.`product` SET `name` = '수제사료 한우 800g', `brand` = '아침애' WHERE (`product_id` = '373');
UPDATE `cocobob_dev`.`product` SET `name` = '수제사료 피부개선 1.8kg', `brand` = '아침애' WHERE (`product_id` = '372');
UPDATE `cocobob_dev`.`product` SET `name` = '수제사료 저칼로리 곤약 다이어트 1.8kg', `brand` = '아침애' WHERE (`product_id` = '371');
UPDATE `cocobob_dev`.`product` SET `name` = '수제사료 저단백 해조류 1.8kg', `brand` = '아침애' WHERE (`product_id` = '370');
UPDATE `cocobob_dev`.`product` SET `name` = '수제사료 오리&연어&감자 1.8kg', `brand` = '아침애' WHERE (`product_id` = '369');
UPDATE `cocobob_dev`.`product` SET `name` = '슬로우 베이크드 연어 1.5kg', `brand` = '아이누' WHERE (`product_id` = '368');
UPDATE `cocobob_dev`.`product` SET `name` = '펠리쿠치나 오리고기 3kg', `brand` = '아스쿠' WHERE (`product_id` = '367');
UPDATE `cocobob_dev`.`product` SET `name` = '펠리쿠치나 오리고기 1.2kg', `brand` = '아스쿠' WHERE (`product_id` = '366');
UPDATE `cocobob_dev`.`product` SET `name` = '펠리쿠치나 연어 3kg', `brand` = '아스쿠' WHERE (`product_id` = '365');
UPDATE `cocobob_dev`.`product` SET `name` = '펠리쿠치나 연어 1.2kg', `brand` = '아스쿠' WHERE (`product_id` = '364');
UPDATE `cocobob_dev`.`product` SET `name` = '펠리쿠치나 소고기 3kg', `brand` = '아스쿠' WHERE (`product_id` = '363');
UPDATE `cocobob_dev`.`product` SET `name` = '피너클 칠면조&펌킨 4.7kg', `brand` = '아보덤' WHERE (`product_id` = '362');
UPDATE `cocobob_dev`.`product` SET `name` = '피너클 칠면조&펌킨 10.89kg', `brand` = '아보덤' WHERE (`product_id` = '361');
UPDATE `cocobob_dev`.`product` SET `name` = '피너클 연어&펌킨 4.7kg', `brand` = '아보덤' WHERE (`product_id` = '360');
UPDATE `cocobob_dev`.`product` SET `name` = '피너클 연어&펌킨 10.89kg', `brand` = '아보덤' WHERE (`product_id` = '359');
UPDATE `cocobob_dev`.`product` SET `name` = '피너클 송어&고구마 10.89kg', `brand` = '아보덤' WHERE (`product_id` = '358');
UPDATE `cocobob_dev`.`product` SET `name` = '조인트 헬스 그레인프리 치킨 1kg', `brand` = '아보덤' WHERE (`product_id` = '357');
UPDATE `cocobob_dev`.`product` SET `name` = '조인트 헬스 그레인프리 4.7kg', `brand` = '아보덤' WHERE (`product_id` = '356');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 치킨&베지터블 4.7kg', `brand` = '아보덤' WHERE (`product_id` = '355');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 치킨&베지터블 1kg', `brand` = '아보덤' WHERE (`product_id` = '354');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 치킨&베지터블 10.89kg', `brand` = '아보덤' WHERE (`product_id` = '353');
UPDATE `cocobob_dev`.`product` SET `name` = '도그 치킨 어덜트 4kg', `brand` = '아미티' WHERE (`product_id` = '352');
UPDATE `cocobob_dev`.`product` SET `name` = '도그 치킨 어덜트 14kg', `brand` = '아미티' WHERE (`product_id` = '351');
UPDATE `cocobob_dev`.`product` SET `name` = '도그 이베리안포크 어덜트 4kg', `brand` = '아미티' WHERE (`product_id` = '350');
UPDATE `cocobob_dev`.`product` SET `name` = '도그 이베리안포크 어덜트 14kg', `brand` = '아미티' WHERE (`product_id` = '349');
UPDATE `cocobob_dev`.`product` SET `name` = '도그 살몬 어덜트 4kg', `brand` = '아미티' WHERE (`product_id` = '348');
UPDATE `cocobob_dev`.`product` SET `name` = '도그 살몬 어덜트 14kg', `brand` = '아미티' WHERE (`product_id` = '347');
UPDATE `cocobob_dev`.`product` SET `name` = '흰살생선과 야채 캔 100g 12개 묶음', `brand` = '시저' WHERE (`product_id` = '346');
UPDATE `cocobob_dev`.`product` SET `name` = '흰살생선과 야채 캔 100g', `brand` = '시저' WHERE (`product_id` = '345');
UPDATE `cocobob_dev`.`product` SET `name` = '홀썸볼 쇠고기,닭고기,당근,보리,콩,비타민,미네랄 85g', `brand` = '시저' WHERE (`product_id` = '344');
UPDATE `cocobob_dev`.`product` SET `name` = '홀썸볼 닭고기,당근,보리,콩,비타민,미네랄 85g 10개 묶음', `brand` = '시저' WHERE (`product_id` = '11');
UPDATE `cocobob_dev`.`product` SET `name` = '연어와 감자 캔 100g 5개 묶음', `brand` = '시저' WHERE (`product_id` = '343');
UPDATE `cocobob_dev`.`product` SET `name` = '연어와 감자 캔 100g 12개 묶음', `brand` = '시저' WHERE (`product_id` = '342');
UPDATE `cocobob_dev`.`product` SET `name` = '연어와 감자 캔 100g', `brand` = '시저' WHERE (`product_id` = '341');
UPDATE `cocobob_dev`.`product` SET `name` = '양고기 캔 100g 12개 묶음', `brand` = '시저' WHERE (`product_id` = '340');
UPDATE `cocobob_dev`.`product` SET `name` = '양고기 캔 100g', `brand` = '시저' WHERE (`product_id` = '339');
UPDATE `cocobob_dev`.`product` SET `name` = '심플리 크래프티드 닭고기,당근,완두콩 37g', `brand` = '시저' WHERE (`product_id` = '338');
UPDATE `cocobob_dev`.`product` SET `name` = '심플리 크래프티드 닭고기,당근,감자,완두콩 37g 12개 묶음', `brand` = '시저' WHERE (`product_id` = '337');
UPDATE `cocobob_dev`.`product` SET `name` = '심플리 크래프티드 닭고기,당근,감자,완두콩 37g', `brand` = '시저' WHERE (`product_id` = '336');
UPDATE `cocobob_dev`.`product` SET `name` = '심플리 크래프티드 닭고기,고구마,사과,보리,시금치 37g 12개 묶음', `brand` = '시저' WHERE (`product_id` = '335');
UPDATE `cocobob_dev`.`product` SET `name` = '심플리 크래프티드 닭고기,고구마,사과,보리,시금치 37g', `brand` = '시저' WHERE (`product_id` = '334');
UPDATE `cocobob_dev`.`product` SET `name` = '쇠고기와 치즈 캔 100g 5개 묶음', `brand` = '시저' WHERE (`product_id` = '333');
UPDATE `cocobob_dev`.`product` SET `name` = '쇠고기와 치즈 캔 100g 12개 묶음', `brand` = '시저' WHERE (`product_id` = '332');
UPDATE `cocobob_dev`.`product` SET `name` = '쇠고기와 참치 캔 100g 12개 묶음', `brand` = '시저' WHERE (`product_id` = '331');
UPDATE `cocobob_dev`.`product` SET `name` = '쇠고기와 닭고기 캔 100g 5개 묶음', `brand` = '시저' WHERE (`product_id` = '330');
UPDATE `cocobob_dev`.`product` SET `name` = '쇠고기와 닭고기 캔 100g 12개 묶음', `brand` = '시저' WHERE (`product_id` = '329');
UPDATE `cocobob_dev`.`product` SET `name` = '쇠고기와 닭고기 캔 100g', `brand` = '시저' WHERE (`product_id` = '328');
UPDATE `cocobob_dev`.`product` SET `name` = '쇠고기와 달걀 1세이하 캔 100g 5개 묶음', `brand` = '시저' WHERE (`product_id` = '327');
UPDATE `cocobob_dev`.`product` SET `name` = '쇠고기와 달걀 1세이하 캔 100g 12개 묶음', `brand` = '시저' WHERE (`product_id` = '326');
UPDATE `cocobob_dev`.`product` SET `name` = '쇠고기와 달걀 1세이하 캔 100g', `brand` = '시저' WHERE (`product_id` = '325');
UPDATE `cocobob_dev`.`product` SET `name` = '쇠고기 캔 100g 5개 묶음', `brand` = '시저' WHERE (`product_id` = '324');
UPDATE `cocobob_dev`.`product` SET `name` = '쇠고기 캔 100g 12개 묶음', `brand` = '시저' WHERE (`product_id` = '323');
UPDATE `cocobob_dev`.`product` SET `name` = '쇠고기 캔 100g', `brand` = '시저' WHERE (`product_id` = '322');
UPDATE `cocobob_dev`.`product` SET `name` = '불고기 캔 100g 12개 묶음', `brand` = '시저' WHERE (`product_id` = '321');
UPDATE `cocobob_dev`.`product` SET `name` = '불고기 캔 100g', `brand` = '시저' WHERE (`product_id` = '320');
UPDATE `cocobob_dev`.`product` SET `name` = '닭고기 캔 100g 5개 묶음', `brand` = '시저' WHERE (`product_id` = '319');
UPDATE `cocobob_dev`.`product` SET `name` = '닭고기 캔 100g 12개 묶음', `brand` = '시저' WHERE (`product_id` = '318');
UPDATE `cocobob_dev`.`product` SET `name` = '닭고기 캔 100g', `brand` = '시저' WHERE (`product_id` = '317');
UPDATE `cocobob_dev`.`product` SET `name` = '4가지맛 (쇠고기, 양고기, 불고기, 쇠고기와 치즈) 캔 24개입', `brand` = '시저' WHERE (`product_id` = '316');
UPDATE `cocobob_dev`.`product` SET `name` = '14세이상 쇠고기 현미와 야채 캔 100g 5개 묶음', `brand` = '시저' WHERE (`product_id` = '315');
UPDATE `cocobob_dev`.`product` SET `name` = '14세이상 쇠고기 현미와 야채 캔 100g 12개 묶음', `brand` = '시저' WHERE (`product_id` = '314');
UPDATE `cocobob_dev`.`product` SET `name` = '14세이상 쇠고기 현미와 야채 캔 100g', `brand` = '시저' WHERE (`product_id` = '313');
UPDATE `cocobob_dev`.`product` SET `name` = '14세이상 닭고기 현미와 야채 캔 100g 5개 묶음', `brand` = '시저' WHERE (`product_id` = '312');
UPDATE `cocobob_dev`.`product` SET `name` = '14세이상 닭고기 현미와 야채 캔 100g 12개 묶음', `brand` = '시저' WHERE (`product_id` = '311');
UPDATE `cocobob_dev`.`product` SET `name` = '14세이상 닭고기 현미와 야채 캔 100g', `brand` = '시저' WHERE (`product_id` = '310');
UPDATE `cocobob_dev`.`product` SET `name` = '14세이상 2가지맛 (쇠고기현미와야채, 닭고기현미와야채) 캔 24개입', `brand` = '시저' WHERE (`product_id` = '309');
UPDATE `cocobob_dev`.`product` SET `name` = '11세이상 쇠고기 캔 100g 12개 묶음', `brand` = '시저' WHERE (`product_id` = '308');
UPDATE `cocobob_dev`.`product` SET `name` = '11세이상 2가지맛 (쇠고기, 닭고기) 캔 24개입', `brand` = '시저' WHERE (`product_id` = '307');
UPDATE `cocobob_dev`.`product` SET `name` = '윌 프리바이오틱스 가수분해 칠면조 1kg', `brand` = '시리우스' WHERE (`product_id` = '306');
UPDATE `cocobob_dev`.`product` SET `name` = '윌 프리바이오틱스 가수분해 연어 1kg', `brand` = '시리우스' WHERE (`product_id` = '305');
UPDATE `cocobob_dev`.`product` SET `name` = '스몰브리드 헬시웨이트 연어&흰살생선 1.81kg', `brand` = 'HALO ' WHERE (`product_id` = '772');
UPDATE `cocobob_dev`.`product` SET `name` = '스몰브리드 그레인프리 칠면조&오리 156g X 10개입', `brand` = 'HALO ' WHERE (`product_id` = '771');
UPDATE `cocobob_dev`.`product` SET `name` = '스몰브리드 그레인프리 칠면조&오리 156g', `brand` = 'HALO ' WHERE (`product_id` = '770');
UPDATE `cocobob_dev`.`product` SET `name` = '스몰브리드 그레인프리 치킨&연어 156g X 10개입', `brand` = 'HALO ' WHERE (`product_id` = '769');
UPDATE `cocobob_dev`.`product` SET `name` = '스몰브리드 그레인프리 치킨&연어 156g', `brand` = 'HALO ' WHERE (`product_id` = '768');
UPDATE `cocobob_dev`.`product` SET `name` = '동결건조 자연식 오리후레이크 180g', `brand` = '슈퍼포우' WHERE (`product_id` = '304');
UPDATE `cocobob_dev`.`product` SET `name` = '동결건조 자연식 연어 첵스 180g', `brand` = '슈퍼포우' WHERE (`product_id` = '303');
UPDATE `cocobob_dev`.`product` SET `name` = '동결건조 자연식 램프로스트 180g', `brand` = '슈퍼포우' WHERE (`product_id` = '302');
UPDATE `cocobob_dev`.`product` SET `name` = '솔루션 LID 그레인프리 오리 9.98kg', `brand` = 'go! ' WHERE (`product_id` = '762');
UPDATE `cocobob_dev`.`product` SET `name` = '솔루션 LID 그레인프리 오리 2.72kg', `brand` = 'go! ' WHERE (`product_id` = '761');
UPDATE `cocobob_dev`.`product` SET `name` = '솔루션 LID 그레인프리 연어 스몰브리드 9.98kg', `brand` = 'go! ' WHERE (`product_id` = '760');
UPDATE `cocobob_dev`.`product` SET `name` = '솔루션 LID 그레인프리 연어 스몰브리드 2.72kg', `brand` = 'go! ' WHERE (`product_id` = '759');
UPDATE `cocobob_dev`.`product` SET `name` = '솔루션 카니보 그레인프리 연어&대구 레시피 9.98kg', `brand` = 'go! ' WHERE (`product_id` = '758');
UPDATE `cocobob_dev`.`product` SET `name` = '솔루션 카니보 그레인프리 연어&대구 레시피 5.4kg', `brand` = 'go! ' WHERE (`product_id` = '757');
UPDATE `cocobob_dev`.`product` SET `name` = '참좋은 황태사료 오리 1kg', `brand` = '소프트플러스' WHERE (`product_id` = '301');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 6.8kg', `brand` = '브이플래닛' WHERE (`product_id` = '300');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 2kg', `brand` = '브이플래닛' WHERE (`product_id` = '23');
UPDATE `cocobob_dev`.`product` SET `name` = '레귤러 6.8kg', `brand` = '브이플래닛' WHERE (`product_id` = '299');
UPDATE `cocobob_dev`.`product` SET `name` = '로우 다이어트 피쉬 레시피 340.19g', `brand` = '보스독' WHERE (`product_id` = '25');
UPDATE `cocobob_dev`.`product` SET `name` = '로우 다이어트 치킨 레시피 340.19g', `brand` = '보스독' WHERE (`product_id` = '26');
UPDATE `cocobob_dev`.`product` SET `name` = '홀리스틱 그레인프리 인섹트 미니 7.5kg', `brand` = '벨포아' WHERE (`product_id` = '298');
UPDATE `cocobob_dev`.`product` SET `name` = '홀리스틱 그레인프리 인섹트 미니 2.5kg', `brand` = '벨포아' WHERE (`product_id` = '297');
UPDATE `cocobob_dev`.`product` SET `name` = '개똑 습식사료 연어 840g', `brand` = '베러펫' WHERE (`product_id` = '296');
UPDATE `cocobob_dev`.`product` SET `name` = '개똑 습식사료 연어 70g', `brand` = '베러펫' WHERE (`product_id` = '295');
UPDATE `cocobob_dev`.`product` SET `name` = '개똑 습식사료 쇠고기 70g', `brand` = '베러펫' WHERE (`product_id` = '294');
UPDATE `cocobob_dev`.`product` SET `name` = '개똑 습식사료 닭고기 840g', `brand` = '베러펫' WHERE (`product_id` = '293');
UPDATE `cocobob_dev`.`product` SET `name` = '개똑 습식사료 닭고기 70g', `brand` = '베러펫' WHERE (`product_id` = '292');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 2.1kg', `brand` = '베기도그' WHERE (`product_id` = '291');
UPDATE `cocobob_dev`.`product` SET `name` = '베지믹스 눈물개선 50g', `brand` = '벅스펫' WHERE (`product_id` = '290');
UPDATE `cocobob_dev`.`product` SET `name` = '베지믹스 관절건강 50g', `brand` = '벅스펫' WHERE (`product_id` = '289');
UPDATE `cocobob_dev`.`product` SET `name` = '베지믹스 간&심장건강 50g', `brand` = '벅스펫' WHERE (`product_id` = '288');
UPDATE `cocobob_dev`.`product` SET `name` = '벅스독 오리지널 인섹트 곤충사료 1.2kg', `brand` = '벅스펫' WHERE (`product_id` = '287');
UPDATE `cocobob_dev`.`product` SET `name` = '독 오리 미니 패티 포뮬라 453g', `brand` = '바이탈에센셜 ' WHERE (`product_id` = '286');
UPDATE `cocobob_dev`.`product` SET `name` = '독 연어 미니닙 포뮬라 397g', `brand` = '바이탈에센셜 ' WHERE (`product_id` = '285');
UPDATE `cocobob_dev`.`product` SET `name` = '독 후르츠 파테&청키 오리와 오렌지 100g', `brand` = '몬지' WHERE (`product_id` = '284');
UPDATE `cocobob_dev`.`product` SET `name` = '독 후르츠 파테&청키 연어와 배 100g', `brand` = '몬지' WHERE (`product_id` = '283');
UPDATE `cocobob_dev`.`product` SET `name` = '독 오븐베이크 그릴 신선한 포크 100g', `brand` = '몬지' WHERE (`product_id` = '282');
UPDATE `cocobob_dev`.`product` SET `name` = '독 오븐베이크 그릴 신선한 대구 100g', `brand` = '몬지' WHERE (`product_id` = '281');
UPDATE `cocobob_dev`.`product` SET `name` = '독 오븐베이크 그릴 신선한 닭고기와 칠면조 조각 100g', `brand` = '몬지' WHERE (`product_id` = '280');
UPDATE `cocobob_dev`.`product` SET `name` = '독 오븐베이크 그릴 시니어 오리 100g', `brand` = '몬지' WHERE (`product_id` = '279');
UPDATE `cocobob_dev`.`product` SET `name` = '독 비와일드 그레인프리 올브리드 어덜트 오리 2.5kg', `brand` = '몬지' WHERE (`product_id` = '278');
UPDATE `cocobob_dev`.`product` SET `name` = '독 비와일드 그레인프리 올브리드 어덜트 연어 2.5kg', `brand` = '몬지' WHERE (`product_id` = '277');
UPDATE `cocobob_dev`.`product` SET `name` = '독 비와일드 그레인프리 올브리드 어덜트 멸치 2.5kg', `brand` = '몬지' WHERE (`product_id` = '276');
UPDATE `cocobob_dev`.`product` SET `name` = '방목 치킨과 연어 중형견용 2kg', `brand` = '맥아담스' WHERE (`product_id` = '275');
UPDATE `cocobob_dev`.`product` SET `name` = '방목 치킨 퍼피 2kg', `brand` = '맥아담스' WHERE (`product_id` = '274');
UPDATE `cocobob_dev`.`product` SET `name` = '인섹트 더 제로 1kg', `brand` = '마이펫닥터' WHERE (`product_id` = '273');
UPDATE `cocobob_dev`.`product` SET `name` = '시그니처 오가닉 슬림컨트롤 2kg', `brand` = '마이펫닥터' WHERE (`product_id` = '272');
UPDATE `cocobob_dev`.`product` SET `name` = '시그니처 오가닉 스킨컨트롤 2kg', `brand` = '마이펫닥터' WHERE (`product_id` = '271');
UPDATE `cocobob_dev`.`product` SET `name` = '시그니처 오가닉 다이제스티브컨트롤 1kg', `brand` = '마이펫닥터 ' WHERE (`product_id` = '14');
UPDATE `cocobob_dev`.`product` SET `name` = '밀프리 LID 드라이 푸드 독 연어 4.5kg', `brand` = '로우즈' WHERE (`product_id` = '270');
UPDATE `cocobob_dev`.`product` SET `name` = '밀프리 LID 드라이 푸드 독 연어 1.5kg', `brand` = '로우즈' WHERE (`product_id` = '269');
UPDATE `cocobob_dev`.`product` SET `name` = '밀프리 드라이 푸드 독 치킨 4.5kg', `brand` = '로우즈' WHERE (`product_id` = '268');
UPDATE `cocobob_dev`.`product` SET `name` = '밀프리 드라이 푸드 독 치킨 1.5kg', `brand` = '로우즈' WHERE (`product_id` = '267');
UPDATE `cocobob_dev`.`product` SET `name` = '밀프리 드라이 푸드 독 연어 4.5kg', `brand` = '로우즈' WHERE (`product_id` = '266');
UPDATE `cocobob_dev`.`product` SET `name` = '밀프리 드라이 푸드 독 연어 1.5kg', `brand` = '로우즈' WHERE (`product_id` = '265');
UPDATE `cocobob_dev`.`product` SET `name` = '로우 다이어트 피쉬 레시피 340.19g', `brand` = '보스독' WHERE (`product_id` = '7');
UPDATE `cocobob_dev`.`product` SET `name` = '로우 다이어트 치킨 레시피 340.19g', `brand` = '보스독' WHERE (`product_id` = '8');
UPDATE `cocobob_dev`.`product` SET `name` = '프렌치불독 어덜트 3kg 근육형성', `brand` = '로얄캐닌' WHERE (`product_id` = '264');
UPDATE `cocobob_dev`.`product` SET `name` = '푸들 퍼피 1.5kg 피모관리', `brand` = '로얄캐닌' WHERE (`product_id` = '263');
UPDATE `cocobob_dev`.`product` SET `name` = '푸들 어덜트 파우치 85g 피모관리', `brand` = '로얄캐닌' WHERE (`product_id` = '262');
UPDATE `cocobob_dev`.`product` SET `name` = '푸들 어덜트 500g 피모관리', `brand` = '로얄캐닌' WHERE (`product_id` = '261');
UPDATE `cocobob_dev`.`product` SET `name` = '푸들 어덜트 3kg 피모관리', `brand` = '로얄캐닌' WHERE (`product_id` = '260');
UPDATE `cocobob_dev`.`product` SET `name` = '포메라니안 어덜트 파우치 85g 관절 건강', `brand` = '로얄캐닌' WHERE (`product_id` = '259');
UPDATE `cocobob_dev`.`product` SET `name` = '포메라니안 어덜트 500g 관절 건강', `brand` = '로얄캐닌' WHERE (`product_id` = '258');
UPDATE `cocobob_dev`.`product` SET `name` = '포메라니안 어덜트 3kg 관절 건강', `brand` = '로얄캐닌' WHERE (`product_id` = '257');
UPDATE `cocobob_dev`.`product` SET `name` = '포메라니안 어덜트 1.5kg 관절 건강', `brand` = '로얄캐닌' WHERE (`product_id` = '256');
UPDATE `cocobob_dev`.`product` SET `name` = '치와와 퍼피 500g 치석관리', `brand` = '로얄캐닌' WHERE (`product_id` = '255');
UPDATE `cocobob_dev`.`product` SET `name` = '치와와 어덜트 500g 치석관리', `brand` = '로얄캐닌' WHERE (`product_id` = '254');
UPDATE `cocobob_dev`.`product` SET `name` = '치와와 어덜트 3kg 치석관리', `brand` = '로얄캐닌' WHERE (`product_id` = '253');
UPDATE `cocobob_dev`.`product` SET `name` = '요크셔테리어 퍼피 1.5kg 피모관리', `brand` = '로얄캐닌' WHERE (`product_id` = '252');
UPDATE `cocobob_dev`.`product` SET `name` = '요크셔테리어 어덜트 1.5kg 피모관리', `brand` = '로얄캐닌' WHERE (`product_id` = '251');
UPDATE `cocobob_dev`.`product` SET `name` = '엑스스몰 퍼피 3kg 면역력', `brand` = '로얄캐닌' WHERE (`product_id` = '250');
UPDATE `cocobob_dev`.`product` SET `name` = '엑스스몰 퍼피 14kg 면역력', `brand` = '로얄캐닌' WHERE (`product_id` = '249');
UPDATE `cocobob_dev`.`product` SET `name` = '엑스스몰 어덜트 11kg 피모관리', `brand` = '로얄캐닌' WHERE (`product_id` = '248');
UPDATE `cocobob_dev`.`product` SET `name` = '어덜트 뷰티 캔 195g', `brand` = '로얄캐닌' WHERE (`product_id` = '247');
UPDATE `cocobob_dev`.`product` SET `name` = '어덜트 라이트 캔 195g', `brand` = '로얄캐닌' WHERE (`product_id` = '246');
UPDATE `cocobob_dev`.`product` SET `name` = '시츄 퍼피 1.5kg 단두종 치석관리', `brand` = '로얄캐닌' WHERE (`product_id` = '245');
UPDATE `cocobob_dev`.`product` SET `name` = '스테럴라이즈드 1kg 중성화견', `brand` = '로얄캐닌' WHERE (`product_id` = '244');
UPDATE `cocobob_dev`.`product` SET `name` = '스타터무스 마더&베이비독 캔 195g', `brand` = '로얄캐닌' WHERE (`product_id` = '243');
UPDATE `cocobob_dev`.`product` SET `name` = '슈나우져 어덜트 3kg 요로 건강', `brand` = '로얄캐닌' WHERE (`product_id` = '242');
UPDATE `cocobob_dev`.`product` SET `name` = '비숑프리제 어덜트 1.5kg', `brand` = '로얄캐닌' WHERE (`product_id` = '241');
UPDATE `cocobob_dev`.`product` SET `name` = '미디움 퍼피 4kg 중형견 면역증진', `brand` = '로얄캐닌' WHERE (`product_id` = '240');
UPDATE `cocobob_dev`.`product` SET `name` = '미디움 퍼피 10kg 중형견 면역증진', `brand` = '로얄캐닌' WHERE (`product_id` = '239');
UPDATE `cocobob_dev`.`product` SET `name` = '미디움 어덜트 4kg 중형견 면역증진', `brand` = '로얄캐닌' WHERE (`product_id` = '238');
UPDATE `cocobob_dev`.`product` SET `name` = '미디움 어덜트 10kg 중형견 면역증진', `brand` = '로얄캐닌' WHERE (`product_id` = '237');
UPDATE `cocobob_dev`.`product` SET `name` = '미디엄 라이트 웨이트 케어 12kg 다이어트', `brand` = '로얄캐닌' WHERE (`product_id` = '236');
UPDATE `cocobob_dev`.`product` SET `name` = '미디엄 더마컴포트 10kg 피부 보호', `brand` = '로얄캐닌' WHERE (`product_id` = '235');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 퍼피 8kg 면역 증진', `brand` = '로얄캐닌' WHERE (`product_id` = '234');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 코트케어 1kg 피모관리', `brand` = '로얄캐닌' WHERE (`product_id` = '233');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 코트 케어 파우치 85g 피모관리', `brand` = '로얄캐닌' WHERE (`product_id` = '232');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 코트 케어 3kg 피모관리', `brand` = '로얄캐닌' WHERE (`product_id` = '231');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 인도어 퍼피 8.7kg 면역력', `brand` = '로얄캐닌' WHERE (`product_id` = '230');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 인도어 퍼피 500g 면역력', `brand` = '로얄캐닌' WHERE (`product_id` = '229');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 인도어 퍼피 3kg 면역력', `brand` = '로얄캐닌' WHERE (`product_id` = '228');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 인도어 어덜트 8.7kg 소화기 건강', `brand` = '로얄캐닌' WHERE (`product_id` = '227');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 인도어 어덜트 500g 소화기 건강', `brand` = '로얄캐닌' WHERE (`product_id` = '226');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 인도어 어덜트 3kg 소화기 건강', `brand` = '로얄캐닌' WHERE (`product_id` = '225');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 인도어 시니어 1.5kg 소화 도움', `brand` = '로얄캐닌' WHERE (`product_id` = '224');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 어덜트 파우치 85g 장건강', `brand` = '로얄캐닌' WHERE (`product_id` = '223');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 어덜트 8kg 치석 예방', `brand` = '로얄캐닌' WHERE (`product_id` = '222');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 스테럴라이즈드 파우치 85g 중성화견', `brand` = '로얄캐닌' WHERE (`product_id` = '221');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 스테럴라이즈드 3kg 중성화견', `brand` = '로얄캐닌' WHERE (`product_id` = '220');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 스타터 마더&베이비 8.5kg 면역증진', `brand` = '로얄캐닌' WHERE (`product_id` = '219');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 스타터 3kg 면역증진', `brand` = '로얄캐닌' WHERE (`product_id` = '218');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 릴렉스 케어 파우치 85g 심신안정', `brand` = '로얄캐닌' WHERE (`product_id` = '217');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 릴렉스 케어 3kg 심신안정', `brand` = '로얄캐닌' WHERE (`product_id` = '216');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 라이트웨이트 케어 3kg 체중조절', `brand` = '로얄캐닌' WHERE (`product_id` = '215');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 라이트웨이트 케어 1kg 체중조절', `brand` = '로얄캐닌' WHERE (`product_id` = '214');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 더마컴포트 파우치 85g 피부 보호', `brand` = '로얄캐닌' WHERE (`product_id` = '213');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 더마컴포트 케어 1kg 피부 보호', `brand` = '로얄캐닌' WHERE (`product_id` = '212');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 더마컴포트 3kg 피부 보호', `brand` = '로얄캐닌' WHERE (`product_id` = '211');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 다이제스티브 파우치 85g 소화 도움', `brand` = '로얄캐닌' WHERE (`product_id` = '210');
UPDATE `cocobob_dev`.`product` SET `name` = '미니 다이제스티브 3kg 소화 도움', `brand` = '로얄캐닌' WHERE (`product_id` = '209');
UPDATE `cocobob_dev`.`product` SET `name` = '머츄어8 캔 195g', `brand` = '로얄캐닌' WHERE (`product_id` = '208');
UPDATE `cocobob_dev`.`product` SET `name` = '맥시 퍼피 4kg 대형견 면역증진', `brand` = '로얄캐닌' WHERE (`product_id` = '207');
UPDATE `cocobob_dev`.`product` SET `name` = '맥시 퍼피 10kg 대형견 면역증진', `brand` = '로얄캐닌' WHERE (`product_id` = '206');
UPDATE `cocobob_dev`.`product` SET `name` = '맥시 어덜트 4kg 대형견 관절건강', `brand` = '로얄캐닌' WHERE (`product_id` = '205');
UPDATE `cocobob_dev`.`product` SET `name` = '맥시 어덜트 10kg 대형견 관절건강', `brand` = '로얄캐닌' WHERE (`product_id` = '204');
UPDATE `cocobob_dev`.`product` SET `name` = '말티즈 어덜트 500g 피모관리', `brand` = '로얄캐닌' WHERE (`product_id` = '203');
UPDATE `cocobob_dev`.`product` SET `name` = '말티즈 어덜트 4.5kg 기획팩', `brand` = '로얄캐닌' WHERE (`product_id` = '202');
UPDATE `cocobob_dev`.`product` SET `name` = '말티즈 어덜트 3kg 피모관리', `brand` = '로얄캐닌' WHERE (`product_id` = '201');
UPDATE `cocobob_dev`.`product` SET `name` = '말티즈 어덜트 1.5kg 피모관리', `brand` = '로얄캐닌' WHERE (`product_id` = '200');
UPDATE `cocobob_dev`.`product` SET `name` = '릴렉스 케어 1kg 심신안정', `brand` = '로얄캐닌' WHERE (`product_id` = '28');
UPDATE `cocobob_dev`.`product` SET `name` = '릴렉스 케어 1kg 심신안정', `brand` = '로얄캐닌' WHERE (`product_id` = '199');
UPDATE `cocobob_dev`.`product` SET `name` = '라브라도리트리버 퍼피 3kg 관절 건강', `brand` = '로얄캐닌' WHERE (`product_id` = '198');
UPDATE `cocobob_dev`.`product` SET `name` = '라브라도리트리버 어덜트 3kg 관절 건강', `brand` = '로얄캐닌' WHERE (`product_id` = '197');
UPDATE `cocobob_dev`.`product` SET `name` = '라브라도리트리버 어덜트 12kg 관절건강', `brand` = '로얄캐닌' WHERE (`product_id` = '196');
UPDATE `cocobob_dev`.`product` SET `name` = '독 푸들 어덜트 7.5kg', `brand` = '로얄캐닌' WHERE (`product_id` = '195');
UPDATE `cocobob_dev`.`product` SET `name` = '닥스훈트 퍼피 1.5kg 관절 건강', `brand` = '로얄캐닌' WHERE (`product_id` = '194');
UPDATE `cocobob_dev`.`product` SET `name` = '닥스훈트 어덜트 1.5kg 관절 건강', `brand` = '로얄캐닌' WHERE (`product_id` = '193');
UPDATE `cocobob_dev`.`product` SET `name` = '다이제스티브 케어 1kg 소화 도움', `brand` = '로얄캐닌' WHERE (`product_id` = '192');
UPDATE `cocobob_dev`.`product` SET `name` = '양고기 캔 380g', `brand` = '럭셔리발란스' WHERE (`product_id` = '191');
UPDATE `cocobob_dev`.`product` SET `name` = '소고기 캔 380g', `brand` = '럭셔리발란스' WHERE (`product_id` = '190');
UPDATE `cocobob_dev`.`product` SET `name` = '닭고기 캔 380g', `brand` = '럭셔리발란스' WHERE (`product_id` = '189');
UPDATE `cocobob_dev`.`product` SET `name` = '램 홀리스틱 큰알갱이 7.2kg', `brand` = 'ANF' WHERE (`product_id` = '754');
UPDATE `cocobob_dev`.`product` SET `name` = '램 홀리스틱 큰알갱이 15kg', `brand` = 'ANF' WHERE (`product_id` = '22');
UPDATE `cocobob_dev`.`product` SET `name` = '램 홀리스틱 큰알갱이 15kg', `brand` = 'ANF' WHERE (`product_id` = '753');
UPDATE `cocobob_dev`.`product` SET `name` = '램 홀리스틱 중간알갱이 7.2kg', `brand` = 'ANF' WHERE (`product_id` = '752');
UPDATE `cocobob_dev`.`product` SET `name` = '램 홀리스틱 중간알갱이 15kg', `brand` = 'ANF' WHERE (`product_id` = '751');
UPDATE `cocobob_dev`.`product` SET `name` = '램 홀리스틱 작은알갱이 7.2kg', `brand` = 'ANF' WHERE (`product_id` = '750');
UPDATE `cocobob_dev`.`product` SET `name` = '램 홀리스틱 시니어 7.2kg', `brand` = 'ANF' WHERE (`product_id` = '749');
UPDATE `cocobob_dev`.`product` SET `name` = '리얼 인섹트 관절 1.2kg', `brand` = '라포그' WHERE (`product_id` = '188');
UPDATE `cocobob_dev`.`product` SET `name` = '리얼 인섹트 1.2kg', `brand` = '라포그' WHERE (`product_id` = '187');
UPDATE `cocobob_dev`.`product` SET `name` = '피쉬 앤 데일리 500g', `brand` = '딩고' WHERE (`product_id` = '186');
UPDATE `cocobob_dev`.`product` SET `name` = '피쉬 앤 데일리 3kg', `brand` = '딩고' WHERE (`product_id` = '185');
UPDATE `cocobob_dev`.`product` SET `name` = '피쉬 앤 데일리 12kg', `brand` = '딩고' WHERE (`product_id` = '184');
UPDATE `cocobob_dev`.`product` SET `name` = '퍼피 앤 주니어 500g', `brand` = '딩고' WHERE (`product_id` = '183');
UPDATE `cocobob_dev`.`product` SET `name` = '퍼피 앤 주니어 3kg', `brand` = '딩고' WHERE (`product_id` = '182');
UPDATE `cocobob_dev`.`product` SET `name` = '퍼피 앤 주니어 12kg', `brand` = '딩고' WHERE (`product_id` = '181');
UPDATE `cocobob_dev`.`product` SET `name` = '토이 앤 데일리 1.5kg', `brand` = '딩고' WHERE (`product_id` = '180');
UPDATE `cocobob_dev`.`product` SET `name` = '치킨 앤 데일리 500g', `brand` = '딩고' WHERE (`product_id` = '179');
UPDATE `cocobob_dev`.`product` SET `name` = '치킨 앤 데일리 3kg', `brand` = '딩고' WHERE (`product_id` = '178');
UPDATE `cocobob_dev`.`product` SET `name` = '치킨 앤 데일리 12kg', `brand` = '딩고' WHERE (`product_id` = '177');
UPDATE `cocobob_dev`.`product` SET `name` = '에너지 앤 핏 3kg', `brand` = '딩고' WHERE (`product_id` = '176');
UPDATE `cocobob_dev`.`product` SET `name` = '머튜얼 앤 데일리 3kg', `brand` = '딩고' WHERE (`product_id` = '175');
UPDATE `cocobob_dev`.`product` SET `name` = '화식 50g 8개 + 치킨텐더 100g 세트', `brand` = '듀먼' WHERE (`product_id` = '174');
UPDATE `cocobob_dev`.`product` SET `name` = '화식 100g 8개 + 치킨텐더 100g 세트', `brand` = '듀먼' WHERE (`product_id` = '173');
UPDATE `cocobob_dev`.`product` SET `name` = '첫 화식세트 50g 8가지맛 콤보, 8개', `brand` = '듀먼' WHERE (`product_id` = '172');
UPDATE `cocobob_dev`.`product` SET `name` = '첫 화식세트 100g 8가지맛 콤보, 8개', `brand` = '듀먼' WHERE (`product_id` = '171');
UPDATE `cocobob_dev`.`product` SET `name` = '자연화식 100g 8가지맛 콤보, 16개', `brand` = '듀먼' WHERE (`product_id` = '170');
UPDATE `cocobob_dev`.`product` SET `name` = '독 홀리스틱 칠면조&귀리 7.2kg', `brand` = 'ANF' WHERE (`product_id` = '748');
UPDATE `cocobob_dev`.`product` SET `name` = '독 홀리스틱 칠면조&귀리 2.4kg', `brand` = 'ANF' WHERE (`product_id` = '747');
UPDATE `cocobob_dev`.`product` SET `name` = '독 홀리스틱 치킨&귀리 2.4kg', `brand` = 'ANF' WHERE (`product_id` = '746');
UPDATE `cocobob_dev`.`product` SET `name` = '독 홀리스틱 연어&귀리 7.2kg', `brand` = 'ANF' WHERE (`product_id` = '745');
UPDATE `cocobob_dev`.`product` SET `name` = '독 홀리스틱 연어&귀리 2.4kg', `brand` = 'ANF' WHERE (`product_id` = '744');
UPDATE `cocobob_dev`.`product` SET `name` = '어덜트 4.5kg', `brand` = '도비' WHERE (`product_id` = '169');
UPDATE `cocobob_dev`.`product` SET `name` = '크리미 치킨야채 스프 시니어 80g', `brand` = '도기맨' WHERE (`product_id` = '168');
UPDATE `cocobob_dev`.`product` SET `name` = '크리미 치킨야채 스프 80g', `brand` = '도기맨' WHERE (`product_id` = '167');
UPDATE `cocobob_dev`.`product` SET `name` = '도그 비티 콤보 5개입', `brand` = 'iti ' WHERE (`product_id` = '782');
UPDATE `cocobob_dev`.`product` SET `name` = '도그 비티 양고기&카와이 200g', `brand` = 'iti ' WHERE (`product_id` = '781');
UPDATE `cocobob_dev`.`product` SET `name` = '도그 비티 양고기&사슴고기 200g', `brand` = 'iti ' WHERE (`product_id` = '780');
UPDATE `cocobob_dev`.`product` SET `name` = '도그 비티 소고기&장어 200g', `brand` = 'iti ' WHERE (`product_id` = '779');
UPDATE `cocobob_dev`.`product` SET `name` = '도그 비티 소고기 200g', `brand` = 'iti ' WHERE (`product_id` = '778');
UPDATE `cocobob_dev`.`product` SET `name` = '도그 비티 닭고기 200g', `brand` = 'iti ' WHERE (`product_id` = '777');
UPDATE `cocobob_dev`.`product` SET `name` = '제스트 올스테이지 5kg', `brand` = '데이스포' WHERE (`product_id` = '166');
UPDATE `cocobob_dev`.`product` SET `name` = '제스트 올스테이지 2.6kg', `brand` = '데이스포' WHERE (`product_id` = '165');
UPDATE `cocobob_dev`.`product` SET `name` = '더마독 장건강 소화 2kg', `brand` = '데이스포' WHERE (`product_id` = '164');
UPDATE `cocobob_dev`.`product` SET `name` = '더마독 관절 체중조절 2kg', `brand` = '데이스포' WHERE (`product_id` = '163');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 밀 닭고기 200g 3개', `brand` = '하림펫푸드' WHERE (`product_id` = '2');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 밀 그레인프리 닭고기 60g 6개', `brand` = '하림펫푸드 ' WHERE (`product_id` = '1');
UPDATE `cocobob_dev`.`product` SET `name` = '더리얼 그레인프리 크런치 돼지고기 어덜트 1.6kg', `brand` = '하림펫푸드 ' WHERE (`product_id` = '162');
UPDATE `cocobob_dev`.`product` SET `name` = '닥터소프트 IGY 치석치주염예방 1.2kg', `brand` = '더독' WHERE (`product_id` = '161');
UPDATE `cocobob_dev`.`product` SET `name` = '닥터소프트 퍼피 1.2kg', `brand` = '더독' WHERE (`product_id` = '160');
UPDATE `cocobob_dev`.`product` SET `name` = '닥터소프트 치킨&장건강 노령견용 1.2kg', `brand` = '더독' WHERE (`product_id` = '159');
UPDATE `cocobob_dev`.`product` SET `name` = '닥터소프트 치킨 시니어 3kg', `brand` = '더독' WHERE (`product_id` = '158');
UPDATE `cocobob_dev`.`product` SET `name` = '닥터소프트 치킨 시니어 1.2kg', `brand` = '더독' WHERE (`product_id` = '157');
UPDATE `cocobob_dev`.`product` SET `name` = '닥터소프트 오리 그레인프리 노령견용 1.2kg', `brand` = '더독' WHERE (`product_id` = '156');
UPDATE `cocobob_dev`.`product` SET `name` = '닥터소프트 양고기와 감자 3kg', `brand` = '더독' WHERE (`product_id` = '155');
UPDATE `cocobob_dev`.`product` SET `name` = '닥터소프트 양고기 1.2kg', `brand` = '더독' WHERE (`product_id` = '154');
UPDATE `cocobob_dev`.`product` SET `name` = '닥터소프트 야채&식이섬유 1.2kg', `brand` = '더독' WHERE (`product_id` = '153');
UPDATE `cocobob_dev`.`product` SET `name` = '닥터소프트 명작 하이포알러지 연어 전견용 1.2kg', `brand` = '더독' WHERE (`product_id` = '152');
UPDATE `cocobob_dev`.`product` SET `name` = '닥터소프트 명작 하이포알러지 연어 노령견용 1.2kg', `brand` = '더독' WHERE (`product_id` = '151');
UPDATE `cocobob_dev`.`product` SET `name` = '닥터소프트 명작 오리&크릴새우 1.2kg', `brand` = '더독' WHERE (`product_id` = '150');
UPDATE `cocobob_dev`.`product` SET `name` = '닥터소프트 명작 연어&크릴새우 1.2kg', `brand` = '더독' WHERE (`product_id` = '149');
UPDATE `cocobob_dev`.`product` SET `name` = '모이스트루 퍼피 치킨&오메가3 파우치 80g', `brand` = '뉴트리플랜' WHERE (`product_id` = '148');
UPDATE `cocobob_dev`.`product` SET `name` = '모이스트루 어덜트 치킨&L-테아닌 파우치 80g', `brand` = '뉴트리플랜' WHERE (`product_id` = '147');
UPDATE `cocobob_dev`.`product` SET `name` = '모이스트루 시니어 치킨&홍삼 파우치 80g', `brand` = '뉴트리플랜' WHERE (`product_id` = '146');
UPDATE `cocobob_dev`.`product` SET `name` = '퍼포먼스 치킨&라이스 18.2kg', `brand` = '뉴트리소스' WHERE (`product_id` = '145');
UPDATE `cocobob_dev`.`product` SET `name` = '트라웃&라이스 6.8kg', `brand` = '뉴트리소스' WHERE (`product_id` = '144');
UPDATE `cocobob_dev`.`product` SET `name` = '트라웃&라이스 13.6kg', `brand` = '뉴트리소스' WHERE (`product_id` = '143');
UPDATE `cocobob_dev`.`product` SET `name` = '어덜트 치킨&라이스 2.26kg', `brand` = '뉴트리소스' WHERE (`product_id` = '141');
UPDATE `cocobob_dev`.`product` SET `name` = '어덜트 치킨&라이스 2.26kg', `brand` = '뉴트리소스' WHERE (`product_id` = '142');
UPDATE `cocobob_dev`.`product` SET `name` = '어덜트 치킨&라이스 13.6kg', `brand` = '뉴트리소스' WHERE (`product_id` = '140');
UPDATE `cocobob_dev`.`product` SET `name` = '스몰&미디엄 브리드퍼피 치킨&라이스 6.8kg', `brand` = '뉴트리소스' WHERE (`product_id` = '139');
UPDATE `cocobob_dev`.`product` SET `name` = '라지브리드 퍼피 치킨&라이스 13.6kg', `brand` = '뉴트리소스' WHERE (`product_id` = '138');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 치킨&피 6.8kg', `brand` = '뉴트리소스' WHERE (`product_id` = '137');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 시니어 13.6kg', `brand` = '뉴트리소스' WHERE (`product_id` = '136');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 라지브리드 퍼피 13.6kg', `brand` = '뉴트리소스' WHERE (`product_id` = '135');
UPDATE `cocobob_dev`.`product` SET `name` = '퍼피 2.1kg', `brand` = '뉴트리나' WHERE (`product_id` = '134');
UPDATE `cocobob_dev`.`product` SET `name` = '울트라 진도 대형견용 10kg', `brand` = '뉴트리나' WHERE (`product_id` = '133');
UPDATE `cocobob_dev`.`product` SET `name` = '울트라 액티브 15kg', `brand` = '뉴트리나' WHERE (`product_id` = '132');
UPDATE `cocobob_dev`.`product` SET `name` = '어덜트 치킨 2.1kg', `brand` = '뉴트리나' WHERE (`product_id` = '131');
UPDATE `cocobob_dev`.`product` SET `name` = '어덜트 연어 2.1kg', `brand` = '뉴트리나' WHERE (`product_id` = '130');
UPDATE `cocobob_dev`.`product` SET `name` = '어덜트 다이어트 2.1kg', `brand` = '뉴트리나' WHERE (`product_id` = '129');
UPDATE `cocobob_dev`.`product` SET `name` = '건강백서 푸들 6kg', `brand` = '뉴트리나' WHERE (`product_id` = '128');
UPDATE `cocobob_dev`.`product` SET `name` = '건강백서 푸들 10.2kg', `brand` = '뉴트리나' WHERE (`product_id` = '127');
UPDATE `cocobob_dev`.`product` SET `name` = '건강백서 포메라니언 6kg', `brand` = '뉴트리나' WHERE (`product_id` = '126');
UPDATE `cocobob_dev`.`product` SET `name` = '건강백서 포메라니언 2kg', `brand` = '뉴트리나' WHERE (`product_id` = '125');
UPDATE `cocobob_dev`.`product` SET `name` = '건강백서 코커스파니엘 2kg', `brand` = '뉴트리나' WHERE (`product_id` = '124');
UPDATE `cocobob_dev`.`product` SET `name` = '건강백서 슈나우져 2kg', `brand` = '뉴트리나' WHERE (`product_id` = '123');
UPDATE `cocobob_dev`.`product` SET `name` = '건강백서 말티즈 6kg', `brand` = '뉴트리나' WHERE (`product_id` = '122');
UPDATE `cocobob_dev`.`product` SET `name` = '건강백서 말티즈 2kg', `brand` = '뉴트리나' WHERE (`product_id` = '121');
UPDATE `cocobob_dev`.`product` SET `name` = '건강백서 말티즈 10.2kg', `brand` = '뉴트리나' WHERE (`product_id` = '120');
UPDATE `cocobob_dev`.`product` SET `name` = '건강백서 건강한 피부 6kg', `brand` = '뉴트리나' WHERE (`product_id` = '119');
UPDATE `cocobob_dev`.`product` SET `name` = '건강백서 건강한 체중 6kg', `brand` = '뉴트리나' WHERE (`product_id` = '118');
UPDATE `cocobob_dev`.`product` SET `name` = '건강백서 건강한 체중 2kg', `brand` = '뉴트리나' WHERE (`product_id` = '117');
UPDATE `cocobob_dev`.`product` SET `name` = '건강백서 건강한 장 10.2kg', `brand` = '뉴트리나' WHERE (`product_id` = '116');
UPDATE `cocobob_dev`.`product` SET `name` = '건강백서 건강한 관절 6kg', `brand` = '뉴트리나' WHERE (`product_id` = '115');
UPDATE `cocobob_dev`.`product` SET `name` = '건강백서 건강한 관절 2kg', `brand` = '뉴트리나' WHERE (`product_id` = '114');
UPDATE `cocobob_dev`.`product` SET `name` = '건강백서 건강한 관절 10.2kg', `brand` = '뉴트리나' WHERE (`product_id` = '113');
UPDATE `cocobob_dev`.`product` SET `name` = '건강백서 건강한 6세이상 6kg', `brand` = '뉴트리나' WHERE (`product_id` = '112');
UPDATE `cocobob_dev`.`product` SET `name` = '건강백서 건강한 6세이상 2kg', `brand` = '뉴트리나' WHERE (`product_id` = '111');
UPDATE `cocobob_dev`.`product` SET `name` = '건강백서 건강한 1세 2kg', `brand` = '뉴트리나' WHERE (`product_id` = '110');
UPDATE `cocobob_dev`.`product` SET `name` = '1세이하 닭고기와 현미 5.9kg', `brand` = '뉴트로' WHERE (`product_id` = '16');
UPDATE `cocobob_dev`.`product` SET `name` = '1세이상 소형견용 닭고기와 현미 5.9kg', `brand` = '뉴트로' WHERE (`product_id` = '18');
UPDATE `cocobob_dev`.`product` SET `name` = '1세이상 닭고기와 현미 5.9kg', `brand` = '뉴트로' WHERE (`product_id` = '27');
UPDATE `cocobob_dev`.`product` SET `name` = '1세이상 닭고기와 현미 5.9kg', `brand` = '뉴트로' WHERE (`product_id` = '109');
UPDATE `cocobob_dev`.`product` SET `name` = '홀리스틱 3 오리고기&고구마 5kg', `brand` = '뉴웨이브' WHERE (`product_id` = '108');
UPDATE `cocobob_dev`.`product` SET `name` = '홀리스틱 2 양고기 5kg', `brand` = '뉴웨이브' WHERE (`product_id` = '107');
UPDATE `cocobob_dev`.`product` SET `name` = '홀리스틱 베네 M32 멀티프로테인 6kg', `brand` = '네츄럴코어' WHERE (`product_id` = '106');
UPDATE `cocobob_dev`.`product` SET `name` = '치킨 주식 캔 80g', `brand` = '네츄럴코어' WHERE (`product_id` = '105');
UPDATE `cocobob_dev`.`product` SET `name` = '유기농 에코 9a 시니어 오리&고구마 6kg', `brand` = '네츄럴코어' WHERE (`product_id` = '104');
UPDATE `cocobob_dev`.`product` SET `name` = '유기농 에코 9a 시니어 오리&고구마 2.4kg', `brand` = '네츄럴코어' WHERE (`product_id` = '103');
UPDATE `cocobob_dev`.`product` SET `name` = '유기농 에코 6 센시티브 솔루션 연어 중간알갱이 2kg', `brand` = '네츄럴코어' WHERE (`product_id` = '102');
UPDATE `cocobob_dev`.`product` SET `name` = '유기농 에코 6 센시티브 솔루션 연어 작은알갱이 2.4kg', `brand` = '네츄럴코어' WHERE (`product_id` = '101');
UPDATE `cocobob_dev`.`product` SET `name` = '유기농 에코 5 퍼피 작은알갱이 7kg', `brand` = '네츄럴코어' WHERE (`product_id` = '100');
UPDATE `cocobob_dev`.`product` SET `name` = '유기농 에코 4 오리고기 슬림다운 6kg', `brand` = '네츄럴코어' WHERE (`product_id` = '99');
UPDATE `cocobob_dev`.`product` SET `name` = '유기농 에코 2 오리고기 작은알갱이 7kg', `brand` = '네츄럴코어' WHERE (`product_id` = '98');
UPDATE `cocobob_dev`.`product` SET `name` = '유기농 에코 2 오리고기 작은알갱이 2kg', `brand` = '네츄럴코어' WHERE (`product_id` = '97');
UPDATE `cocobob_dev`.`product` SET `name` = '에코10 베지테리언 6kg', `brand` = '네츄럴코어' WHERE (`product_id` = '96');
UPDATE `cocobob_dev`.`product` SET `name` = '에코 9b 시니어 연어&고구마 6kg', `brand` = '네츄럴코어' WHERE (`product_id` = '95');
UPDATE `cocobob_dev`.`product` SET `name` = '에코 70B 연어 7kg', `brand` = '네츄럴코어' WHERE (`product_id` = '94');
UPDATE `cocobob_dev`.`product` SET `name` = '에코 70B 연어 2kg', `brand` = '네츄럴코어' WHERE (`product_id` = '93');
UPDATE `cocobob_dev`.`product` SET `name` = '에코 70A 양고기 7kg', `brand` = '네츄럴코어' WHERE (`product_id` = '92');
UPDATE `cocobob_dev`.`product` SET `name` = '에코 70A 양고기 2kg', `brand` = '네츄럴코어' WHERE (`product_id` = '91');
UPDATE `cocobob_dev`.`product` SET `name` = '에코 2 오리고기 큰알갱이 10kg', `brand` = '네츄럴코어' WHERE (`product_id` = '90');
UPDATE `cocobob_dev`.`product` SET `name` = '에코 2 오리고기 작은알갱이 10kg', `brand` = '네츄럴코어' WHERE (`product_id` = '89');
UPDATE `cocobob_dev`.`product` SET `name` = '에코 1 양고기 작은알갱이 10kg', `brand` = '네츄럴코어' WHERE (`product_id` = '88');
UPDATE `cocobob_dev`.`product` SET `name` = '소프트델리 사슴&연어 800g', `brand` = '네츄럴코어' WHERE (`product_id` = '87');
UPDATE `cocobob_dev`.`product` SET `name` = '센시티브케어 베지 3kg', `brand` = '네츄럴코어' WHERE (`product_id` = '86');
UPDATE `cocobob_dev`.`product` SET `name` = '센시티브케어 베지 1.2kg', `brand` = '네츄럴코어' WHERE (`product_id` = '85');
UPDATE `cocobob_dev`.`product` SET `name` = '센시티브케어 밀웜 3kg', `brand` = '네츄럴코어' WHERE (`product_id` = '84');
UPDATE `cocobob_dev`.`product` SET `name` = '센시티브케어 밀웜 1.2kg', `brand` = '네츄럴코어' WHERE (`product_id` = '83');
UPDATE `cocobob_dev`.`product` SET `name` = '70%유기농 에코 1 양고기 중간알갱이 6kg', `brand` = '네츄럴코어' WHERE (`product_id` = '82');
UPDATE `cocobob_dev`.`product` SET `name` = '70%유기농 에코 1 양고기 작은알갱이 7kg', `brand` = '네츄럴코어' WHERE (`product_id` = '81');
UPDATE `cocobob_dev`.`product` SET `name` = '70%유기농 에코 1 양고기 작은알갱이 2kg', `brand` = '네츄럴코어' WHERE (`product_id` = '80');
UPDATE `cocobob_dev`.`product` SET `name` = '인스팅트 RBK 헬시웨이트 9kg', `brand` = '네이처스 버라이어티' WHERE (`product_id` = '79');
UPDATE `cocobob_dev`.`product` SET `name` = '인스팅트 RBK 헬시웨이트 1.8kg', `brand` = '네이처스 버라이어티' WHERE (`product_id` = '78');
UPDATE `cocobob_dev`.`product` SET `name` = '인스팅트 RBK 오리&칠면조 9kg', `brand` = '네이처스 버라이어티' WHERE (`product_id` = '77');
UPDATE `cocobob_dev`.`product` SET `name` = '인스팅트 RBK 오리&칠면조 1.8kg', `brand` = '네이처스 버라이어티' WHERE (`product_id` = '76');
UPDATE `cocobob_dev`.`product` SET `name` = '인스팅트 RBK  치킨 9.5kg', `brand` = '네이처스 버라이어티' WHERE (`product_id` = '75');
UPDATE `cocobob_dev`.`product` SET `name` = '인스팅트 RBK  장건강 1.8kg', `brand` = '네이처스 버라이어티' WHERE (`product_id` = '74');
UPDATE `cocobob_dev`.`product` SET `name` = '인스팅트 LID 칠면조 캔 374g', `brand` = '네이처스 버라이어티' WHERE (`product_id` = '73');
UPDATE `cocobob_dev`.`product` SET `name` = '인스팅트 LID 칠면조 10kg', `brand` = '네이처스 버라이어티' WHERE (`product_id` = '72');
UPDATE `cocobob_dev`.`product` SET `name` = '인스팅트 LID 칠면조 1.8kg', `brand` = '네이처스 버라이어티' WHERE (`product_id` = '71');
UPDATE `cocobob_dev`.`product` SET `name` = '인스팅트 LID 연어 9kg', `brand` = '네이처스 버라이어티' WHERE (`product_id` = '70');
UPDATE `cocobob_dev`.`product` SET `name` = '인스팅트 LID 연어 1.8kg', `brand` = '네이처스 버라이어티' WHERE (`product_id` = '69');
UPDATE `cocobob_dev`.`product` SET `name` = '인스팅트 BE 내추럴 독 치킨&현미 2kg', `brand` = '네이처스 버라이어티' WHERE (`product_id` = '68');
UPDATE `cocobob_dev`.`product` SET `name` = '인스팅트 BE 내추럴 독 연어&현미 2kg', `brand` = '네이처스 버라이어티' WHERE (`product_id` = '67');
UPDATE `cocobob_dev`.`product` SET `name` = '인스팅트 BE 내추럴 독 연어&현미 10.8kg', `brand` = '네이처스 버라이어티' WHERE (`product_id` = '66');
UPDATE `cocobob_dev`.`product` SET `name` = '인스팅트 헬시크레이빙 치킨 파우치 85g', `brand` = '네이처스 버라이어티' WHERE (`product_id` = '65');
UPDATE `cocobob_dev`.`product` SET `name` = '인스팅트 헬시크레이빙 연어 파우치 85g', `brand` = '네이처스 버라이어티' WHERE (`product_id` = '64');
UPDATE `cocobob_dev`.`product` SET `name` = '인스팅트 토끼 9kg', `brand` = '네이처스 버라이어티' WHERE (`product_id` = '63');
UPDATE `cocobob_dev`.`product` SET `name` = '인스팅트 토끼 1.8kg', `brand` = '네이처스 버라이어티' WHERE (`product_id` = '62');
UPDATE `cocobob_dev`.`product` SET `name` = '인스팅트 치킨 10.2kg', `brand` = '네이처스 버라이어티' WHERE (`product_id` = '61');
UPDATE `cocobob_dev`.`product` SET `name` = '인스팅트 치킨 1.8kg', `brand` = '네이처스 버라이어티' WHERE (`product_id` = '60');
UPDATE `cocobob_dev`.`product` SET `name` = '인스팅트 오리고기 9kg', `brand` = '네이처스 버라이어티' WHERE (`product_id` = '59');
UPDATE `cocobob_dev`.`product` SET `name` = '연어&현미, 야채 400g', `brand` = '내추로' WHERE (`product_id` = '58');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 퍼피 닭고기&감자, 야채 150g', `brand` = '내추로' WHERE (`product_id` = '57');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 캔 400g x 6개입 버라이어티팩', `brand` = '내추로' WHERE (`product_id` = '56');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 캔 390g x 6개입 버라이어티팩', `brand` = '내추로' WHERE (`product_id` = '55');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 저지방 닭고기&현미, 야채 400g', `brand` = '내추로' WHERE (`product_id` = '54');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 오리고기&현미, 야채 400g', `brand` = '내추로' WHERE (`product_id` = '53');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 연어&감자, 야채 캔 400g', `brand` = '내추로' WHERE (`product_id` = '52');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 시니어 칠면조&현미, 야채 400g', `brand` = '내추로' WHERE (`product_id` = '51');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 닭고기&감자, 야채 캔 400g', `brand` = '내추로' WHERE (`product_id` = '50');
UPDATE `cocobob_dev`.`product` SET `name` = 'G-FREE 오리와 눈 건강 1.2kg', `brand` = '내추럴팩토리' WHERE (`product_id` = '49');
UPDATE `cocobob_dev`.`product` SET `name` = 'G-FREE 연어와 피부 1.2kg', `brand` = '내추럴팩토리' WHERE (`product_id` = '48');
UPDATE `cocobob_dev`.`product` SET `name` = 'G-FREE 양고기와 관절 1.2kg', `brand` = '내추럴팩토리' WHERE (`product_id` = '47');
UPDATE `cocobob_dev`.`product` SET `name` = '수제 스튜 닭고기&연어 캔 78g', `brand` = '내추럴발란스 ' WHERE (`product_id` = '46');
UPDATE `cocobob_dev`.`product` SET `name` = '피부강화 3kg', `brand` = '나인케어' WHERE (`product_id` = '45');
UPDATE `cocobob_dev`.`product` SET `name` = '시니어 3kg', `brand` = '나인케어' WHERE (`product_id` = '44');
UPDATE `cocobob_dev`.`product` SET `name` = '사료 1.4kg', `brand` = '꼬시다' WHERE (`product_id` = '43');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 피쉬 어덜트 올브리드 9.98kg', `brand` = 'now' WHERE (`product_id` = '797');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 피쉬 어덜트 스몰브리드 9.98kg', `brand` = 'now' WHERE (`product_id` = '796');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 피쉬 어덜트 스몰브리드 5.44kg', `brand` = 'now' WHERE (`product_id` = '795');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 퍼피 스몰브리드 9.98kg', `brand` = 'now' WHERE (`product_id` = '794');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 퍼피 스몰브리드 5.44kg', `brand` = 'now' WHERE (`product_id` = '793');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 퍼피 스몰브리드 2.72kg', `brand` = 'now' WHERE (`product_id` = '792');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 어덜트 올브리드 9.98kg', `brand` = 'now' WHERE (`product_id` = '790');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 어덜트 올브리드 9.98kg', `brand` = 'now' WHERE (`product_id` = '791');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 어덜트 올브리드 5.44kg', `brand` = 'now' WHERE (`product_id` = '789');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 어덜트 스몰브리드 9.98kg', `brand` = 'now' WHERE (`product_id` = '788');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 어덜트 스몰브리드 5.44kg', `brand` = 'now' WHERE (`product_id` = '787');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 어덜트 스몰브리드 2.72kg', `brand` = 'now' WHERE (`product_id` = '786');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 시니어 스몰브리드 9.98kg', `brand` = 'now' WHERE (`product_id` = '785');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 시니어 스몰브리드 5.44kg', `brand` = 'now' WHERE (`product_id` = '784');
UPDATE `cocobob_dev`.`product` SET `name` = '그레인프리 시니어 스몰브리드 2.72kg', `brand` = 'now' WHERE (`product_id` = '783');
UPDATE `cocobob_dev`.`product` SET `name` = '스페셜서퍼 양고기 285g', `brand` = '굿프랜드 ' WHERE (`product_id` = '9');
UPDATE `cocobob_dev`.`product` SET `name` = '스페셜서퍼 닭고기 285g', `brand` = '굿프랜드' WHERE (`product_id` = '42');
UPDATE `cocobob_dev`.`product` SET `name` = '프리 에이커 치킨 레시피 어덜트 7.26kg', `brand` = '게더' WHERE (`product_id` = '41');
UPDATE `cocobob_dev`.`product` SET `name` = '프리 에이커 치킨 레시피 어덜트 2.72kg', `brand` = '게더' WHERE (`product_id` = '40');
UPDATE `cocobob_dev`.`product` SET `name` = '프리 에이커 치킨 레시피 어덜트 1kg', `brand` = '게더' WHERE (`product_id` = '39');
UPDATE `cocobob_dev`.`product` SET `name` = '엔드레스 벨리 비건 레시피 어덜트 7.26kg', `brand` = '게더' WHERE (`product_id` = '38');
UPDATE `cocobob_dev`.`product` SET `name` = '엔드레스 벨리 비건 레시피 어덜트 2.72kg', `brand` = '게더' WHERE (`product_id` = '37');
UPDATE `cocobob_dev`.`product` SET `name` = '엔드레스 벨리 비건 레시피 어덜트 1kg', `brand` = '게더' WHERE (`product_id` = '36');
UPDATE `cocobob_dev`.`product` SET `name` = '6Free 플러스 오리고기&연어 5.6kg', `brand` = 'ANF' WHERE (`product_id` = '743');
UPDATE `cocobob_dev`.`product` SET `name` = '6Free 플러스 연어&흰살생선 5.6kg', `brand` = 'ANF' WHERE (`product_id` = '742');
UPDATE `cocobob_dev`.`product` SET `name` = '6Free 플러스 양고기&쌀 5.6kg', `brand` = 'ANF' WHERE (`product_id` = '741');
UPDATE `cocobob_dev`.`product` SET `name` = '6Free 플러스 양고기&쌀 1.8kg', `brand` = 'ANF' WHERE (`product_id` = '740');
UPDATE `cocobob_dev`.`product` SET `name` = '6Free 플러스 소고기&연어 5.6kg', `brand` = 'ANF' WHERE (`product_id` = '739');
UPDATE `cocobob_dev`.`product` SET `name` = '6Free 플러스 소고기&연어 1.8kg', `brand` = 'ANF' WHERE (`product_id` = '738');
UPDATE `cocobob_dev`.`product` SET `name` = '1세이하 닭고기와 현미 5.9kg', `brand` = '뉴트로' WHERE (`product_id` = '20');