alter table product add product_detail_image_webp varchar(1000) null;

UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/ZOE 조이 파테 습식사료 화이트피쉬 369g.jpg' WHERE (`product_id` = '803');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/SHAKEAT 버라이어티팩 4개입.webp' WHERE (`product_id` = '800');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/하루애 수제사료 연어 1kg.webp' WHERE (`product_id` = '666');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/하루애 수제사료 양고기 1kg.webp' WHERE (`product_id` = '665');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/프리미엄 진도 10kg.webp' WHERE (`product_id` = '660');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/이즈그림 루츠 어덜트 독 칠면조 410g.webp' WHERE (`product_id` = '516');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/이즈그림 루츠 어덜트 독 멧돼지 410g.webp' WHERE (`product_id` = '514');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/이즈그림 루츠 어덜트 독 말고기 410g.webp' WHERE (`product_id` = '513');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/윌로펫 뉴트리탑 퍼스트클래스 퍼피 1.2kg.webp' WHERE (`product_id` = '510');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/윌로펫 뉴트리탑 퍼스트클래스 어덜트 1.2kg.webp' WHERE (`product_id` = '509');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/윌로펫 뉴트리탑 퍼스트클래스 면역 1.2kg.webp' WHERE (`product_id` = '508');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/위시본 오리 5.4kg.jpg' WHERE (`product_id` = '507');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/위시본 연어 10.89kg.jpg' WHERE (`product_id` = '506');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/웰츠 퍼피 6kg.webp' WHERE (`product_id` = '505');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/웰츠 퍼피 2.1kg.webp' WHERE (`product_id` = '504');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/웰츠 시니어 독 6kg.webp' WHERE (`product_id` = '503');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/웰츠 시니어 독 2.1kg.webp' WHERE (`product_id` = '502');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/웰츠 독 저지방 다이어트 2.1kg.webp' WHERE (`product_id` = '501');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/웰츠 독 오리 6kg.webp' WHERE (`product_id` = '30');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/웰츠 독 오리 6kg.webp' WHERE (`product_id` = '500');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/웰츠 독 오리 2.1kg.webp' WHERE (`product_id` = '499');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/웰츠 독 연어 6kg.webp' WHERE (`product_id` = '498');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/웰츠 독 연어 2.1kg.webp' WHERE (`product_id` = '497');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/웰츠 독 아이케어 6kg.webp' WHERE (`product_id` = '496');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/웰츠 독 아이케어 2.1kg.webp' WHERE (`product_id` = '495');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/웰츠 독 관절케어 2.1kg.webp' WHERE (`product_id` = '494');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/웰썸 그레인프리 동애등에 3.6kg.jpg' WHERE (`product_id` = '493');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/웰썸 그레인프리 동애등에 1.2kg.jpg' WHERE (`product_id` = '492');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/웰니스 코어 오션 1.8kg.webp' WHERE (`product_id` = '491');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/웰니스 코어 스몰브리드 헬시웨이트 1.8kg.webp' WHERE (`product_id` = '490');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/웰니스 코어 그레인프리 스몰브리드 1.8kg.webp' WHERE (`product_id` = '489');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/웰니스 컴플리트 헬스 헬시 웨이트 스몰브리드 1.8kg.webp' WHERE (`product_id` = '488');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/웰니스 컴플리트 헬스 그레인프리 스몰브리드 1.8kg.webp' WHERE (`product_id` = '487');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/웰니스 심플 그레인프리 연어 2.04kg.webp' WHERE (`product_id` = '486');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/원데이케어 파이토 랩 시니어 1.2kg.jpg' WHERE (`product_id` = '485');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/원데이케어 파이토 랩 센서티브 1.2kg.jpg' WHERE (`product_id` = '484');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/원데이케어 파이토 랩 모빌리티 1.2kg.jpg' WHERE (`product_id` = '483');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/우리주 투뿔리아 수제사료 연어 800g.webp' WHERE (`product_id` = '482');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/우리주 투뿔리아 수제사료 소고기 800g.webp' WHERE (`product_id` = '481');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/우리주 투뿔리아 수제사료 동애등에 800g.webp' WHERE (`product_id` = '480');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/올가밀 홀리스틱 램29 2.7kg.webp' WHERE (`product_id` = '479');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/올가밀 홀리스틱 램29 14kg.webp' WHERE (`product_id` = '478');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/오픈팜 독 화이트피쉬 2.04kg.webp' WHERE (`product_id` = '477');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/오픈팜 독 포크 2.04kg.webp' WHERE (`product_id` = '476');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/오픈팜 독 살몬 2.04kg.webp' WHERE (`product_id` = '474');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/오리젠 피트앤트림 독 11.4kg.jpg' WHERE (`product_id` = '468');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/오리젠 퍼피 라지브리드 6kg.jpg' WHERE (`product_id` = '467');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/오리젠 퍼피 라지브리드 11.4kg.jpg' WHERE (`product_id` = '466');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/오리젠 퍼피 340g.jpg' WHERE (`product_id` = '465');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/오리젠 퍼피 2kg.jpg' WHERE (`product_id` = '464');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/오리젠 퍼피 11.4kg.jpg' WHERE (`product_id` = '463');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/오리젠 오리지널 독 6kg.jpg' WHERE (`product_id` = '462');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/오리젠 오리지널 독 340g.jpg' WHERE (`product_id` = '461');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/오리젠 오리지널 독 2kg.jpg' WHERE (`product_id` = '460');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/오리젠 오리지널 독 11.4kg.jpg' WHERE (`product_id` = '459');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/오리젠 시니어 독 340g.jpg' WHERE (`product_id` = '458');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/오리젠 시니어 독 11.4kg.jpg' WHERE (`product_id` = '457');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/오리젠 스몰브리드 4.5kg.jpg' WHERE (`product_id` = '456');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/오리젠 스몰브리드 1.8kg.jpg' WHERE (`product_id` = '455');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/오리젠 6 피쉬 독 340g.jpg' WHERE (`product_id` = '454');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/오리젠 6 피쉬 독 2kg.jpg' WHERE (`product_id` = '453');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/어드밴스 퍼피 맥시 3kg.webp' WHERE (`product_id` = '452');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/어드밴스 퍼피 맥시 12kg.webp' WHERE (`product_id` = '451');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/어드밴스 독 퍼피 센시티브 3kg.webp' WHERE (`product_id` = '449');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/어드밴스 독 퍼피 미디엄 3kg.webp' WHERE (`product_id` = '448');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/어드밴스 독 퍼피 미디엄 12kg.webp' WHERE (`product_id` = '447');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/어드밴스 독 퍼피 미니 800g.webp' WHERE (`product_id` = '446');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/어드밴스 독 퍼피 미니 7.5kg.webp' WHERE (`product_id` = '445');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/어드밴스 독 퍼피 미니 3kg.webp' WHERE (`product_id` = '444');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/어드밴스 독 저먼 셰퍼드 어덜트 12kg.webp' WHERE (`product_id` = '443');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/어드밴스 독 어덜트 미디엄 3kg.webp' WHERE (`product_id` = '442');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/어드밴스 독 어덜트 미디엄 14kg.webp' WHERE (`product_id` = '441');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/어드밴스 독 어덜트 미니 800g.webp' WHERE (`product_id` = '440');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/어드밴스 독 어덜트 미니 7.5kg.webp' WHERE (`product_id` = '439');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/어드밴스 독 어덜트 미니 3kg.webp' WHERE (`product_id` = '438');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/어드밴스 독 어덜트 맥시 14kg.webp' WHERE (`product_id` = '437');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/어드밴스 독 시니어 미디엄 3kg.webp' WHERE (`product_id` = '436');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/어드밴스 독 시니어 미디엄 12kg.webp' WHERE (`product_id` = '435');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/어드밴스 독 시니어 미니 7.5kg.webp' WHERE (`product_id` = '434');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/어드밴스 독 시니어 미니 3kg.webp' WHERE (`product_id` = '433');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/어드밴스 독 센시티브 미니 800g.webp' WHERE (`product_id` = '432');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/어드밴스 독 센시티브 미니 7.5kg.webp' WHERE (`product_id` = '431');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/어드밴스 독 센시티브 미니 3kg.webp' WHERE (`product_id` = '430');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/어드밴스 독 센시티브 3kg.webp' WHERE (`product_id` = '429');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/어드밴스 독 센시티브 12kg.webp' WHERE (`product_id` = '428');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/어드밴스 독 라이트 미디엄 3kg.webp' WHERE (`product_id` = '427');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/어드밴스 독 라이트 미디엄 12kg.webp' WHERE (`product_id` = '426');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/어드밴스 독 라이트 미니 7.5kg.webp' WHERE (`product_id` = '425');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/어드밴스 독 라이트 미니 3kg.webp' WHERE (`product_id` = '424');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/아투 퍼피 연어 5kg.webp' WHERE (`product_id` = '416');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/아투 퍼피 연어 1.5kg.webp' WHERE (`product_id` = '415');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/아투 독 칠면조 5kg.webp' WHERE (`product_id` = '414');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/아투 독 칠면조 10kg.webp' WHERE (`product_id` = '413');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/아투 독 칠면조 1.5kg.webp' WHERE (`product_id` = '412');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/아투 독 치킨 5kg.webp' WHERE (`product_id` = '411');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/아투 독 치킨 10kg.webp' WHERE (`product_id` = '410');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/아투 독 치킨 1.5kg.webp' WHERE (`product_id` = '409');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/아투 독 오리 10kg.webp' WHERE (`product_id` = '408');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/아투 독 연어 5kg.webp' WHERE (`product_id` = '407');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/아투 독 연어 10kg.webp' WHERE (`product_id` = '406');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/아투 독 연어 1.5kg.webp' WHERE (`product_id` = '405');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/아투 독 쉘피쉬 5kg.webp' WHERE (`product_id` = '404');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/아투 독 쉘피쉬 10kg.webp' WHERE (`product_id` = '403');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/아투 독 쉘피쉬 1.5kg.webp' WHERE (`product_id` = '402');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아카나 헤리티지 퍼피 앤 주니어 독 6kg.jpg' WHERE (`product_id` = '401');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아카나 헤리티지 퍼피 앤 주니어 독 2kg.jpg' WHERE (`product_id` = '399');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아카나 헤리티지 퍼피 앤 주니어 독 2kg.jpg' WHERE (`product_id` = '400');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아카나 헤리티지 퍼피 앤 주니어 독 11.4kg.jpg' WHERE (`product_id` = '398');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아카나 헤리티지 어덜트 라지브리드 독  11.4kg.jpg' WHERE (`product_id` = '397');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아카나 헤리티지 시니어 독 6kg.jpg' WHERE (`product_id` = '396');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아카나 헤리티지 시니어 독 2kg.jpg' WHERE (`product_id` = '395');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아카나 헤리티지 시니어 독 11.4kg.jpg' WHERE (`product_id` = '394');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아카나 헤리티지 라이트 앤 피트 독 11.4kg.jpg' WHERE (`product_id` = '393');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아카나 프리런 덕 6kg.jpg' WHERE (`product_id` = '392');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아카나 프리런 덕 2kg.jpg' WHERE (`product_id` = '391');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아카나 프리런 덕 11.4kg.jpg' WHERE (`product_id` = '390');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아카나 퍼피 스몰브리드 2kg.jpg' WHERE (`product_id` = '389');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아카나 클래식 프레이리 폴트리 독 6kg.jpg' WHERE (`product_id` = '388');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아카나 클래식 프레이리 폴트리 독 340g.jpg' WHERE (`product_id` = '29');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아카나 클래식 프레이리 폴트리 독 340g.jpg' WHERE (`product_id` = '387');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아카나 클래식 프레이리 폴트리 독 2kg.jpg' WHERE (`product_id` = '386');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아카나 클래식 와일드 코스트 독 6kg.jpg' WHERE (`product_id` = '385');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아카나 클래식 와일드 코스트 독 340g.jpg' WHERE (`product_id` = '384');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아카나 클래식 와일드 코스트 독 2kg.jpg' WHERE (`product_id` = '383');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아카나 와일드 프레이리 독 6kg.jpg' WHERE (`product_id` = '382');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아카나 어덜트 스몰브리드 6kg.jpg' WHERE (`product_id` = '381');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아카나 어덜트 스몰브리드 2kg.jpg' WHERE (`product_id` = '380');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아카나 어덜트 독 6kg.jpg' WHERE (`product_id` = '379');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아카나 어덜트 독 2kg.jpg' WHERE (`product_id` = '378');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아카나 어덜트 독 11.4kg.jpg' WHERE (`product_id` = '377');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아카나 리저널 패시피카 독 6kg.jpg' WHERE (`product_id` = '376');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아카나 리저널 패시피카 독 340g.jpg' WHERE (`product_id` = '375');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아카나 리저널 패시피카 독 2kg.jpg' WHERE (`product_id` = '374');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/아침애 수제사료 한우 800g.webp' WHERE (`product_id` = '373');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/아침애 수제사료 피부개선 1.8kg.webp' WHERE (`product_id` = '372');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/아침애 수제사료 저칼로리 곤약 다이어트 1.8kg.webp' WHERE (`product_id` = '371');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/아침애 수제사료 저단백 해조류 1.8kg.webp' WHERE (`product_id` = '370');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아이누 슬로우 베이크드 연어 1.5kg.jpg' WHERE (`product_id` = '368');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아스쿠 펠리쿠치나 오리고기 3kg.jpg' WHERE (`product_id` = '367');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아스쿠 펠리쿠치나 오리고기 1.2kg.jpg' WHERE (`product_id` = '366');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아스쿠 펠리쿠치나 연어 3kg.jpg' WHERE (`product_id` = '365');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아스쿠 펠리쿠치나 연어 1.2kg.jpg' WHERE (`product_id` = '364');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/아스쿠 펠리쿠치나 소고기 3kg.jpg' WHERE (`product_id` = '363');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/아보덤 조인트 헬스 그레인프리 치킨 1kg.webp' WHERE (`product_id` = '357');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/아보덤 조인트 헬스 그레인프리 4.7kg.webp' WHERE (`product_id` = '356');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/아미티 도그 치킨 어덜트 4kg.webp' WHERE (`product_id` = '352');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/아미티 도그 치킨 어덜트 14kg.webp' WHERE (`product_id` = '351');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/아미티 도그 이베리안포크 어덜트 4kg.webp' WHERE (`product_id` = '350');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/아미티 도그 이베리안포크 어덜트 14kg.webp' WHERE (`product_id` = '349');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/아미티 도그 살몬 어덜트 4kg.webp' WHERE (`product_id` = '348');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/아미티 도그 살몬 어덜트 14kg.webp' WHERE (`product_id` = '347');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 흰살생선과 야채 캔 100g 12개 묶음.webp' WHERE (`product_id` = '346');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 흰살생선과 야채 캔 100g.webp' WHERE (`product_id` = '345');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 홀썸볼 쇠고기,닭고기,당근,보리,콩,비타민,미네랄 85g.webp' WHERE (`product_id` = '344');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 연어와 감자 캔 100g 5개 묶음.webp' WHERE (`product_id` = '343');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 연어와 감자 캔 100g 12개 묶음.webp' WHERE (`product_id` = '342');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 연어와 감자 캔 100g.webp' WHERE (`product_id` = '341');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 양고기 캔 100g 12개 묶음.webp' WHERE (`product_id` = '340');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 양고기 캔 100g.webp' WHERE (`product_id` = '339');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 심플리 크래프티드 닭고기,당근,완두콩 37g.webp' WHERE (`product_id` = '338');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 심플리 크래프티드 닭고기,당근,감자,완두콩 37g 12개 묶음.webp' WHERE (`product_id` = '337');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 심플리 크래프티드 닭고기,당근,감자,완두콩 37g.webp' WHERE (`product_id` = '336');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 심플리 크래프티드 닭고기,고구마,사과,보리,시금치 37g 12개 묶음.webp' WHERE (`product_id` = '335');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 심플리 크래프티드 닭고기,고구마,사과,보리,시금치 37g.webp' WHERE (`product_id` = '334');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 쇠고기와 치즈 캔 100g 5개 묶음.webp' WHERE (`product_id` = '333');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 쇠고기와 치즈 캔 100g 12개 묶음.webp' WHERE (`product_id` = '332');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 쇠고기와 참치 캔 100g 12개 묶음.webp' WHERE (`product_id` = '331');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 쇠고기와 닭고기 캔 100g 5개 묶음.webp' WHERE (`product_id` = '330');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 쇠고기와 닭고기 캔 100g 12개 묶음.webp' WHERE (`product_id` = '329');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 쇠고기와 닭고기 캔 100g.webp' WHERE (`product_id` = '328');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 쇠고기와 달걀 1세이하 캔 100g 5개 묶음.webp' WHERE (`product_id` = '327');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 쇠고기와 달걀 1세이하 캔 100g 12개 묶음.webp' WHERE (`product_id` = '326');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 쇠고기와 달걀 1세이하 캔 100g.webp' WHERE (`product_id` = '325');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 쇠고기 캔 100g 5개 묶음.webp' WHERE (`product_id` = '324');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 쇠고기 캔 100g 12개 묶음.webp' WHERE (`product_id` = '323');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 쇠고기 캔 100g.webp' WHERE (`product_id` = '322');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 불고기 캔 100g 12개 묶음.webp' WHERE (`product_id` = '321');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 불고기 캔 100g.webp' WHERE (`product_id` = '320');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 닭고기 캔 100g 5개 묶음.webp' WHERE (`product_id` = '319');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 닭고기 캔 100g 12개 묶음.webp' WHERE (`product_id` = '318');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 닭고기 캔 100g.webp' WHERE (`product_id` = '317');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 14세이상 쇠고기 현미와 야채 캔 100g 5개 묶음.webp' WHERE (`product_id` = '315');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 14세이상 쇠고기 현미와 야채 캔 100g 12개 묶음.webp' WHERE (`product_id` = '314');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 14세이상 쇠고기 현미와 야채 캔 100g.webp' WHERE (`product_id` = '313');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 14세이상 닭고기 현미와 야채 캔 100g 5개 묶음.webp' WHERE (`product_id` = '312');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 14세이상 닭고기 현미와 야채 캔 100g 12개 묶음.webp' WHERE (`product_id` = '311');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 14세이상 닭고기 현미와 야채 캔 100g.webp' WHERE (`product_id` = '310');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시저 11세이상 쇠고기 캔 100g 12개 묶음.webp' WHERE (`product_id` = '308');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시리우스 윌 프리바이오틱스 가수분해 칠면조 1kg.webp' WHERE (`product_id` = '306');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/시리우스 윌 프리바이오틱스 가수분해 연어 1kg.webp' WHERE (`product_id` = '305');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/슈퍼포우 동결건조 자연식 오리후레이크 180g.jpg' WHERE (`product_id` = '304');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/슈퍼포우 동결건조 자연식 연어 첵스 180g.jpg' WHERE (`product_id` = '303');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/슈퍼포우 동결건조 자연식 램프로스트 180g.jpg' WHERE (`product_id` = '302');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/소프트플러스 참좋은 황태사료 오리 1kg.jpg' WHERE (`product_id` = '301');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/브이플래닛 미니 6.8kg.jpg' WHERE (`product_id` = '300');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/브이플래닛 레귤러 6.8kg.jpg' WHERE (`product_id` = '299');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/벨포아 홀리스틱 그레인프리 인섹트 미니 7.5kg.jpg' WHERE (`product_id` = '298');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/벨포아 홀리스틱 그레인프리 인섹트 미니 2.5kg.jpg' WHERE (`product_id` = '297');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/베러펫 개똑 습식사료 연어 840g.webp' WHERE (`product_id` = '296');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/베러펫 개똑 습식사료 연어 70g.jpg' WHERE (`product_id` = '295');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/베러펫 개똑 습식사료 쇠고기 70g.jpg' WHERE (`product_id` = '294');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/베러펫 개똑 습식사료 닭고기 840g.webp' WHERE (`product_id` = '293');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/베러펫 개똑 습식사료 닭고기 70g.jpg' WHERE (`product_id` = '292');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/베기도그 그레인프리 2.1kg.jpg' WHERE (`product_id` = '291');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/벅스펫 베지믹스 눈물개선 50g.jpg' WHERE (`product_id` = '290');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/벅스펫 베지믹스 관절건강 50g.jpg' WHERE (`product_id` = '289');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/벅스펫 벅스독 오리지널 인섹트 곤충사료 1.2kg.jpg' WHERE (`product_id` = '287');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/바이탈에센셜 독 오리 미니 패티 포뮬라 453g.webp' WHERE (`product_id` = '286');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/바이탈에센셜 독 연어 미니닙 포뮬라 397g.webp' WHERE (`product_id` = '285');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/몬지 독 오븐베이크 그릴 신선한 포크 100g.webp' WHERE (`product_id` = '282');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/몬지 독 오븐베이크 그릴 신선한 대구 100g.webp' WHERE (`product_id` = '281');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/몬지 독 오븐베이크 그릴 신선한 닭고기와 칠면조 조각 100g.webp' WHERE (`product_id` = '280');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/몬지 독 오븐베이크 그릴 시니어 오리 100g.webp' WHERE (`product_id` = '279');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/몬지 독 비와일드 그레인프리 올브리드 어덜트 오리 2.5kg.webp' WHERE (`product_id` = '278');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/몬지 독 비와일드 그레인프리 올브리드 어덜트 연어 2.5kg.webp' WHERE (`product_id` = '277');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/몬지 독 비와일드 그레인프리 올브리드 어덜트 멸치 2.5kg.webp' WHERE (`product_id` = '276');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/맥아담스 방목 치킨과 연어 중형견용 2kg.webp' WHERE (`product_id` = '275');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/맥아담스 방목 치킨 퍼피 2kg.webp' WHERE (`product_id` = '274');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/마이펫닥터 인섹트 더 제로 1kg.jpg' WHERE (`product_id` = '273');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/마이펫닥터 시그니처 오가닉 슬림컨트롤 2kg.jpg' WHERE (`product_id` = '272');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/마이펫닥터 시그니처 오가닉 스킨컨트롤 2kg.jpg' WHERE (`product_id` = '271');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로우즈 밀프리 LID 드라이 푸드 독 연어 4.5kg.webp' WHERE (`product_id` = '270');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로우즈 밀프리 LID 드라이 푸드 독 연어 1.5kg.webp' WHERE (`product_id` = '269');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로우즈 밀프리 드라이 푸드 독 치킨 4.5kg.webp' WHERE (`product_id` = '268');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로우즈 밀프리 드라이 푸드 독 치킨 1.5kg.webp' WHERE (`product_id` = '267');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로우즈 밀프리 드라이 푸드 독 연어 4.5kg.webp' WHERE (`product_id` = '266');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로우즈 밀프리 드라이 푸드 독 연어 1.5kg.webp' WHERE (`product_id` = '265');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 프렌치불독 어덜트 3kg 근육형성.webp' WHERE (`product_id` = '264');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 푸들 퍼피 1.5kg 피모관리.webp' WHERE (`product_id` = '263');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 푸들 어덜트 파우치 85g 피모관리.webp' WHERE (`product_id` = '262');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 푸들 어덜트 500g 피모관리.webp' WHERE (`product_id` = '261');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 푸들 어덜트 3kg 피모관리.webp' WHERE (`product_id` = '260');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 포메라니안 어덜트 파우치 85g 관절 건강.webp' WHERE (`product_id` = '259');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 포메라니안 어덜트 500g 관절 건강.webp' WHERE (`product_id` = '258');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 포메라니안 어덜트 3kg 관절 건강.webp' WHERE (`product_id` = '257');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 포메라니안 어덜트 1.5kg 관절 건강.webp' WHERE (`product_id` = '256');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 치와와 어덜트 500g 치석관리.webp' WHERE (`product_id` = '254');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 치와와 어덜트 3kg 치석관리.webp' WHERE (`product_id` = '253');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 요크셔테리어 어덜트 1.5kg 피모관리.webp' WHERE (`product_id` = '251');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 엑스스몰 퍼피 3kg 면역력.webp' WHERE (`product_id` = '250');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 엑스스몰 퍼피 14kg 면역력.webp' WHERE (`product_id` = '249');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 엑스스몰 어덜트 11kg 피모관리.webp' WHERE (`product_id` = '248');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 어덜트 뷰티 캔 195g.webp' WHERE (`product_id` = '247');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 어덜트 라이트 캔 195g.webp' WHERE (`product_id` = '246');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 스테럴라이즈드 1kg 중성화견.webp' WHERE (`product_id` = '244');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 슈나우져 어덜트 3kg 요로 건강.webp' WHERE (`product_id` = '242');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 비숑프리제 어덜트 1.5kg.webp' WHERE (`product_id` = '241');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 미디움 퍼피 4kg 중형견 면역증진.webp' WHERE (`product_id` = '240');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 미디움 퍼피 10kg 중형견 면역증진.webp' WHERE (`product_id` = '239');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 미디움 어덜트 4kg 중형견 면역증진.webp' WHERE (`product_id` = '238');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 미디움 어덜트 10kg 중형견 면역증진.webp' WHERE (`product_id` = '237');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 미디엄 라이트 웨이트 케어 12kg 다이어트.webp' WHERE (`product_id` = '236');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 미디엄 더마컴포트 10kg 피부 보호.webp' WHERE (`product_id` = '235');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 미니 퍼피 8kg 면역 증진.webp' WHERE (`product_id` = '234');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 미니 코트케어 1kg 피모관리.webp' WHERE (`product_id` = '233');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/로얄캐닌 미니 코트 케어 파우치 85g 피모관리.jpg' WHERE (`product_id` = '232');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/로얄캐닌 미니 코트 케어 3kg 피모관리.jpg' WHERE (`product_id` = '231');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/로얄캐닌 미니 인도어 퍼피 8.7kg 면역력.jpg' WHERE (`product_id` = '230');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/로얄캐닌 미니 인도어 퍼피 500g 면역력.jpg' WHERE (`product_id` = '229');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/로얄캐닌 미니 인도어 퍼피 3kg 면역력.jpg' WHERE (`product_id` = '228');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/로얄캐닌 미니 인도어 어덜트 8.7kg 소화기 건강.jpg' WHERE (`product_id` = '227');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/로얄캐닌 미니 인도어 어덜트 500g 소화기 건강.jpg' WHERE (`product_id` = '226');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/로얄캐닌 미니 인도어 어덜트 3kg 소화기 건강.jpg' WHERE (`product_id` = '225');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 미니 인도어 시니어 1.5kg 소화 도움.webp' WHERE (`product_id` = '224');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/로얄캐닌 미니 어덜트 파우치 85g 장건강.jpg' WHERE (`product_id` = '223');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 미니 어덜트 8kg 치석 예방.webp' WHERE (`product_id` = '222');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/로얄캐닌 미니 스테럴라이즈드 파우치 85g 중성화견.jpg' WHERE (`product_id` = '221');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/로얄캐닌 미니 스테럴라이즈드 3kg 중성화견.jpg' WHERE (`product_id` = '220');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 미니 스타터 3kg 면역증진.webp' WHERE (`product_id` = '218');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/로얄캐닌 미니 릴렉스 케어 파우치 85g 심신안정.jpg' WHERE (`product_id` = '217');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/로얄캐닌 미니 릴렉스 케어 3kg 심신안정.jpg' WHERE (`product_id` = '216');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/로얄캐닌 미니 라이트웨이트 케어 3kg 체중조절.jpg' WHERE (`product_id` = '215');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 미니 라이트웨이트 케어 1kg 체중조절.webp' WHERE (`product_id` = '214');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/로얄캐닌 미니 더마컴포트 파우치 85g 피부 보호.jpg' WHERE (`product_id` = '213');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 미니 더마컴포트 케어 1kg 피부 보호.webp' WHERE (`product_id` = '212');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/로얄캐닌 미니 더마컴포트 3kg 피부 보호.jpg' WHERE (`product_id` = '211');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/로얄캐닌 미니 다이제스티브 파우치 85g 소화 도움.jpg' WHERE (`product_id` = '210');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/로얄캐닌 미니 다이제스티브 3kg 소화 도움.jpg' WHERE (`product_id` = '209');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 머츄어8 캔 195g.webp' WHERE (`product_id` = '208');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/로얄캐닌 맥시 퍼피 4kg 대형견 면역증진.jpg' WHERE (`product_id` = '207');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/로얄캐닌 맥시 퍼피 10kg 대형견 면역증진.jpg' WHERE (`product_id` = '206');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/로얄캐닌 맥시 어덜트 4kg 대형견 관절건강.jpg' WHERE (`product_id` = '205');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/로얄캐닌 맥시 어덜트 10kg 대형견 관절건강.jpg' WHERE (`product_id` = '204');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/로얄캐닌 말티즈 어덜트 500g 피모관리.jpg' WHERE (`product_id` = '203');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/로얄캐닌 말티즈 어덜트 4.5kg 기획팩.jpg' WHERE (`product_id` = '202');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/로얄캐닌 말티즈 어덜트 3kg 피모관리.jpg' WHERE (`product_id` = '201');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/로얄캐닌 말티즈 어덜트 1.5kg 피모관리.jpg' WHERE (`product_id` = '200');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 릴렉스 케어 1kg 심신안정.webp' WHERE (`product_id` = '28');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 릴렉스 케어 1kg 심신안정.webp' WHERE (`product_id` = '199');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 라브라도리트리버 어덜트 3kg 관절 건강.webp' WHERE (`product_id` = '197');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 라브라도리트리버 어덜트 12kg 관절건강.webp' WHERE (`product_id` = '196');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 독 푸들 어덜트 7.5kg.webp' WHERE (`product_id` = '195');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 닥스훈트 어덜트 1.5kg 관절 건강.webp' WHERE (`product_id` = '193');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/로얄캐닌 다이제스티브 케어 1kg 소화 도움.webp' WHERE (`product_id` = '192');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/럭셔리발란스 양고기 캔 380g.webp' WHERE (`product_id` = '191');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/럭셔리발란스 소고기 캔 380g.webp' WHERE (`product_id` = '190');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/럭셔리발란스 닭고기 캔 380g.webp' WHERE (`product_id` = '189');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/라포그 리얼 인섹트 관절 1.2kg.jpg' WHERE (`product_id` = '188');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/라포그 리얼 인섹트 1.2kg.jpg' WHERE (`product_id` = '187');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/딩고 피쉬 앤 데일리 500g.jpg' WHERE (`product_id` = '186');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/딩고 피쉬 앤 데일리 3kg.jpg' WHERE (`product_id` = '185');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/딩고 피쉬 앤 데일리 12kg.jpg' WHERE (`product_id` = '184');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/딩고 퍼피 앤 주니어 500g.jpg' WHERE (`product_id` = '183');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/딩고 퍼피 앤 주니어 3kg.jpg' WHERE (`product_id` = '182');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/딩고 퍼피 앤 주니어 12kg.jpg' WHERE (`product_id` = '181');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/딩고 토이 앤 데일리 1.5kg.jpg' WHERE (`product_id` = '180');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/딩고 치킨 앤 데일리 500g.jpg' WHERE (`product_id` = '179');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/딩고 치킨 앤 데일리 3kg.jpg' WHERE (`product_id` = '178');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/딩고 치킨 앤 데일리 12kg.jpg' WHERE (`product_id` = '177');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/딩고 에너지 앤 핏 3kg.jpg' WHERE (`product_id` = '176');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/딩고 머튜얼 앤 데일리 3kg.jpg' WHERE (`product_id` = '175');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/듀먼 화식 50g 8개 + 치킨텐더 100g 세트.jpg' WHERE (`product_id` = '174');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/듀먼 화식 100g 8개 + 치킨텐더 100g 세트.jpg' WHERE (`product_id` = '173');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/듀먼 첫 화식세트 50g 8가지맛 콤보, 8개.jpg' WHERE (`product_id` = '172');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/듀먼 첫 화식세트 100g 8가지맛 콤보, 8개.jpg' WHERE (`product_id` = '171');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/듀먼 자연화식 100g 8가지맛 콤보, 16개.jpg' WHERE (`product_id` = '170');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/도비 어덜트 4.5kg.webp' WHERE (`product_id` = '169');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/도기맨 크리미 치킨야채 스프 시니어 80g.webp' WHERE (`product_id` = '168');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/도기맨 크리미 치킨야채 스프 80g.webp' WHERE (`product_id` = '167');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/데이스포 제스트 올스테이지 5kg.webp' WHERE (`product_id` = '166');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/데이스포 제스트 올스테이지 2.6kg.webp' WHERE (`product_id` = '165');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/더마독 장건강 소화 2kg.jpg' WHERE (`product_id` = '164');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/더마독 관절 체중조절 2kg.jpg' WHERE (`product_id` = '163');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/더리얼 그레인프리 크런치 돼지고기 어덜트 1.6kg.webp' WHERE (`product_id` = '162');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/더독 닥터소프트 IGY 치석치주염예방 1.2kg.webp' WHERE (`product_id` = '161');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/더독 닥터소프트 퍼피 1.2kg.webp' WHERE (`product_id` = '160');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/더독 닥터소프트 치킨 시니어 3kg.webp' WHERE (`product_id` = '158');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/더독 닥터소프트 치킨 시니어 1.2kg.webp' WHERE (`product_id` = '157');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/더독 닥터소프트 오리 그레인프리 노령견용 1.2kg.webp' WHERE (`product_id` = '156');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/더독 닥터소프트 양고기와 감자 3kg.webp' WHERE (`product_id` = '155');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/더독 닥터소프트 양고기 1.2kg.webp' WHERE (`product_id` = '154');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/더독 닥터소프트 명작 하이포알러지 연어 전견용 1.2kg.jpg' WHERE (`product_id` = '152');
UPDATE `cocobob_dev`.`product` SET `product_detail_image` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail_resized/더독 닥터소프트 명작 하이포알러지 연어 노령견용 1.2kg.jpg' WHERE (`product_id` = '151');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/뉴트리소스 그레인프리 시니어 13.6kg.webp' WHERE (`product_id` = '136');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/뉴트리소스 그레인프리 라지브리드 퍼피 13.6kg.webp' WHERE (`product_id` = '135');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/뉴트리나 퍼피 2.1kg.webp' WHERE (`product_id` = '134');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/뉴트리나 울트라 진도 대형견용 10kg.webp' WHERE (`product_id` = '133');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/뉴트리나 어덜트 치킨 2.1kg.webp' WHERE (`product_id` = '131');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/뉴트리나 어덜트 연어 2.1kg.webp' WHERE (`product_id` = '130');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/뉴트리나 어덜트 다이어트 2.1kg.webp' WHERE (`product_id` = '129');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/뉴트리나 건강백서 푸들 6kg.webp' WHERE (`product_id` = '128');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/뉴트리나 건강백서 푸들 10.2kg.webp' WHERE (`product_id` = '127');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/뉴트리나 건강백서 포메라니언 6kg.webp' WHERE (`product_id` = '126');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/뉴트리나 건강백서 포메라니언 2kg.webp' WHERE (`product_id` = '125');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/뉴트리나 건강백서 코커스파니엘 2kg.webp' WHERE (`product_id` = '124');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/뉴트리나 건강백서 슈나우져 2kg.webp' WHERE (`product_id` = '123');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/뉴트리나 건강백서 말티즈 6kg.webp' WHERE (`product_id` = '122');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/뉴트리나 건강백서 말티즈 2kg.webp' WHERE (`product_id` = '121');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/뉴트리나 건강백서 말티즈 10.2kg.webp' WHERE (`product_id` = '120');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/뉴트리나 건강백서 건강한 피부 6kg.webp' WHERE (`product_id` = '119');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/뉴트리나 건강백서 건강한 체중 6kg.webp' WHERE (`product_id` = '118');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/뉴트리나 건강백서 건강한 체중 2kg.webp' WHERE (`product_id` = '117');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/뉴트리나 건강백서 건강한 장 10.2kg.webp' WHERE (`product_id` = '116');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/뉴트리나 건강백서 건강한 관절 6kg.webp' WHERE (`product_id` = '115');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/뉴트리나 건강백서 건강한 관절 2kg.webp' WHERE (`product_id` = '114');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/뉴트리나 건강백서 건강한 관절 10.2kg.webp' WHERE (`product_id` = '113');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/뉴트리나 건강백서 건강한 6세이상 6kg.webp' WHERE (`product_id` = '112');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/뉴트리나 건강백서 건강한 6세이상 2kg.webp' WHERE (`product_id` = '111');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/뉴트리나 건강백서 건강한 1세 2kg.webp' WHERE (`product_id` = '110');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/뉴트로 1세이상 닭고기와 현미 5.9kg.webp' WHERE (`product_id` = '27');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/뉴트로 1세이상 닭고기와 현미 5.9kg.webp' WHERE (`product_id` = '109');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/뉴웨이브 홀리스틱 2 양고기 5kg.webp' WHERE (`product_id` = '107');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네츄럴코어 홀리스틱 베네 M32 멀티프로테인 6kg.webp' WHERE (`product_id` = '106');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네츄럴코어 치킨 주식 캔 80g.webp' WHERE (`product_id` = '105');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네츄럴코어 유기농 에코 6 센시티브 솔루션 연어 중간알갱이 2kg.webp' WHERE (`product_id` = '102');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네츄럴코어 유기농 에코 6 센시티브 솔루션 연어 작은알갱이 2.4kg.webp' WHERE (`product_id` = '101');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네츄럴코어 유기농 에코 5 퍼피 작은알갱이 7kg.webp' WHERE (`product_id` = '100');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네츄럴코어 유기농 에코 4 오리고기 슬림다운 6kg.webp' WHERE (`product_id` = '99');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네츄럴코어 유기농 에코 2 오리고기 작은알갱이 7kg.webp' WHERE (`product_id` = '98');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네츄럴코어 유기농 에코 2 오리고기 작은알갱이 2kg.webp' WHERE (`product_id` = '97');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네츄럴코어 에코10 베지테리언 6kg.webp' WHERE (`product_id` = '96');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네츄럴코어 에코 70B 연어 7kg.webp' WHERE (`product_id` = '94');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네츄럴코어 에코 70B 연어 2kg.webp' WHERE (`product_id` = '93');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네츄럴코어 에코 70A 양고기 7kg.webp' WHERE (`product_id` = '92');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네츄럴코어 에코 70A 양고기 2kg.webp' WHERE (`product_id` = '91');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네츄럴코어 에코 2 오리고기 큰알갱이 10kg.webp' WHERE (`product_id` = '90');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네츄럴코어 에코 2 오리고기 작은알갱이 10kg.webp' WHERE (`product_id` = '89');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네츄럴코어 에코 1 양고기 작은알갱이 10kg.webp' WHERE (`product_id` = '88');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네츄럴코어 센시티브케어 베지 3kg.webp' WHERE (`product_id` = '86');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네츄럴코어 센시티브케어 베지 1.2kg.webp' WHERE (`product_id` = '85');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네츄럴코어 센시티브케어 밀웜 3kg.webp' WHERE (`product_id` = '84');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네츄럴코어 센시티브케어 밀웜 1.2kg.webp' WHERE (`product_id` = '83');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네이처스 버라이어티 인스팅트 RBK 헬시웨이트 9kg.webp' WHERE (`product_id` = '79');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네이처스 버라이어티 인스팅트 RBK 헬시웨이트 1.8kg.webp' WHERE (`product_id` = '78');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네이처스 버라이어티 인스팅트 RBK  치킨 9.5kg.webp' WHERE (`product_id` = '75');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네이처스 버라이어티 인스팅트 RBK  장건강 1.8kg.webp' WHERE (`product_id` = '74');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네이처스 버라이어티 인스팅트 LID 칠면조 캔 374g.webp' WHERE (`product_id` = '73');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네이처스 버라이어티 인스팅트 LID 칠면조 10kg.webp' WHERE (`product_id` = '72');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네이처스 버라이어티 인스팅트 LID 칠면조 1.8kg.webp' WHERE (`product_id` = '71');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네이처스 버라이어티 인스팅트 LID 연어 9kg.webp' WHERE (`product_id` = '70');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네이처스 버라이어티 인스팅트 LID 연어 1.8kg.webp' WHERE (`product_id` = '69');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네이처스 버라이어티 인스팅트 헬시크레이빙 치킨 파우치 85g.webp' WHERE (`product_id` = '65');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네이처스 버라이어티 인스팅트 헬시크레이빙 연어 파우치 85g.webp' WHERE (`product_id` = '64');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네이처스 버라이어티 인스팅트 토끼 9kg.webp' WHERE (`product_id` = '63');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네이처스 버라이어티 인스팅트 토끼 1.8kg.webp' WHERE (`product_id` = '62');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네이처스 버라이어티 인스팅트 치킨 10.2kg.webp' WHERE (`product_id` = '61');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네이처스 버라이어티 인스팅트 치킨 1.8kg.webp' WHERE (`product_id` = '60');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/네이처스 버라이어티 인스팅트 오리고기 9kg.webp' WHERE (`product_id` = '59');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/내추로 그레인프리 캔 400g x 6개입 버라이어티팩.webp' WHERE (`product_id` = '56');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/내추로 그레인프리 캔 390g x 6개입 버라이어티팩.webp' WHERE (`product_id` = '55');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/내추럴팩토리 G-FREE 오리와 눈 건강 1.2kg.webp' WHERE (`product_id` = '49');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/내추럴팩토리 G-FREE 연어와 피부 1.2kg.webp' WHERE (`product_id` = '48');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/내추럴팩토리 G-FREE 양고기와 관절 1.2kg.webp' WHERE (`product_id` = '47');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/나인케어 피부강화 3kg.webp' WHERE (`product_id` = '45');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/나인케어 시니어 3kg.webp' WHERE (`product_id` = '44');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/꼬시다 사료 1.4kg.webp' WHERE (`product_id` = '43');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/굿프랜드 스페셜서퍼 닭고기 285g.webp' WHERE (`product_id` = '42');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/게더 프리 에이커 치킨 레시피 어덜트 7.26kg.webp' WHERE (`product_id` = '41');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/게더 프리 에이커 치킨 레시피 어덜트 2.72kg.webp' WHERE (`product_id` = '40');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/게더 프리 에이커 치킨 레시피 어덜트 1kg.webp' WHERE (`product_id` = '39');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/게더 엔드레스 벨리 비건 레시피 어덜트 7.26kg.webp' WHERE (`product_id` = '38');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/게더 엔드레스 벨리 비건 레시피 어덜트 2.72kg.webp' WHERE (`product_id` = '37');
UPDATE `cocobob_dev`.`product` SET `product_detail_image_webp` = 'https://cocobob-storage.s3.ap-northeast-2.amazonaws.com/product_detail/게더 엔드레스 벨리 비건 레시피 어덜트 1kg.webp' WHERE (`product_id` = '36');
