insert into breed values('1','ADMIN','러시안 토이', '초소형');
insert into breed values('2','ADMIN','말티즈', '초소형');
insert into breed values('3','ADMIN','볼로네즈', '초소형');
insert into breed values('4','ADMIN','쁘띠 브라반숑', '초소형');
insert into breed values('5','ADMIN','오스트레일리언 실키 테리어', '초소형');
insert into breed values('6','ADMIN','요크셔테리어', '초소형');
insert into breed values('7','ADMIN','잉글리시 토이 테리어 블랙 앤드 탠', '초소형');
insert into breed values('8','ADMIN','재패니즈 친', '초소형');
insert into breed values('9','ADMIN','차이니스 크레스티드', '초소형');
insert into breed values('10','ADMIN','치와와', '초소형');
insert into breed values('11','ADMIN','콘티넨탈 토이 스패니얼', '초소형');
insert into breed values('12','ADMIN','포메라니안', '초소형');
insert into breed values('13','ADMIN','그리폰 브뤼셀', '소형');
insert into breed values('14','ADMIN','노르웨이 룬트훈트', '소형');
insert into breed values('15','ADMIN','노리치 테리어', '소형');
insert into breed values('16','ADMIN','노퍽 테리어', '소형');
insert into breed values('17','ADMIN','닥스훈트', '소형');
insert into breed values('18','ADMIN','대니시 스웨디시 팜독', '소형');
insert into breed values('19','ADMIN','댄디 딘몬트 테리어', '소형');
insert into breed values('20','ADMIN','더치 스모우스혼트', '소형');
insert into breed values('21','ADMIN','리사압소', '소형');
insert into breed values('22','ADMIN','레이클랜드 테리어', '소형');
insert into breed values('23','ADMIN','로첸(리틀 라이온 독)', '소형');
insert into breed values('24','ADMIN','멘체스터 테리어', '소형');
insert into breed values('25','ADMIN','무디', '소형');
insert into breed values('26','ADMIN','미니어처 슈나우저', '소형');
insert into breed values('27','ADMIN','미니어처 핀셔', '소형');
insert into breed values('28','ADMIN','바셋 포브 드 브르타뉴', '소형');
insert into breed values('29','ADMIN','베들링턴 테리어', '소형');
insert into breed values('30','ADMIN','벨지안 그리폰', '소형');
insert into breed values('31','ADMIN','보더 테리어', '소형');
insert into breed values('32','ADMIN','보스턴 테리어', '소형');
insert into breed values('33','ADMIN','불 테리어', '소형');
insert into breed values('34','ADMIN','브라질리언 테리어', '소형');
insert into breed values('35','ADMIN','비숑 프리제', '소형');
insert into breed values('36','ADMIN','셰틀랜드 쉽독', '소형');
insert into breed values('37','ADMIN','스웨디시 발훈트(비지고딕 스피츠)', '소형');
insert into breed values('38','ADMIN','스카이 테리어', '소형');
insert into breed values('39','ADMIN','스코티시 테리어', '소형');
insert into breed values('40','ADMIN','스키퍼키', '소형');
insert into breed values('41','ADMIN','시바', '소형');
insert into breed values('42','ADMIN','시츄', '소형');
insert into breed values('43','ADMIN','실리엄 테리어', '소형');
insert into breed values('44','ADMIN','아펜핀셔', '소형');
insert into breed values('45','ADMIN','오베르뉴 포인터', '소형');
insert into breed values('46','ADMIN','오스트레일리안 테리어', '소형');
insert into breed values('47','ADMIN','웨스트 하일랜드 화이트 테리어', '소형');
insert into breed values('48','ADMIN','웰시 테리어', '소형');
insert into breed values('49','ADMIN','이탈리안 그레이하운드', '소형');
insert into breed values('50','ADMIN','이탈리안 볼피노', '소형');
insert into breed values('51','ADMIN','재패니즈 스피츠', '소형');
insert into breed values('52','ADMIN','재패니즈 테리어', '소형');
insert into breed values('53','ADMIN','잭 러셀 테리어', '소형');
insert into breed values('54','ADMIN','저먼 헌팅 테리어', '소형');
insert into breed values('55','ADMIN','체스키 테리어', '소형');
insert into breed values('56','ADMIN','카발리에 킹 찰스 스패니얼', '소형');
insert into breed values('57','ADMIN','케언 테리어', '소형');
insert into breed values('58','ADMIN','코통 드 튈레아르', '소형');
insert into breed values('59','ADMIN','킹 찰스 스패니얼', '소형');
insert into breed values('60','ADMIN','티벳탄 스패니얼', '소형');
insert into breed values('61','ADMIN','파슨 러셀 테리어', '소형');
insert into breed values('62','ADMIN','퍼그', '소형');
insert into breed values('63','ADMIN','페키니즈', '소형');
insert into breed values('64','ADMIN','포르투기즈 와런 하운드(포르투기즈 포덴고)', '소형');
insert into breed values('65','ADMIN','폭스 테리어 스무스', '소형');
insert into breed values('66','ADMIN','폭스 테리어 와이어', '소형');
insert into breed values('67','ADMIN','푸미', '소형');
insert into breed values('68','ADMIN','피레니안 셰퍼드(스무스 페이스드)', '소형');
insert into breed values('69','ADMIN','피레니안 쉽독', '소형');
insert into breed values('70','ADMIN','허배너스', '소형');
insert into breed values('71','ADMIN','휘핏', '소형');
insert into breed values('72','ADMIN','가스콘 세인톤죠이스', '중형');
insert into breed values('73','ADMIN','그랜드 바셋 그리폰 방뎅', '중형');
insert into breed values('74','ADMIN','그리폰 니베르네', '중형');
insert into breed values('75','ADMIN','그릭 헤어하운드', '중형');
insert into breed values('76','ADMIN','기슈', '중형');
insert into breed values('77','ADMIN','노르보텐스피치', '중형');
insert into breed values('78','ADMIN','노르웨이안 부훈트', '중형');
insert into breed values('79','ADMIN','노르웨이안 하운드', '중형');
insert into breed values('80','ADMIN','노르웨이언 엘크하운드', '중형');
insert into breed values('81','ADMIN','노바 스코셔 덕 톨링 레트리버', '중형');
insert into breed values('82','ADMIN','더치 샤펜도스', '중형');
insert into breed values('83','ADMIN','도베르만', '중형');
insert into breed values('84','ADMIN','드레버', '중형');
insert into breed values('85','ADMIN','라포니안 허더', '중형');
insert into breed values('86','ADMIN','러시안 유러피안 라이카', '중형');
insert into breed values('87','ADMIN','로마그나 워터 독', '중형');
insert into breed values('88','ADMIN','멕시칸 헤어리스 독', '중형');
insert into breed values('89','ADMIN','몬터니그런 마운틴 하운드', '중형');
insert into breed values('90','ADMIN','미디움 사이즈드 앵글로 프렌치 하운드', '중형');
insert into breed values('91','ADMIN','바바리안 마운틴 센트 하운드', '중형');
insert into breed values('92','ADMIN','바베트', '중형');
insert into breed values('93','ADMIN','바센지', '중형');
insert into breed values('94','ADMIN','바셋 블뢰 드 가스코뉴', '중형');
insert into breed values('95','ADMIN','바셋 아르테지앙 노르만', '중형');
insert into breed values('96','ADMIN','베르가마스코 셰퍼드 독', '중형');
insert into breed values('97','ADMIN','벨지안 셰퍼드 독', '중형');
insert into breed values('98','ADMIN','보더 콜리', '중형');
insert into breed values('99','ADMIN','보스니안 브로큰 헤어드 하운드(바락)', '중형');
insert into breed values('100','ADMIN','부르보네 포인트 독', '중형');
insert into breed values('101','ADMIN','부비에 드 아르덴느', '중형');
insert into breed values('102','ADMIN','불독', '중형');
insert into breed values('103','ADMIN','브리케 그리폰 방댕', '중형');
insert into breed values('104','ADMIN','브리트니 스패니얼', '중형');
insert into breed values('105','ADMIN','블루 가스코니 그리폰', '중형');
insert into breed values('106','ADMIN','블루 피카르디 스패니얼', '중형');
insert into breed values('107','ADMIN','비글', '중형');
insert into breed values('108','ADMIN','비글 해리어', '중형');
insert into breed values('109','ADMIN','비어다드 콜리', '중형');
insert into breed values('110','ADMIN','쁘띠 바셋 그리폰 방댕', '중형');
insert into breed values('111','ADMIN','사모예드', '중형');
insert into breed values('112','ADMIN','살루키', '중형');
insert into breed values('113','ADMIN','샤페이', '중형');
insert into breed values('114','ADMIN','서식스 스패니얼', '중형');
insert into breed values('115','ADMIN','세르비안 트라이컬러 하운드', '중형');
insert into breed values('116','ADMIN','세르비안 하운드', '중형');
insert into breed values('117','ADMIN','세인트 저먼 포인터', '중형');
insert into breed values('118','ADMIN','슈나우저', '중형');
insert into breed values('119','ADMIN','스말랜드스퇴바레', '중형');
insert into breed values('120','ADMIN','스몰 블루 가스코니', '중형');
insert into breed values('121','ADMIN','스웨디시 라프훈트', '중형');
insert into breed values('122','ADMIN','스위스 하운드', '중형');
insert into breed values('123','ADMIN','스타포드셔 불 테리어', '중형');
insert into breed values('124','ADMIN','스테비훈', '중형');
insert into breed values('125','ADMIN','스패니시 워터 독', '중형');
insert into breed values('126','ADMIN','스패니시 하운드', '중형');
insert into breed values('127','ADMIN','스피츠', '중형');
insert into breed values('128','ADMIN','슬로바키안 와이어 헤어드 포인터', '중형');
insert into breed values('129','ADMIN','슬로바키안 하운드', '중형');
insert into breed values('130','ADMIN','슬루기', '중형');
insert into breed values('131','ADMIN','시르네코 델레트나', '중형');
insert into breed values('132','ADMIN','시베리안 허스키', '중형');
insert into breed values('133','ADMIN','시코쿠', '중형');
insert into breed values('134','ADMIN','실레르스퇴바레', '중형');
insert into breed values('135','ADMIN','아리에쥬아', '중형');
insert into breed values('136','ADMIN','아메리칸 스태퍼드셔 테리어', '중형');
insert into breed values('137','ADMIN','아메리칸 워터 스패니얼', '중형');
insert into breed values('138','ADMIN','아메리칸 코커 스패니얼', '중형');
insert into breed values('139','ADMIN','아메리칸 폭스하운드', '중형');
insert into breed values('140','ADMIN','아이리시 글렌 오브 이말 테리어', '중형');
insert into breed values('141','ADMIN','아이리시 레드 세터', '중형');
insert into breed values('142','ADMIN','아이리시 레드 앤드 화이트 세터', '중형');
insert into breed values('143','ADMIN','아이리시 소프트코티드 휘튼 테리어', '중형');
insert into breed values('144','ADMIN','아이리시 워터 스패니얼', '중형');
insert into breed values('145','ADMIN','아이리시 테리어', '중형');
insert into breed values('146','ADMIN','아이슬랜드 쉽독', '중형');
insert into breed values('147','ADMIN','아펜젤러 세넨훈드', '중형');
insert into breed values('148','ADMIN','알라스카 말라뮤트', '중형');
insert into breed values('149','ADMIN','알파인 닥스브라크', '중형');
insert into breed values('150','ADMIN','에리에지 포인팅 독', '중형');
insert into breed values('151','ADMIN','에어데일 테리어', '중형');
insert into breed values('152','ADMIN','엔틀버쳐 캐틀 독', '중형');
insert into breed values('153','ADMIN','오스트레일리안 셰퍼드', '중형');
insert into breed values('154','ADMIN','오스트레일리안 스텀피 테일 캐틀 독', '중형');
insert into breed values('155','ADMIN','오스트레일리안 켈피', '중형');
insert into breed values('156','ADMIN','오스트리안 블랙 앤드 탄 하운드', '중형');
insert into breed values('157','ADMIN','오스트리안 핀셔', '중형');
insert into breed values('158','ADMIN','와이어-헤어드 포인팅 그리폰 코르탈스', '중형');
insert into breed values('159','ADMIN','웨스트 시베리안 라이카', '중형');
insert into breed values('160','ADMIN','웨스트팔리안 닥스브라케', '중형');
insert into breed values('161','ADMIN','웰시 스프링어 스패니얼', '중형');
insert into breed values('162','ADMIN','웰시 코기', '중형');
insert into breed values('163','ADMIN','유라시안', '중형');
insert into breed values('164','ADMIN','이비전 포덴코', '중형');
insert into breed values('165','ADMIN','이스트 시베리안 라이카', '중형');
insert into breed values('166','ADMIN','이스트리안 쇼트-헤어드 하운드', '중형');
insert into breed values('167','ADMIN','이스트리안 와이어-헤어드 하운드', '중형');
insert into breed values('168','ADMIN','이탈리안 쇼트 헤어드 세구죠', '중형');
insert into breed values('169','ADMIN','이탈리안 콜스 헤어드 하운드', '중형');
insert into breed values('170','ADMIN','잉글리스 세터(르웰린)', '중형');
insert into breed values('171','ADMIN','잉글리시 스프링거 스패니얼', '중형');
insert into breed values('172','ADMIN','잉글리시 코커 스패니얼', '중형');
insert into breed values('173','ADMIN','저먼 스패니얼', '중형');
insert into breed values('174','ADMIN','저먼 핀셔', '중형');
insert into breed values('175','ADMIN','저먼 하운드', '중형');
insert into breed values('176','ADMIN','진돗개', '중형');
insert into breed values('177','ADMIN','차우차우', '중형');
insert into breed values('178','ADMIN','카르스트 셰퍼드 독', '중형');
insert into breed values('179','ADMIN','카이', '중형');
insert into breed values('180','ADMIN','카탈란 쉽독', '중형');
insert into breed values('181','ADMIN','커릴리언 베어 독', '중형');
insert into breed values('182','ADMIN','케리 블루 테리어', '중형');
insert into breed values('183','ADMIN','케이넌 독', '중형');
insert into breed values('184','ADMIN','콜리 러프', '중형');
insert into breed values('185','ADMIN','콜리 스무스', '중형');
insert into breed values('186','ADMIN','콜스-헤어드 스타이리안 하운드', '중형');
insert into breed values('187','ADMIN','쿠이커혼제', '중형');
insert into breed values('188','ADMIN','크로아티안 셰퍼드 독', '중형');
insert into breed values('189','ADMIN','크롬폴란데', '중형');
insert into breed values('190','ADMIN','클라인 문스터렌더', '중형');
insert into breed values('191','ADMIN','타이 리지백', '중형');
insert into breed values('192','ADMIN','타이완 독', '중형');
insert into breed values('193','ADMIN','티롤리언 하운드', '중형');
insert into breed values('194','ADMIN','티베탄 테리어', '중형');
insert into breed values('195','ADMIN','페루비안 잉카 오키드', '중형');
insert into breed values('196','ADMIN','펨브록 웰시 코기', '중형');
insert into breed values('197','ADMIN','포르셀엔', '중형');
insert into breed values('198','ADMIN','포르투기즈 쉽독', '중형');
insert into breed values('199','ADMIN','포르투기즈 워터 독', '중형');
insert into breed values('200','ADMIN','포르투기즈 포인트 독', '중형');
insert into breed values('201','ADMIN','포사바츠 하운드', '중형');
insert into breed values('202','ADMIN','폰 브리태니 그리폰', '중형');
insert into breed values('203','ADMIN','폴리시 로랜드 쉽독', '중형');
insert into breed values('204','ADMIN','폴리시 헌팅 독', '중형');
insert into breed values('205','ADMIN','퐁도드메르 스패니얼', '중형');
insert into breed values('206','ADMIN','푸들', '중형');
insert into breed values('207','ADMIN','풀리', '중형');
insert into breed values('208','ADMIN','프렌치 불독', '중형');
insert into breed values('209','ADMIN','프렌치 스패니얼', '중형');
insert into breed values('210','ADMIN','프렌치 포인팅 독(피레니안)', '중형');
insert into breed values('211','ADMIN','피니쉬 하운드', '중형');
insert into breed values('212','ADMIN','피니시 스피츠', '중형');
insert into breed values('213','ADMIN','피카디 셰퍼드', '중형');
insert into breed values('214','ADMIN','핀란드 라포니안 독', '중형');
insert into breed values('215','ADMIN','필드 스패니얼', '중형');
insert into breed values('216','ADMIN','하노베리언 센트 하운드', '중형');
insert into breed values('217','ADMIN','하이겐 하운드', '중형');
insert into breed values('218','ADMIN','할덴 하운드', '중형');
insert into breed values('219','ADMIN','해리어', '중형');
insert into breed values('220','ADMIN','헝가리안 쇼트-헤어드 포인터(비즐라)', '중형');
insert into breed values('221','ADMIN','홋카이도', '중형');
insert into breed values('222','ADMIN','고든 세터', '대형');
insert into breed values('223','ADMIN','골든 리트리버', '대형');
insert into breed values('224','ADMIN','그랜드 그리폰 방뎅', '대형');
insert into breed values('225','ADMIN','그레이 하운드', '대형');
insert into breed values('226','ADMIN','그레이트 가스코니 블루', '대형');
insert into breed values('227','ADMIN','그레이트 스위스 마운틴 독', '대형');
insert into breed values('228','ADMIN','그레이트 앵글로-프렌티 트라이컬러 하운드', '대형');
insert into breed values('229','ADMIN','그레이트 앵글로-프렌치 화이트 앤드 블랙 하운드', '대형');
insert into breed values('230','ADMIN','그레이트 앵글로-프렌치 화이트 엔드 오렌지 하운드', '대형');
insert into breed values('231','ADMIN','그린란드견', '대형');
insert into breed values('232','ADMIN','달마시안', '대형');
insert into breed values('233','ADMIN','더치 셰퍼드 독', '대형');
insert into breed values('234','ADMIN','도고 아르헨티노', '대형');
insert into breed values('235','ADMIN','도이치 스티첼할', '대형');
insert into breed values('236','ADMIN','드렌츠허 파트레이스', '대형');
insert into breed values('237','ADMIN','디어하운드', '대형');
insert into breed values('238','ADMIN','라지 문스터랜더', '대형');
insert into breed values('239','ADMIN','래브라도 리트리버', '대형');
insert into breed values('240','ADMIN','러시안 블랙 테리어', '대형');
insert into breed values('241','ADMIN','로디지안 리지백', '대형');
insert into breed values('242','ADMIN','로마니안 미오리틱 셰퍼드 독', '대형');
insert into breed values('243','ADMIN','로마니안 카프파티안 셰퍼드 독', '대형');
insert into breed values('244','ADMIN','마요르카 마스티프', '대형');
insert into breed values('245','ADMIN','마요르가 셰퍼드 독', '대형');
insert into breed values('246','ADMIN','머레머 앤드 아브루츠 쉽독', '대형');
insert into breed values('247','ADMIN','바셋하운드', '대형');
insert into breed values('248','ADMIN','벌고 포인팅 독', '대형');
insert into breed values('249','ADMIN','보르조이', '대형');
insert into breed values('250','ADMIN','보스 쉽독', '대형');
insert into breed values('251','ADMIN','보헤미안 와이어 헤어드 포인팅 그리폰', '대형');
insert into breed values('252','ADMIN','복서', '대형');
insert into breed values('253','ADMIN','부비에 데 플랑드르', '대형');
insert into breed values('254','ADMIN','브리아드', '대형');
insert into breed values('255','ADMIN','블랙 앤 탄 쿤하운드', '대형');
insert into breed values('256','ADMIN','블러드 하운드', '대형');
insert into breed values('257','ADMIN','빌리', '대형');
insert into breed values('258','ADMIN','뿌아뚜방', '대형');
insert into breed values('259','ADMIN','사를로스 울프혼드', '대형');
insert into breed values('260','ADMIN','세인트 미굴엘 캐틀 독', '대형');
insert into breed values('261','ADMIN','스패니시 그레이하운드', '대형');
insert into breed values('262','ADMIN','슬로바키안 쿠바크', '대형');
insert into breed values('263','ADMIN','시마론 우루과이', '대형');
insert into breed values('264','ADMIN','아르토이스 하운드', '대형');
insert into breed values('265','ADMIN','아메리칸 아키타', '대형');
insert into breed values('266','ADMIN','아키타', '대형');
insert into breed values('267','ADMIN','아프간 하운드', '대형');
insert into breed values('268','ADMIN','알렌테조 라페이로', '대형');
insert into breed values('269','ADMIN','에이디', '대형');
insert into breed values('270','ADMIN','오터 하운드', '대형');
insert into breed values('271','ADMIN','올드 대니시 포인팅 독', '대형');
insert into breed values('272','ADMIN','올드 잉글리시 쉽독', '대형');
insert into breed values('273','ADMIN','와이마라너', '대형');
insert into breed values('274','ADMIN','이탈리안 스피노네', '대형');
insert into breed values('275','ADMIN','이탈리안 포인팅 독', '대형');
insert into breed values('276','ADMIN','잉글리시 포인터', '대형');
insert into breed values('277','ADMIN','잉글리시 폭스하운드', '대형');
insert into breed values('278','ADMIN','자이언트 슈나우저', '대형');
insert into breed values('279','ADMIN','잠트훈트', '대형');
insert into breed values('280','ADMIN','저먼 롱헤어드 포인팅 독', '대형');
insert into breed values('281','ADMIN','저먼 셰퍼드', '대형');
insert into breed values('282','ADMIN','저먼 쇼트-헤어드 포인팅 독', '대형');
insert into breed values('283','ADMIN','저먼 와이어헤어드 포인팅 독', '대형');
insert into breed values('284','ADMIN','체서피크 베이 리트리버', '대형');
insert into breed values('285','ADMIN','체코슬로바키아 늑대개', '대형');
insert into breed values('286','ADMIN','카니리안 와런 하운드(포덴고카나리오)', '대형');
insert into breed values('287','ADMIN','카네코르소', '대형');
insert into breed values('288','ADMIN','카스트로 라보레이로 독', '대형');
insert into breed values('289','ADMIN','컬리 코티드 리트리버', '대형');
insert into breed values('290','ADMIN','코몬돌', '대형');
insert into breed values('291','ADMIN','쿠바츠', '대형');
insert into breed values('292','ADMIN','클럼버 스패니얼', '대형');
insert into breed values('293','ADMIN','타트라 마운틴 쉽독', '대형');
insert into breed values('294','ADMIN','파라오 하운드', '대형');
insert into breed values('295','ADMIN','폴리시 하운드', '대형');
insert into breed values('296','ADMIN','푸델포인터', '대형');
insert into breed values('297','ADMIN','프레사 카나리오', '대형');
insert into breed values('298','ADMIN','프렌치 트라이컬러 하운드', '대형');
insert into breed values('299','ADMIN','프렌치 포인팅 독(가스코뉴)', '대형');
insert into breed values('300','ADMIN','프렌치 화이트 앤드 블랙 하운드', '대형');
insert into breed values('301','ADMIN','프렌치 화이트 앤드 오렌지 하운드', '대형');
insert into breed values('302','ADMIN','프리지안 워터 독', '대형');
insert into breed values('303','ADMIN','플랫 코티드 리트리버', '대형');
insert into breed values('304','ADMIN','피카디 스패니얼', '대형');
insert into breed values('305','ADMIN','해밀턴스퉤바레', '대형');
insert into breed values('306','ADMIN','헝가리안 그레이하운드(마자르 아가)', '대형');
insert into breed values('307','ADMIN','헝가리안 와이어-헤어드 포인터(비즐라) 소개', '대형');
insert into breed values('308','ADMIN','호바와트', '대형');
insert into breed values('309','ADMIN','화이트 스위스 셰퍼드 독', '대형');
insert into breed values('310','ADMIN','그레이트 데인', '초대형');
insert into breed values('311','ADMIN','나폴리탄 마스티프', '초대형');
insert into breed values('312','ADMIN','뉴펀들랜드', '초대형');
insert into breed values('313','ADMIN','도그 드 보르도', '초대형');
insert into breed values('314','ADMIN','랜시어', '초대형');
insert into breed values('315','ADMIN','레온베르거', '초대형');
insert into breed values('316','ADMIN','로트바일러', '초대형');
insert into breed values('317','ADMIN','마스티프', '초대형');
insert into breed values('318','ADMIN','버니즈 마운틴 독', '초대형');
insert into breed values('319','ADMIN','불마스티프', '초대형');
insert into breed values('320','ADMIN','브로홀머', '초대형');
insert into breed values('321','ADMIN','세인트 버나드', '초대형');
insert into breed values('322','ADMIN','스패니스 마스티프', '초대형');
insert into breed values('323','ADMIN','아이리시 울프하운드', '초대형');
insert into breed values('324','ADMIN','에스트렐라 캐틀 독', '초대형');
insert into breed values('325','ADMIN','캉칼 셰퍼드 독', '초대형');
insert into breed values('326','ADMIN','티베탄 마스티프', '초대형');
insert into breed values('327','ADMIN','피레니안 마스티프', '초대형');