name: Push Docker Image to Amazon ECR

on:
  push:
    branches:
      - dev

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: cocobob/be-api

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: develop

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate Application Environment Variables File
        env:
          DATASOURCE_URL: ${{ secrets.DATASOURCE_URL }}
          DATASOURCE_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          ACCESS_TOKEN_VALID_TIME: ${{ secrets.ACCESS_TOKEN_VALID_TIME }}
          REFRESH_TOKEN_VALID_TIME: ${{ secrets.REFRESH_TOKEN_VALID_TIME }}
        run: |
          echo "spring:" >> ./src/main/resources/application-secret.yml
          echo "  datasource:" >> ./src/main/resources/application-secret.yml
          echo "    url: $DATASOURCE_URL" >> ./src/main/resources/application-secret.yml
          echo "    username: admin" >> ./src/main/resources/application-secret.yml
          echo "    password: $DATASOURCE_PASSWORD" >> ./src/main/resources/application-secret.yml
          echo "    driver-class-name: org.mariadb.jdbc.Driver" >> ./src/main/resources/application-secret.yml
          echo "  jwt:" >> ./src/main/resources/application-secret.yml
          echo "    secretKey: $JWT_SECRET_KEY" >> ./src/main/resources/application-secret.yml
          echo "    accessTokenValidTime: $ACCESS_TOKEN_VALID_TIME" >> ./src/main/resources/application-secret.yml
          echo "    refreshTokenValidTime: $REFRESH_TOKEN_VALID_TIME" >> ./src/main/resources/application-secret.yml

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Test with Gradle
        run: ./gradlew test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          echo $ECR_REGISTRY
          echo $IMAGE_TAG
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY"

      - name: Create Deploy Script Zip
        run: zip -r deploy-script.zip ./scripts ./appspec.yml
        shell: bash

      - name: Upload to S3
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run:
          aws s3 cp --region ap-northeast-2 ./deploy-script.zip s3://cocobob-storage/cocobob-be-dev/deploy-script.zip

      - name: Deploy
        run: aws deploy create-deployment
          --application-name cocobob-be-dev
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name cocobob-be-dev
          --s3-location bucket=cocobob-storage,key=cocobob-be-dev/deploy-script.zip,bundleType=zip
